// main/shared/src/domain/index.ts

export {
  getAuditActionTone,
  getAuditSeverityTone,
  buildAuditEvent,
  sanitizeMetadata,
  AUDIT_ACTION_REGEX,
  AUDIT_CATEGORIES,
  AUDIT_SEVERITIES,
  auditEventSchema,
  auditLogFilterSchema,
  auditLogListResponseSchema,
  createAuditEventSchema,
  type AuditBuilderParams,
  type AuditCategory,
  type AuditEvent,
  type AuditLogFilter,
  type AuditLogListResponse,
  type AuditSeverity,
  type CreateAuditEvent,
} from './audit-log';

export {
  validatePassword,
  authContract,
  AUTH_ERROR_MESSAGES,
  AUTH_SUCCESS_MESSAGES,
  AccountLockedError,
  EmailSendError,
  HTTP_ERROR_MESSAGES,
  isKnownAuthError,
  mapErrorToHttpResponse,
  authResponseSchema,
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema,
  loginRequestSchema,
  logoutResponseSchema,
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyRequestSchema,
  magicLinkVerifyResponseSchema,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpLoginChallengeResponseSchema,
  totpLoginVerifyRequestSchema,
  totpVerifyRequestSchema,
  totpVerifyResponseSchema,
  setPhoneRequestSchema,
  setPhoneResponseSchema,
  verifyPhoneRequestSchema,
  verifyPhoneResponseSchema,
  removePhoneResponseSchema,
  smsChallengeRequestSchema,
  smsVerifyRequestSchema,
  deviceItemSchema,
  deviceListResponseSchema,
  trustDeviceResponseSchema,
  invalidateSessionsResponseSchema,
  webauthnOptionsResponseSchema,
  webauthnRegisterVerifyResponseSchema,
  type ErrorMapperLogger,
  type ErrorMapperOptions,
  type ErrorStatusCode,
  type HttpErrorResponse,
  type AuthResponse,
  type ChangeEmailRequest,
  type ChangeEmailResponse,
  type ConfirmEmailChangeRequest,
  type ConfirmEmailChangeResponse,
  type EmailVerificationRequest,
  type EmailVerificationResponse,
  type ForgotPasswordRequest,
  type ForgotPasswordResponse,
  type LoginRequest,
  type LogoutResponse,
  type MagicLinkRequest,
  type MagicLinkRequestResponse,
  type MagicLinkVerifyRequest,
  type MagicLinkVerifyResponse,
  type RefreshResponse,
  type RegisterRequest,
  type RegisterResponse,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type SetPasswordRequest,
  type SetPasswordResponse,
  type SmsLoginChallengeResponse,
  type TotpLoginChallengeResponse,
  type TotpLoginVerifyRequest,
  type TotpSetupResponse,
  type TotpStatusResponse,
  type TotpVerifyRequest,
  type TotpVerifyResponse,
  type SetPhoneRequest,
  type SetPhoneResponse,
  type VerifyPhoneRequest,
  type VerifyPhoneResponse,
  type RemovePhoneResponse,
  type SmsChallengeRequest,
  type SmsChallengeResponse,
  type SmsVerifyRequest,
  type DeviceItem,
  type DeviceListResponse,
  type TrustDeviceResponse,
  type InvalidateSessionsResponse,
  type WebauthnOptionsResponse,
  type WebauthnRegisterVerifyResponse,
} from './auth';

export {
  PLAN_FEES,
  calculateProration,
  billingContract,
  BILLING_PROVIDERS,
  FEATURE_KEYS,
  INVOICE_STATUSES,
  PAYMENT_METHOD_TYPES,
  PLAN_INTERVALS,
  SUBSCRIPTION_STATUSES,
  addPaymentMethodRequestSchema,
  cancelSubscriptionRequestSchema,
  cardDetailsSchema,
  checkoutRequestSchema,
  checkoutResponseSchema,
  invoiceSchema,
  invoicesListResponseSchema,
  paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema,
  planFeatureSchema,
  planSchema,
  plansListResponseSchema,
  setupIntentResponseSchema,
  subscriptionActionResponseSchema,
  subscriptionResponseSchema,
  subscriptionSchema,
  updateSubscriptionRequestSchema,
  adminBillingStatsSchema,
  adminPlansListResponseSchema,
  createPlanRequestSchema,
  updatePlanRequestSchema,
  BillingProviderError,
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError,
  CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError,
  CheckoutSessionError,
  CustomerNotFoundError,
  InvoiceNotFoundError,
  isBillingProviderError,
  isPlanError,
  isSubscriptionError,
  PaymentMethodNotFoundError,
  PaymentMethodValidationError,
  PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  PlanNotFoundError,
  SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError,
  WebhookEventAlreadyProcessedError,
  WebhookSignatureError,
  type BillingStats,
  type BillingProvider,
  type AddPaymentMethodRequest,
  type CancelSubscriptionRequest,
  type CardDetails,
  type CheckoutRequest,
  type CheckoutResponse,
  type FeatureKey,
  type Invoice,
  type InvoiceResponse,
  type InvoiceStatus,
  type InvoicesListResponse,
  type PaymentMethod,
  type PaymentMethodResponse,
  type PaymentMethodType,
  type PaymentMethodsListResponse,
  type Plan,
  type PlanFeature,
  type PlanId,
  type PlanInterval,
  type PlansListResponse,
  type SetupIntentResponse,
  type Subscription,
  type SubscriptionActionResponse,
  type SubscriptionId,
  type SubscriptionResponse,
  type SubscriptionStatus,
  type UpdateSubscriptionRequest,
  type AdminBillingStats,
  type AdminPlansListResponse,
  type CreatePlanRequest,
  type UpdatePlanRequest,
  type BillingService,
  type CheckoutParams,
  type CheckoutResult,
  type CreateProductParams,
  type CreateProductResult,
  type NormalizedEventType,
  type NormalizedWebhookEvent,
  type ProviderInvoice,
  type ProviderPaymentMethod,
  type ProviderSubscription,
  type SetupIntentResult,
  assertEntitled,
  assertWithinLimit,
  hasActiveSubscription,
  isEntitled,
  resolveEntitlements,
  type EntitlementInput,
  type FeatureEntitlement,
  type ResolvedEntitlements,
  type SubscriptionState,
} from './billing';

export {
  getEffectiveConsent,
  isConsentGranted,
  needsReacceptance,
  CONSENT_TYPES,
  consentLogSchema,
  createConsentLogSchema,
  createDataExportRequestSchema,
  createLegalDocumentSchema,
  createUserAgreementSchema,
  DATA_EXPORT_STATUSES,
  DATA_EXPORT_TYPES,
  dataExportRequestSchema,
  DOCUMENT_TYPES,
  legalDocumentSchema,
  updateConsentPreferencesRequestSchema,
  updateLegalDocumentSchema,
  userAgreementSchema,
  type ConsentLog,
  type ConsentType,
  type CreateConsentLog,
  type CreateDataExportRequest,
  type CreateLegalDocument,
  type CreateUserAgreement,
  type DataExportRequest,
  type DataExportStatus,
  type DataExportType,
  type DocumentType,
  type LegalDocument,
  type UpdateConsentPreferencesRequest,
  type UpdateLegalDocument,
  type UserAgreement,
} from './compliance';

export {
  evaluateFlag,
  createFeatureFlagRequestSchema,
  featureFlagSchema,
  setTenantFeatureOverrideRequestSchema,
  tenantFeatureOverrideSchema,
  updateFeatureFlagRequestSchema,
  type CreateFeatureFlagRequest,
  type FeatureFlag,
  type SetTenantFeatureOverrideRequest,
  type TenantFeatureOverride,
  type UpdateFeatureFlagRequest,
} from './feature-flags';

export {
  getJobStatusLabel,
  getJobStatusTone,
  calculateBackoff,
  canRetry,
  isTerminalStatus,
  shouldProcess,
  createJobSchema,
  JOB_PRIORITIES,
  JOB_PRIORITY_VALUES,
  JOB_STATUSES,
  jobSchema,
  updateJobSchema,
  type CreateJob,
  type DomainJob,
  type JobPriority,
  type JobStatus,
  type UpdateJob,
} from './jobs';

export {
  getInvitationStatusTone,
  getTenantRoleTone,
  canAcceptInvite,
  canAssignRole,
  canChangeRole,
  canLeave,
  canRemoveMember,
  canRevokeInvite,
  getNextOwnerCandidate,
  getRoleLevel,
  hasAtLeastRole,
  isInviteExpired,
  isSoleOwner,
  INVITATION_STATUSES,
  acceptInvitationSchema,
  addMemberSchema,
  createInvitationSchema,
  invitationSchema,
  membershipSchema,
  updateMembershipRoleSchema,
  type AcceptInvitation,
  type AddMember,
  type CreateInvitation,
  type Invitation,
  type InvitationStatus,
  type Membership,
  type UpdateMembershipRole,
} from './membership';

export {
  notificationsContract,
  getNotificationLevelTone,
  shouldSendNotification,
  baseMarkAsReadRequestSchema,
  deleteNotificationResponseSchema,
  markReadResponseSchema,
  notificationDeleteRequestSchema,
  NOTIFICATION_TYPES,
  notificationPreferencesSchema,
  notificationSchema,
  notificationsListRequestSchema,
  notificationsListResponseSchema,
  sendNotificationRequestSchema,
  sendNotificationResponseSchema,
  preferencesResponseSchema,
  subscribeRequestSchema,
  subscribeResponseSchema,
  unsubscribeRequestSchema,
  unsubscribeResponseSchema,
  updatePreferencesRequestSchema,
  vapidKeyResponseSchema,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  NOTIFICATION_PAYLOAD_MAX_SIZE,
  NotificationRateLimitError,
  NotificationSendError,
  NotificationsDisabledError,
  PayloadTooLargeError,
  PreferencesNotFoundError,
  ProviderError,
  ProviderNotConfiguredError,
  PushProviderNotConfiguredError,
  PushSubscriptionExistsError,
  PushSubscriptionNotFoundError,
  QuietHoursActiveError,
  SubscriptionExistsError,
  SubscriptionExpiredError,
  SubscriptionNotFoundError,
  VapidNotConfiguredError,
  DEFAULT_NOTIFICATION_PREFERENCES,
  type BaseMarkAsReadRequest,
  type DeleteNotificationResponse,
  type MarkReadResponse,
  type NotificationDeleteRequest,
  type Notification,
  type NotificationPreferences,
  type NotificationPreferencesConfig,
  type NotificationsListRequest,
  type NotificationsListResponse,
  type BatchSendResult,
  type NotificationAction,
  type NotificationChannel,
  type NotificationMessage,
  type NotificationPayload,
  type NotificationPriority,
  type NotificationType,
  type NotificationTypePreference,
  type PreferencesResponse,
  type PushSubscription,
  type PushSubscriptionKeys,
  type SendNotificationRequest,
  type SendNotificationResponse,
  type PushSendResult,
  type StoredPushSubscription,
  type SubscribeRequest,
  type SubscribeResponse,
  type UnsubscribeRequest,
  type UnsubscribeResponse,
  type UpdatePreferencesRequest,
  type VapidKeyResponse,
} from './notifications';

export {
  getSessionAge,
  isSessionActive,
  isSessionRevoked,
  createUserSessionSchema,
  updateUserSessionSchema,
  userSessionSchema,
  type CreateUserSession,
  type UpdateUserSession,
  type UserSession,
} from './sessions';

export {
  createTenantSchema,
  extractEmailDomain,
  isEmailDomainAllowed,
  tenantSchema,
  transferOwnershipSchema,
  updateTenantSchema,
  type CreateTenantInput,
  type Tenant,
  type TransferOwnershipInput,
  type UpdateTenantInput,
} from './tenant';

export {
  aggregateSnapshots,
  aggregateValues,
  isOverQuota,
  usageMetricSchema,
  usageSnapshotSchema,
  type UsageMetric,
  type UsageSnapshot,
} from './usage-metering';

export {
  getAllRoles,
  getRoleDisplayName,
  isAdmin,
  isModerator,
  isUser,
  canUser,
  hasRole,
  isOwner,
  isRegularUser,
  usersContract,
  APP_ROLES,
  appRoleSchema,
  avatarDeleteResponseSchema,
  avatarUploadRequestSchema,
  avatarUploadResponseSchema,
  changePasswordRequestSchema,
  changePasswordResponseSchema,
  revokeAllSessionsResponseSchema,
  revokeSessionResponseSchema,
  sessionSchema,
  sessionsListResponseSchema,
  updateProfileRequestSchema,
  userIdSchema,
  userSchema,
  calculateDeletionGracePeriodEnd,
  canDeactivate,
  canReactivate,
  canRequestDeletion,
  getAccountStatus,
  isAccountActive,
  isAccountDeactivated,
  isAccountPendingDeletion,
  isWithinDeletionGracePeriod,
  ACCOUNT_DELETION_GRACE_PERIOD_DAYS,
  deactivateAccountRequestSchema,
  deleteAccountRequestSchema,
  type AccountLifecycleFields,
  type AccountLifecycleResponse,
  type AccountStatus,
  type DeactivateAccountRequest,
  type DeleteAccountRequest,
  type AppRole,
  type AvatarDeleteResponse,
  type AvatarUploadRequest,
  type AvatarUploadResponse,
  type ChangePasswordRequest,
  type ChangePasswordResponse,
  type RevokeAllSessionsResponse,
  type RevokeSessionResponse,
  type Session,
  type SessionsListResponse,
  type UpdateProfileRequest,
  type User,
  type UserId,
} from './users';

export {
  webhooksContract,
  calculateRetryDelay,
  isDeliveryTerminal,
  matchesEventFilter,
  shouldRetryDelivery,
  createWebhookDeliverySchema,
  createWebhookSchema,
  rotateSecretResponseSchema,
  updateWebhookDeliverySchema,
  updateWebhookSchema,
  WEBHOOK_DELIVERY_STATUSES,
  webhookDeleteResponseSchema,
  webhookDeliveryItemSchema,
  webhookDeliverySchema,
  webhookItemSchema,
  webhookListResponseSchema,
  webhookMutationResponseSchema,
  webhookResponseSchema,
  webhookSchema,
  webhookWithDeliveriesSchema,
  type CreateWebhook,
  type CreateWebhookDelivery,
  type RotateSecretResponse,
  type UpdateWebhook,
  type UpdateWebhookDelivery,
  type Webhook,
  type WebhookDeleteResponse,
  type WebhookDeliveryItem,
  type WebhookDelivery,
  type WebhookDeliveryStatus,
  type WebhookItem,
  type WebhookListResponse,
  type WebhookMutationResponse,
  type WebhookResponse,
  type WebhookWithDeliveries,
} from './webhooks';

export {
  realtimeContract,
  conflictResponseSchema,
  getRecordsRequestSchema,
  getRecordsResponseSchema,
  listInsertOperationSchema,
  listPositionSchema,
  listRemoveOperationSchema,
  operationSchema,
  recordMapSchema,
  recordPointerSchema,
  recordSchema,
  setNowOperationSchema,
  setOperationSchema,
  transactionSchema,
  writeResponseSchema,
  type ConflictResponse,
  type GetRecordsRequest,
  type GetRecordsResponse,
  type ListInsertOperation,
  type ListPosition,
  type ListRemoveOperation,
  type RealtimeOperation,
  type RealtimeRecord,
  type RealtimeTransaction,
  type RecordMap,
  type RecordPointer,
  type SetNowOperation,
  type SetOperation,
  type WriteResponse,
  PROTECTED_FIELDS,
  REALTIME_ERRORS,
  applyOperation,
  applyOperations,
  checkVersionConflicts,
  getOperationPointers,
  isFieldMutable,
  setPath,
  type ApplyOperationsResult,
  type VersionConflict,
} from './realtime';

// Media
export {
  ALL_MEDIA_EXTENSIONS,
  ALLOWED_MEDIA_MIME_TYPES,
  AUDIO_EXTENSIONS,
  EXT_TO_MIME,
  IMAGE_EXTENSIONS,
  MAX_CHUNK_SIZE,
  MAX_FILENAME_LENGTH,
  MAX_UPLOAD_FILE_SIZE,
  MAX_UPLOAD_TIMEOUT_MS,
  MIME_TO_EXT,
  VIDEO_EXTENSIONS,
  detectFileType,
  detectFileTypeFromPath,
  generateFileId,
  isAllowedFileType,
  parseAudioMetadataFromBuffer,
  sanitizeFilename,
  validateUploadConfig,
  type AudioMetadata,
  type AudioProcessingOptions,
  type ContentModerationResult,
  type FileTypeResult,
  type ImageProcessingOptions,
  type MediaMetadata,
  type MediaProcessingOptions,
  type ProcessingResult,
  type SecurityScanResult,
  type UploadConfig,
  type VideoProcessingOptions,
} from './media';

export {
  getActorTypeTone,
  ACTOR_TYPES,
  activitySchema,
  actorTypeSchema,
  createActivitySchema,
  type Activity,
  type ActorType,
  type CreateActivity,
} from './activities';

export {
  apiKeysContract,
  apiKeySchema,
  apiKeyItemSchema,
  createApiKeyRequestSchema,
  createApiKeyResponseSchema,
  createApiKeySchema,
  deleteApiKeyResponseSchema,
  listApiKeysResponseSchema,
  revokeApiKeyResponseSchema,
  updateApiKeySchema,
  type ApiKey,
  type ApiKeyItem,
  type CreateApiKeyRequest,
  type CreateApiKeyResponse,
  type CreateApiKey,
  type DeleteApiKeyResponse,
  type ListApiKeysResponse,
  type RevokeApiKeyResponse,
  type UpdateApiKey,
} from './api-keys';

export {
  createEmailLogEntrySchema,
  createEmailTemplateSchema,
  EMAIL_PROVIDERS,
  EMAIL_STATUSES,
  emailLogEntrySchema,
  emailProviderSchema,
  emailStatusSchema,
  emailTemplateSchema,
  updateEmailTemplateSchema,
  type CreateEmailLogEntry,
  type CreateEmailTemplate,
  type EmailLogEntry,
  type EmailProvider,
  type EmailStatus,
  type EmailTemplate,
  type UpdateEmailTemplate,
} from './email';

export {
  createFileRecordSchema,
  fileUploadRequestSchema,
  FILE_PURPOSES,
  filePurposeSchema,
  fileRecordSchema,
  STORAGE_PROVIDERS,
  storageProviderSchema,
  updateFileRecordSchema,
  type CreateFileRecord,
  type FilePurpose,
  type FileRecord,
  type FileUploadRequest,
  type StorageProvider,
  type UpdateFileRecord,
} from './files';

export {
  createTenantSettingSchema,
  tenantSettingSchema,
  updateTenantSettingSchema,
  type CreateTenantSetting,
  type TenantSetting,
  type UpdateTenantSetting,
} from './tenant-settings';

export {
  DEFAULT_CONTRAST_MODE,
  DEFAULT_DENSITY,
  densityMultipliers,
  getContrastCssVariables,
  getDensityCssVariables,
  getSpacingForDensity,
  highContrastDarkOverrides,
  highContrastLightOverrides,
  type ContrastMode,
  type Density,
} from './theme';
