// src/client/ui/src/index.ts
// Shared UI components for all platforms (web, desktop, mobile)

// Elements - Atomic UI building blocks
export {
  Alert,
  Avatar,
  Badge,
  Box,
  Button,
  Checkbox,
  CloseButton,
  Divider,
  EnvironmentBadge,
  FileInput,
  Heading,
  Input,
  Kbd,
  MenuItem,
  OAuthButton,
  PasswordInput,
  Progress,
  Skeleton,
  SkipLink,
  Spinner,
  Switch,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
  Text,
  TextArea,
  Toaster,
  Tooltip,
  VersionBadge,
  VisuallyHidden,
} from './elements';

// Components - Composed multi-part components
export {
  Accordion,
  AuthFormLayout,
  Card,
  DelayedFallback,
  Dialog,
  Dropdown,
  EmptyState,
  ErrorBoundary,
  FocusTrap,
  FormField,
  Image,
  // Billing
  InvoiceList,
  InvoiceRow,
  LoadingContainer,
  Pagination,
  PaymentMethodCard,
  PeekLink,
  PlanCard,
  Popover,
  PricingTable,
  Radio,
  RadioGroup,
  Select,
  Slider,
  SubscriptionStatus,
  Tabs,
  Toast,
  ToastContainer,
  UndoHistoryPanel,
  UndoRedoToolbar,
} from './components';
export type {
  DelayedFallbackProps,
  EmptyStateProps,
  ErrorBoundaryProps,
  InvoiceListProps,
  InvoiceRowProps,
  PaymentMethodCardProps,
  PeekLinkProps,
  PlanCardProps,
  PricingTableProps,
  SubscriptionStatusProps,
  TabItem,
  TabsProps,
  UndoHistoryPanelProps,
  UndoRedoToolbarProps,
} from './components';

// Layouts - Page and section layouts
export {
  AppShell,
  AuthLayout,
  BottombarLayout,
  Container,
  LeftSidebarLayout,
  Modal,
  Overlay,
  PageContainer,
  ProtectedRoute,
  ResizablePanel,
  ResizablePanelGroup,
  ResizableSeparator,
  RightSidebarLayout,
  ScrollArea,
  SidePeek,
  StackedLayout,
  TopbarLayout,
} from './layouts';
export type {
  AppShellProps,
  BottombarLayoutProps,
  LeftSidebarLayoutProps,
  RightSidebarLayoutProps,
  SidePeekRootProps,
  SidePeekSize,
  TopbarLayoutProps,
} from './layouts';

// Theme
export {
  ThemeProvider,
  colors,
  darkColors,
  lightColors,
  motion,
  radius,
  spacing,
  typography,
  useTheme,
} from './theme';
export type {
  ContrastMode,
  DarkColors,
  Density,
  LightColors,
  Radius,
  ThemeColors,
  ThemeContextValue,
  ThemeProviderProps,
} from './theme';

// Utilities
export { Markdown, SyntaxHighlighter, cn } from './utils';
