packages:
  # Applications
  - 'apps/*'
  # Infrastructure packages
  - 'packages/backend-core'
  - 'packages/db'
  # Business modules
  - 'modules/*'
  # Core
  - 'packages/shared'
  # Client
  - 'client/*'
  # Premium packages
  - 'premium/*'
  - 'premium/*/*'
