// apps/server/src/modules/index.ts
export {
  adminRoutes,
  authRoutes,
  createAuthGuard,
  handleAdminUnlock,
  handleForgotPassword,
  handleGetPreferences,
  handleGetRecords,
  handleGetVapidKey,
  handleLogin,
  handleLogout,
  handleMe,
  handleRefresh,
  handleRegister,
  handleResendVerification,
  handleResetPassword,
  handleSendNotification,
  handleSubscribe,
  handleTestNotification,
  handleUnsubscribe,
  handleUpdatePreferences,
  handleVerifyEmail,
  handleWrite,
  notificationRoutes,
  notificationRoutesConfig,
  protectedRoute,
  publicRoute,
  realtimeRoutes,
  RecordNotFoundError,
  registerRouteMap,
  registerRoutes,
  registerRealtimeTable,
  systemRoutes,
  userRoutes,
  VersionConflictError,
} from './routes';
export type {
  HttpMethod,
  ProtectedHandler,
  PublicHandler,
  ReplyWithCookies,
  RequestWithCookies,
  RouteDefinition,
  RouteHandler,
  RouteMap,
  RouteResult,
  RouterOptions,
  ValidationSchema,
} from './routes';
