// packages/shared/src/domain/billing/index.ts

export { PLAN_FEES, calculateProration, type BillingStats } from './billing.logic';

export { billingContract } from './billing.contracts';

export {
  BILLING_PROVIDERS,
  FEATURE_KEYS,
  INVOICE_STATUSES,
  PAYMENT_METHOD_TYPES,
  PLAN_INTERVALS,
  SUBSCRIPTION_STATUSES,
  addPaymentMethodRequestSchema,
  cancelSubscriptionRequestSchema,
  cardDetailsSchema,
  checkoutRequestSchema,
  checkoutResponseSchema,
  invoiceSchema,
  invoicesListResponseSchema,
  paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema,
  planFeatureSchema,
  planSchema,
  plansListResponseSchema,
  setupIntentResponseSchema,
  subscriptionActionResponseSchema,
  subscriptionResponseSchema,
  subscriptionSchema,
  updateSubscriptionRequestSchema,
  type AddPaymentMethodRequest,
  type BillingProvider,
  type CancelSubscriptionRequest,
  type CardDetails,
  type CheckoutRequest,
  type CheckoutResponse,
  type FeatureKey,
  type Invoice,
  type InvoiceStatus,
  type InvoicesListResponse,
  type PaymentMethod,
  type PaymentMethodResponse,
  type PaymentMethodType,
  type PaymentMethodsListResponse,
  type Plan,
  type PlanFeature,
  type PlanInterval,
  type PlanId,
  type PlansListResponse,
  type SetupIntentResponse,
  type Subscription,
  type SubscriptionActionResponse,
  type SubscriptionId,
  type SubscriptionResponse,
  type SubscriptionStatus,
  type UpdateSubscriptionRequest,
} from './billing.schemas';

export {
  adminBillingStatsSchema,
  adminPlanResponseSchema,
  adminPlanSchema,
  adminPlansListResponseSchema,
  createPlanRequestSchema,
  syncStripeResponseSchema,
  updatePlanRequestSchema,
  type AdminBillingStats,
  type AdminPlan,
  type AdminPlanResponse,
  type AdminPlansListResponse,
  type CreatePlanRequest,
  type SyncStripeResponse,
  type UpdatePlanRequest,
} from './billing.admin.schemas';

export {
  BillingProviderError,
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError,
  CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError,
  CheckoutSessionError,
  CustomerNotFoundError,
  InvoiceNotFoundError,
  isBillingProviderError,
  isPlanError,
  isSubscriptionError,
  PaymentMethodNotFoundError,
  PaymentMethodValidationError,
  PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  PlanNotFoundError,
  SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError,
  WebhookEventAlreadyProcessedError,
  WebhookSignatureError,
} from './billing.errors';
