// Global styles for the application
export const globalStyles = {
  // Base styles
  body: {
    margin: "0px",
    padding: "0px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol"',
    background: "var(--background)",
    color: "var(--text-color)",
  },
  bodyInputButton: {
    fontSize: "18px",
  },
  boxSizing: {
    boxSizing: "border-box",
  },

  // Variables
  variables: {
    light: {
      background: "rgba(255, 255, 255, 1)",
      background2: "rgba(242, 242, 247, 1)",
      background3: "rgba(255, 255, 255, 1)",
      transparent1: "rgba(0, 0, 18, 0.1)",
      transparent2: "rgba(0, 0, 18, 0.2)",
      transparent3: "rgba(0, 0, 18, 0.3)",
      transparent4: "rgba(0, 0, 18, 0.4)",
      textColor: "rgba(0, 0, 0, 1)",
      textColor2: "rgba(61, 61, 66, 0.6)",
      textColor3: "rgba(61, 61, 66, 0.3)",
      textColor4: "rgba(61, 61, 66, 0.18)",
      placeholder: "rgba(61, 61, 66, 0.3)",
      separator: "rgba(61, 61, 66, 0.29)",
      separatorOpaque: "rgba(199, 199, 199, 1)",
      hover: "rgba(0, 122, 255, 0.3)",
      active: "rgba(0, 122, 255, 0.5)",
      blue: "rgba(0, 122, 255, 1)",
      green: "rgba(51, 199, 89, 1)",
      indigo: "rgba(89, 87, 214, 1)",
      orange: "rgba(255, 148, 0, 1)",
      pink: "rgba(255, 46, 84, 1)",
      purple: "rgba(176, 82, 222, 1)",
      red: "rgba(255, 59, 48, 1)",
      teal: "rgba(89, 199, 250, 1)",
      yellow: "rgba(255, 204, 0, 1)",
      gray: "rgba(143, 143, 148, 1)",
      gray2: "rgba(173, 173, 179, 1)",
      gray3: "rgba(199, 199, 204, 1)",
      gray4: "rgba(209, 209, 214, 1)",
      gray5: "rgba(230, 230, 235, 1)",
      gray6: "rgba(242, 242, 247, 1)",
      popupBackground: "var(--background)",
      shadow:
        "rgba(15, 15, 15, 0.05) 0px 0px 0px 1px, rgba(15, 15, 15, 0.1) 0px 3px 6px, rgba(15, 15, 15, 0.2) 0px 9px 24px",
    },
    dark: {
      background: "rgba(0, 0, 0, 1)",
      background2: "rgb(36, 36, 40)",
      background3: "rgb(48, 48, 52)",
      transparent1: "rgba(243, 243, 255, 0.1)",
      transparent2: "rgba(243, 243, 255, 0.2)",
      transparent3: "rgba(243, 243, 255, 0.3)",
      transparent4: "rgba(243, 243, 255, 0.4)",
      textColor: "rgba(255, 255, 255, 1)",
      textColor2: "rgba(235, 235, 245, 0.6)",
      textColor3: "rgba(235, 235, 245, 0.3)",
      textColor4: "rgba(235, 235, 245, 0.18)",
      placeholder: "rgba(235, 235, 245, 0.3)",
      separator: "rgba(84, 84, 89, 0.6)",
      separatorOpaque: "rgba(56, 56, 59, 1)",
      hover: "rgba(10, 133, 255, 0.3)",
      active: "rgba(10, 133, 255, 0.5)",
      blue: "rgba(10, 133, 255, 1)",
      green: "rgba(48, 209, 89, 1)",
      indigo: "rgba(94, 92, 230, 1)",
      orange: "rgba(255, 158, 10, 1)",
      pink: "rgba(255, 56, 94, 1)",
      purple: "rgba(191, 89, 242, 1)",
      red: "rgba(255, 69, 59, 1)",
      teal: "rgba(99, 209, 255, 1)",
      yellow: "rgba(255, 214, 10, 1)",
      gray: "rgba(143, 143, 148, 1)",
      gray2: "rgba(99, 99, 102, 1)",
      gray3: "rgba(71, 71, 74, 1)",
      gray4: "rgba(59, 59, 61, 1)",
      gray5: "rgba(43, 43, 46, 1)",
      gray6: "rgba(28, 28, 31, 1)",
      popupBackground: "var(--background2)",
      shadow:
        "rgba(255, 255, 255, 0.2) 0px 0px 0px 1px, rgba(15, 15, 15, 0.1) 0px 3px 6px, rgba(15, 15, 15, 0.2) 0px 9px 24px",
    },
  },

  // Form elements
  input: {
    color: "var(--text-color)",
    background: "transparent",
  },
  inputPlaceholder: {
    color: "var(--placeholder)",
  },
  button: {
    background: "transparent",
  },

  // Links
  a: {
    color: "var(--text-color2)",
  },

  // Feedback states
  feedbackHover: {
    backgroundColor: "var(--hover)",
  },
  feedbackActive: {
    backgroundColor: "var(--active)",
  },

  // Focus states
  focus: {
    outline: "2px solid var(--orange)",
    outlineOffset: "-2px",
  },

  // Spinner animation
  spinner: {
    width: "1.25em",
    height: "1.25em",
    border: "0.15em solid var(--text-color2)",
    borderBottomColor: "transparent",
    borderRadius: "100%",
    display: "inline-block",
    boxSizing: "border-box",
    animation: "rotation 800ms linear infinite",
  },
  keyframes: {
    rotation: {
      from: {
        transform: "rotate(0deg)",
      },
      to: {
        transform: "rotate(360deg)",
      },
    },
  },
};

// Image Gallery styles
export const imageGalleryStyles = {
  imageGallery: {
    position: "relative",
    width: "100%",
    maxWidth: "100%",
    overflow: "hidden",
    background: "var(--background3)",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
  },
  galleryMain: {
    position: "relative",
    width: "100%",
    height: "100%",
    display: "flex",
    overflow: "hidden",
  },
  galleryImageContainer: {
    minWidth: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "transform 0.3s ease",
  },
  galleryImage: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain",
    userSelect: "none",
  },
  galleryNav: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(0, 0, 0, 0.5)",
    color: "white",
    border: "none",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    opacity: 0.7,
    transition: "opacity 0.2s",
    zIndex: 10,
  },
  galleryNavHover: {
    opacity: 1,
  },
  galleryPrev: {
    left: "10px",
  },
  galleryNext: {
    right: "10px",
  },
  galleryFullscreen: {
    position: "absolute",
    top: "10px",
    right: "10px",
    background: "rgba(0, 0, 0, 0.5)",
    color: "white",
    border: "none",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    opacity: 0.7,
    transition: "opacity 0.2s",
    zIndex: 10,
  },
  galleryFullscreenHover: {
    opacity: 1,
  },
  galleryThumbnails: {
    display: "flex",
    padding: "10px",
    overflowX: "auto",
    scrollbarWidth: "thin",
  },
  galleryThumbnail: {
    width: "60px",
    height: "60px",
    flexShrink: 0,
    marginRight: "8px",
    borderRadius: "4px",
    overflow: "hidden",
    opacity: 0.7,
    cursor: "pointer",
    transition: "opacity 0.2s",
    border: "2px solid transparent",
  },
  galleryThumbnailHover: {
    opacity: 0.9,
  },
  galleryThumbnailActive: {
    opacity: 1,
    borderColor: "var(--blue, #1a73e8)",
  },
  galleryThumbnailImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  galleryIndicators: {
    position: "absolute",
    bottom: "15px",
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    gap: "8px",
    zIndex: 10,
  },
  galleryIndicator: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "white",
    opacity: 0.5,
    border: "none",
    padding: 0,
    cursor: "pointer",
    transition: "opacity 0.2s, transform 0.2s",
  },
  galleryIndicatorActive: {
    opacity: 1,
    transform: "scale(1.2)",
  },
  imageGalleryFullscreen: {
    width: "100vw !important",
    height: "100vh !important",
    maxWidth: "100vw",
    maxHeight: "100vh",
    background: "black",
  },
  imageGalleryFullscreenImage: {
    maxHeight: "90vh",
  },
};

// Video Player styles
export const videoPlayerStyles = {
  videoPlayer: {
    position: "relative",
    width: "100%",
    maxWidth: "100%",
    background: "var(--background2)",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
  },
  videoContainer: {
    position: "relative",
    width: "100%",
    background: "#000",
  },
  videoElement: {
    width: "100%",
    display: "block",
  },
  videoOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.3)",
    opacity: 0,
    transition: "opacity 0.3s",
  },
  videoOverlayVisible: {
    opacity: 1,
  },
  playButton: {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    background: "rgba(0, 0, 0, 0.7)",
    border: "none",
    color: "white",
    fontSize: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "transform 0.2s, background 0.2s",
  },
  playButtonHover: {
    transform: "scale(1.1)",
    background: "rgba(0, 0, 0, 0.8)",
  },
  controls: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: "100%",
    padding: "10px",
    background: "linear-gradient(transparent, rgba(0, 0, 0, 0.7))",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    opacity: 0,
    transition: "opacity 0.3s",
  },
  controlsVisible: {
    opacity: 1,
  },
  progressContainer: {
    width: "100%",
    height: "5px",
    background: "rgba(255, 255, 255, 0.3)",
    borderRadius: "3px",
    cursor: "pointer",
    position: "relative",
  },
  progressBar: {
    height: "100%",
    background: "var(--blue, #1a73e8)",
    borderRadius: "3px",
    position: "absolute",
    top: 0,
    left: 0,
  },
  controlsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "white",
  },
  controlsGroup: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
  },
  controlButton: {
    background: "transparent",
    border: "none",
    color: "white",
    cursor: "pointer",
    width: "30px",
    height: "30px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "16px",
    opacity: 0.8,
    transition: "opacity 0.2s",
  },
  controlButtonHover: {
    opacity: 1,
  },
  timeDisplay: {
    fontSize: "14px",
    opacity: 0.9,
  },
  volumeContainer: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
  volumeSlider: {
    width: "60px",
    height: "5px",
    WebkitAppearance: "none",
    background: "rgba(255, 255, 255, 0.3)",
    borderRadius: "3px",
    outline: "none",
  },
  volumeSliderThumb: {
    WebkitAppearance: "none",
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    background: "white",
    cursor: "pointer",
  },
  fullscreenButton: {
    marginLeft: "10px",
  },
};

// Social Feed styles
export const socialFeedStyles = {
  socialFeed: {
    width: "100%",
    maxWidth: "600px",
    margin: "0 auto",
  },
  feedHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
  },
  feedTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "var(--text-color)",
  },
  feedFilter: {
    display: "flex",
    gap: "10px",
  },
  filterButton: {
    background: "var(--background2)",
    border: "none",
    padding: "8px 15px",
    borderRadius: "20px",
    fontSize: "0.9rem",
    color: "var(--text-color2)",
    cursor: "pointer",
    transition: "background-color 0.2s, color 0.2s",
  },
  filterButtonHover: {
    background: "var(--hover)",
  },
  filterButtonActive: {
    background: "var(--blue)",
    color: "white",
  },
  postList: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  postCard: {
    background: "var(--background2)",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
  },
  postHeader: {
    display: "flex",
    alignItems: "center",
    padding: "15px",
  },
  postAvatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    overflow: "hidden",
    marginRight: "12px",
  },
  postAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  postUserInfo: {
    flex: 1,
  },
  postUsername: {
    fontWeight: 600,
    color: "var(--text-color)",
    margin: 0,
  },
  postTime: {
    fontSize: "0.8rem",
    color: "var(--text-color2)",
    margin: 0,
  },
  postOptions: {
    color: "var(--text-color2)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "5px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  postOptionsHover: {
    background: "var(--hover)",
  },
  postContent: {
    padding: "0 15px 15px",
    color: "var(--text-color)",
    whiteSpace: "pre-wrap",
  },
  postMedia: {
    width: "100%",
    maxHeight: "500px",
    overflow: "hidden",
    marginBottom: "15px",
  },
  postMediaImg: {
    width: "100%",
    objectFit: "contain",
  },
  postActions: {
    display: "flex",
    padding: "10px 15px",
    borderTop: "1px solid var(--border)",
  },
  postAction: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    marginRight: "20px",
    color: "var(--text-color2)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "5px",
    borderRadius: "5px",
    fontSize: "0.9rem",
  },
  postActionHover: {
    background: "var(--hover)",
  },
  postActionLiked: {
    color: "var(--red)",
  },
  loadMore: {
    background: "var(--background2)",
    border: "none",
    padding: "10px 20px",
    borderRadius: "20px",
    color: "var(--text-color)",
    cursor: "pointer",
    margin: "20px auto",
    display: "block",
    transition: "background-color 0.2s",
  },
  loadMoreHover: {
    background: "var(--hover)",
  },
  emptyFeed: {
    textAlign: "center",
    padding: "40px 0",
    color: "var(--text-color2)",
  },
  loadingIndicator: {
    textAlign: "center",
    padding: "20px 0",
    color: "var(--text-color2)",
  },
};
