// client/ui/src/index.ts
// Shared UI components for all platforms (web, desktop, mobile)

// Elements - Atomic UI building blocks
export {
  Alert,
  Avatar,
  Badge,
  Box,
  Button,
  Checkbox,
  CloseButton,
  Divider,
  EnvironmentBadge,
  FileInput,
  Heading,
  Input,
  Kbd,
  MenuItem,
  OAuthButton,
  PasswordInput,
  Progress,
  Skeleton,
  SkipLink,
  Spinner,
  Switch,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
  Text,
  TextArea,
  Toaster,
  Tooltip,
  VersionBadge,
  VisuallyHidden,
} from './elements';

// Components - Composed multi-part components
export {
  Accordion,
  Card,
  DelayedFallback,
  Dialog,
  Dropdown,
  ErrorBoundary,
  FocusTrap,
  FormField,
  LiveRegion,
  useAnnounce,
  Image,
  // Billing
  InvoiceList,
  InvoiceRow,
  LoadingContainer,
  Pagination,
  PaymentMethodCard,
  PeekLink,
  PlanCard,
  Popover,
  PricingTable,
  Radio,
  RadioGroup,
  Select,
  Slider,
  SubscriptionStatus,
  Tabs,
  Toast,
  ToastContainer,
} from './components';
export type {
  AnnouncePoliteness,
  DelayedFallbackProps,
  ErrorBoundaryProps,
  InvoiceListProps,
  LiveRegionProps,
  UseAnnounceResult,
  InvoiceRowProps,
  PaymentMethodCardProps,
  PeekLinkProps,
  PlanCardProps,
  PricingTableProps,
  SubscriptionStatusProps,
  TabItem,
  TabsProps,
  UserAction,
  UserState,
} from './components';

// Layouts - Page and section layouts
export {
  AppShell,
  AuthLayout,
  BottombarLayout,
  Container,
  LeftSidebarLayout,
  Modal,
  Overlay,
  PageContainer,
  ProtectedRoute,
  ResizablePanel,
  ResizablePanelGroup,
  ResizableSeparator,
  RightSidebarLayout,
  ScrollArea,
  SidePeek,
  StackedLayout,
  TopbarLayout,
} from './layouts';
export type {
  AppShellProps,
  BottombarLayoutProps,
  LeftSidebarLayoutProps,
  RightSidebarLayoutProps,
  SidePeekRootProps,
  SidePeekSize,
  TopbarLayoutProps,
} from './layouts';

// Hooks
export {
  HistoryProvider,
  useAuthModeNavigation,
  useClickOutside,
  useContrast,
  useControllableState,
  useCopyToClipboard,
  useDebounce,
  useDelayedFlag,
  useDensity,
  useDisclosure,
  useFocusReturn,
  useFormState,
  useHistoryNav,
  useKeyboardShortcuts,
  useLocalStorage,
  useMediaQuery,
  useOffsetPaginatedQuery,
  useOnScreen,
  usePaginatedQuery,
  usePanelConfig,
  useResendCooldown,
  useRouteFocusAnnounce,
  useSidePeek,
  useThemeMode,
  useVirtualScroll,
  useWindowSize,
} from './hooks';
export type {
  AuthMode,
  AuthModeNavigation,
  AuthModeNavigationOptions,
  FormState,
  HistoryContextValue,
  UseFocusReturnOptions,
  UseFocusReturnResult,
  UseRouteFocusAnnounceOptions,
  UseContrastReturn,
  UseDensityReturn,
  UseOffsetPaginatedQueryOptions,
  UseOffsetPaginatedQueryResult,
  UsePaginatedQueryOptions,
  UsePaginatedQueryResult,
  UseResendCooldownReturn,
  UseSidePeekResult,
  VirtualScrollItem,
  VirtualScrollListProps,
  VirtualScrollOptions,
  VirtualScrollResult,
} from './hooks';

// Theme
export {
  ThemeProvider,
  colors,
  darkColors,
  lightColors,
  motion,
  radius,
  spacing,
  typography,
  useTheme,
} from './theme';
export type {
  ContrastMode,
  DarkColors,
  Density,
  LightColors,
  Radius,
  ThemeColors,
  ThemeContextValue,
  ThemeProviderProps,
} from './theme';

export {
  BrowserRouter,
  Link,
  MemoryRouter,
  Navigate,
  Outlet,
  OutletProvider,
  Route,
  Router,
  RouterContext,
  Routes,
  useHistory,
  useLocation,
  useNavigate,
  useNavigationType,
  useParams,
  useSearchParams,
} from './router';
export type {
  History,
  LinkProps,
  MemoryRouterProps,
  NavigateFunction,
  NavigateOptions,
  NavigateProps,
  NavigationType,
  OutletProviderProps,
  RouteProps,
  RouterContextValue,
  RouterLocation,
  RouterProps,
  RouterState,
  RoutesProps,
} from './router';

// Utilities
export { Markdown, SyntaxHighlighter, cn, createFormHandler } from './utils';
export type { FormHandlerOptions } from './utils';
