// core/src/index.ts
/**
 * @abe-stack/core
 *
 * Backend utilities, infrastructure, and domain logic for ABE Stack.
 */

// ============================================================================
// Configuration
// ============================================================================
export {
  AuthEnvSchema,
  BillingEnvSchema,
  CacheEnvSchema,
  DatabaseEnvSchema,
  EmailEnvSchema,
  EnvSchema,
  getBool,
  getInt,
  getList,
  getRequired,
  initEnv,
  loadServerEnv,
  NotificationEnvSchema,
  QueueEnvSchema,
  SearchEnvSchema,
  ServerEnvSchema,
  StorageEnvSchema,
  validateEnvironment,
} from './config';
export type {
  AppConfig,
  AuthConfig,
  AuthStrategy,
  BillingConfig,
  BillingPlansConfig,
  BillingProvider,
  BillingUrlsConfig,
  BrazeConfig,
  CacheConfig,
  CourierConfig,
  DatabaseConfig,
  DatabaseProvider,
  ElasticsearchProviderConfig,
  EmailConfig,
  FcmConfig,
  FullEnv,
  GenericNotificationConfig,
  JsonDatabaseConfig,
  JwtRotationConfig,
  KnockConfig,
  LocalStorageConfig,
  LogLevel,
  MongoConfig,
  MySqlConfig,
  NotificationConfig,
  NotificationProvider,
  OAuthProviderConfig,
  OneSignalConfig,
  PayPalProviderConfig,
  PostgresConfig,
  QueueConfig,
  QueueProvider,
  RateLimitConfig,
  S3StorageConfig,
  SearchConfig,
  ServerConfig,
  SmtpConfig,
  SnsConfig,
  SqlColumnMapping,
  SqliteConfig,
  SqlSearchProviderConfig,
  SqlTableConfig,
  StorageConfig,
  StorageConfigBase,
  StorageProviderName,
  StripeProviderConfig,
} from './config';

// ============================================================================
// Infrastructure
// ============================================================================
export { BatchedQueue, DeferredPromise, ReactiveMap } from './infrastructure/async';
export type { BatchedQueueOptions } from './infrastructure/async';
// Cache errors and types consolidated into @abe-stack/cache
// JWT exports removed from main entry - use direct import for server-only code:
// import { decode, JwtError, sign, verify } from '@abe-stack/core/infrastructure/crypto';
export type { JwtErrorCode, JwtHeader, JwtPayload, SignOptions } from './infrastructure/crypto';
export {
  AppError,
  BaseError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  InternalError,
  NotFoundError,
  TooManyRequestsError,
  UnauthorizedError,
  UnprocessableError,
  ValidationError,
  formatValidationErrors,
  getErrorStatusCode,
  getSafeErrorMessage,
  isAppError,
  isErrorResponse,
  isSuccessResponse,
  toAppError,
} from './infrastructure/errors';
export type {
  ApiErrorResponse,
  ApiResponse,
  ApiSuccessResponse,
  ValidationErrorDetail,
  ValidationErrorResponse,
  ZodIssueMinimal,
} from './infrastructure/errors';
export { parseCookies } from './infrastructure/http';
export type { RequestInfo, RouteResult, ValidationSchema } from './infrastructure/http';

// Module Registration
export type { ModuleDeps, ModuleRegistrationOptions } from './infrastructure/module-registration';
// Logger
export {
  CONSOLE_LOG_LEVELS,
  createConsoleLogger,
  createJobCorrelationId,
  createJobLogger,
  createLogger,
  createRequestContext,
  createRequestLogger,
  generateCorrelationId,
  getOrCreateCorrelationId,
  LOG_LEVELS,
  shouldLog,
} from './infrastructure/logger';
export type {
  BaseLogger,
  ConsoleLogLevel,
  ConsoleLoggerConfig,
  LogData,
  Logger as CoreLogger,
  LoggerConfig,
  LogLevel as CoreLogLevel,
  RequestContext,
} from './infrastructure/logger';
// Monitor (Health Checks)
export {
  buildDetailedHealthResponse,
  checkDatabase,
  checkEmail,
  checkPubSub,
  checkRateLimit,
  checkSchema,
  checkStorage,
  checkWebSocket,
  determineOverallStatus,
} from './infrastructure/monitor';
export type {
  DetailedHealthResponse,
  EmailHealthConfig,
  HealthCheckDatabase,
  HealthCheckPubSub,
  LiveResponse,
  OverallStatus,
  ReadyResponse,
  RoutesResponse,
  SchemaHealth,
  SchemaValidationResult,
  SchemaValidator,
  ServiceHealth,
  ServiceStatus,
  StartupSummaryOptions,
  StorageHealthConfig,
  WebSocketStats,
} from './infrastructure/monitor';
// PostgresPubSub exports removed from main entry - use direct import for server-only code:
// import { createPostgresPubSub, PostgresPubSub } from '@abe-stack/core/pubsub';
export { publishAfterWrite, SubKeys, SubscriptionManager } from './infrastructure/pubsub';
export type {
  ClientMessage,
  ListKey,
  PubSubMessage,
  RecordKey,
  ServerMessage,
  SubscriptionKey,
  SubscriptionManagerOptions,
  WebSocket,
} from './infrastructure/pubsub';
// PostgresPubSubOptions type available via: import type { PostgresPubSubOptions } from '@abe-stack/core/pubsub';
export {
  compoundFilterSchema,
  createSearchQuery,
  cursorSearchResultSchema,
  evaluateCompoundFilter,
  evaluateCondition,
  evaluateFilter,
  facetBucketSchema,
  facetConfigSchema,
  facetedSearchQuerySchema,
  facetedSearchResultSchema,
  facetResultSchema,
  filterArray,
  filterConditionSchema,
  filterOperatorSchema,
  filterPrimitiveSchema,
  filterSchema,
  filterValueSchema,
  fromSearchQuery,
  fullTextSearchConfigSchema,
  getFieldValue,
  highlightedFieldSchema,
  InvalidCursorError,
  InvalidFieldError,
  InvalidFilterError,
  InvalidOperatorError,
  InvalidPaginationError,
  InvalidQueryError,
  InvalidSortError,
  isCompoundFilter,
  isFilterCondition,
  isInvalidFilterError,
  isInvalidQueryError,
  isSearchError,
  isSearchProviderError,
  isSearchTimeoutError,
  FILTER_OPERATORS,
  LOGICAL_OPERATORS,
  logicalOperatorSchema,
  paginateArray,
  QueryTooComplexError,
  rangeValueSchema,
  SEARCH_DEFAULTS,
  SEARCH_ERROR_TYPES,
  SearchError,
  SearchProviderError,
  SearchProviderUnavailableError,
  searchQuerySchema,
  SearchQueryBuilder,
  searchResultItemSchema,
  searchResultSchema,
  SearchTimeoutError,
  sortArray,
  sortConfigSchema,
  SORT_ORDER,
  sortOrderSchema,
  UnsupportedOperatorError,
  urlSearchParamsSchema,
} from './infrastructure/search';
export type {
  CompoundFilter,
  CursorSearchResult,
  FacetBucket,
  FacetConfig,
  FacetedSearchQuery,
  FacetedSearchResult,
  FacetResult,
  FilterCondition,
  FilterOperator,
  FilterPrimitive,
  FilterValue,
  FullTextSearchConfig,
  HighlightedField,
  LogicalOperator,
  SearchCapabilities,
  SearchErrorType,
  SearchProvider,
  SearchQuery,
  SearchQueryInput,
  SearchQueryOutput,
  SearchResult,
  SearchResultItem,
  SortConfig,
  SortOrder,
  UrlSearchParamsInput,
} from './infrastructure/search';
export {
  createListInsertOperation,
  createListRemoveOperation,
  createSetOperation,
  createTransaction,
  invertOperation,
  invertTransaction,
  mergeTransactions,
  isListInsertOperation,
  isListRemoveOperation,
  isSetOperation,
} from './infrastructure/transactions';
export type {
  ListInsertOperation as TransactionListInsertOperation,
  ListRemoveOperation as TransactionListRemoveOperation,
  Operation as TransactionOperation,
  SetOperation as TransactionSetOperation,
  Transaction as TransactionType,
} from './infrastructure/transactions';

// ============================================================================
// Modules (Domain Logic)
// ============================================================================
export {
  AccountLockedError,
  calculateEntropy,
  calculateScore,
  COMMON_PASSWORDS,
  containsUserInput,
  defaultPasswordConfig,
  EmailAlreadyExistsError,
  EmailNotVerifiedError,
  EmailSendError,
  estimateCrackTime,
  estimatePasswordStrength,
  generateFeedback,
  getCharsetSize,
  getStrengthColor,
  getStrengthLabel,
  hasKeyboardPattern,
  hasRepeatedChars,
  hasSequentialChars,
  HTTP_ERROR_MESSAGES,
  InvalidCredentialsError,
  InvalidTokenError,
  isCommonPassword,
  isKnownAuthError,
  KEYBOARD_PATTERNS,
  mapErrorToHttpResponse,
  OAuthError,
  OAuthStateMismatchError,
  TokenReuseError,
  TotpInvalidError,
  TotpRequiredError,
  UserNotFoundError,
  validatePassword,
  validatePasswordBasic,
  WeakPasswordError,
} from './modules/auth';
export type {
  ErrorMapperLogger,
  ErrorMapperOptions,
  ErrorStatusCode,
  HttpErrorResponse,
  PasswordConfig,
  PasswordPenalties,
  PasswordValidationResult,
  StrengthResult,
} from './modules/auth';
export {
  // Providers (avoid duplicates)
  BillingProviderError,
  // Aliases
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError,
  CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError,
  CheckoutSessionError,
  // Customers
  CustomerNotFoundError,
  // Invoices
  InvoiceNotFoundError,
  // Payment methods
  PaymentMethodNotFoundError,
  PaymentMethodValidationError,
  PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  // Plans
  PlanNotFoundError,
  // Subscriptions (avoid duplicates with infrastructure)
  SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError,
  WebhookEventAlreadyProcessedError,
  WebhookSignatureError,
  // Type guards
  isBillingProviderError,
  isPlanError,
  isSubscriptionError,
} from './modules/billing';
export {
  batchSendResultSchema,
  DEFAULT_NOTIFICATION_PREFERENCES,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  notificationActionSchema,
  notificationChannelSchema,
  notificationPayloadSchema,
  notificationPrioritySchema,
  NotificationRateLimitError,
  NotificationSendError,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_PRIORITIES,
  NotificationsDisabledError,
  notificationTypePreferenceSchema,
  notificationTypeSchema,
  NOTIFICATION_TYPES,
  PayloadTooLargeError,
  preferencesResponseSchema,
  PreferencesNotFoundError,
  ProviderError,
  ProviderNotConfiguredError,
  PushSubscriptionExistsError,
  pushSubscriptionKeysSchema,
  pushSubscriptionSchema,
  QuietHoursActiveError,
  quietHoursSchema,
  sendNotificationRequestSchema,
  sendNotificationResponseSchema,
  sendResultSchema,
  subscribeRequestSchema,
  subscribeResponseSchema,
  SubscriptionExistsError,
  SubscriptionExpiredError,
  SubscriptionNotFoundError,
  unsubscribeRequestSchema,
  unsubscribeResponseSchema,
  updatePreferencesRequestSchema,
  VapidNotConfiguredError,
  vapidKeyResponseSchema,
} from './modules/notifications';
export type {
  BatchSendResult,
  NotificationAction,
  NotificationChannel,
  NotificationMessage,
  NotificationPayload,
  NotificationPayloadSchema,
  NotificationPreferences,
  NotificationPriority,
  NotificationType,
  NotificationTypePreference,
  PreferencesResponse,
  PushSubscription,
  PushSubscriptionKeys,
  SendNotificationRequest,
  SendNotificationRequestSchema,
  SendNotificationResponse,
  SendResult,
  StoredPushSubscription,
  SubscribeRequest,
  SubscribeRequestSchema,
  SubscribeResponse,
  UnsubscribeRequest,
  UnsubscribeRequestSchema,
  UnsubscribeResponse,
  UpdatePreferencesRequest,
  UpdatePreferencesRequestSchema,
  VapidKeyResponse,
} from './modules/notifications';

// Contract Re-exports (for convenience)
// ============================================================================
export {
  addPaymentMethodRequestSchema,
  adminBillingContract,
  adminContract,
  adminLockUserRequestSchema,
  adminLockUserResponseSchema,
  adminPlanResponseSchema,
  adminPlanSchema,
  adminPlansListResponseSchema,
  adminUpdateUserRequestSchema,
  adminUpdateUserResponseSchema,
  adminUserListFiltersSchema,
  adminUserListResponseSchema,
  adminUserSchema,
  apiContract,
  authContract,
  authResponseSchema,
  avatarDeleteResponseSchema,
  avatarUploadResponseSchema,
  billingContract,
  BILLING_PROVIDERS,
  cancelSubscriptionRequestSchema,
  changePasswordRequestSchema,
  changePasswordResponseSchema,
  checkoutRequestSchema,
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  checkoutResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  conflictResponseSchema,
  createPlanRequestSchema,
  createSchema,
  cursorPaginatedResultSchema,
  cursorPaginationOptionsSchema,
  emailSchema,
  emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  emptyBillingBodySchema,
  emptyBodySchema,
  errorResponseSchema,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema,
  getRecordsRequestSchema,
  getRecordsResponseSchema,
  invoiceSchema,
  invoicesListResponseSchema,
  INVOICE_STATUSES,
  jobActionResponseSchema,
  jobDetailsSchema,
  jobErrorSchema,
  jobIdRequestSchema,
  jobListQuerySchema,
  jobListResponseSchema,
  jobsContract,
  jobStatusSchema,
  JOB_STATUSES,
  listInsertOperationSchema,
  listPositionSchema,
  listRemoveOperationSchema,
  loginRequestSchema,
  logoutResponseSchema,
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyResponseSchema,
  magicLinkVerifySchema,
  nameSchema,
  oauthCallbackQuerySchema,
  oauthCallbackResponseSchema,
  oauthConnectionSchema,
  oauthConnectionsResponseSchema,
  oauthContract,
  oauthEnabledProvidersResponseSchema,
  oauthInitiateResponseSchema,
  oauthLinkCallbackResponseSchema,
  oauthLinkResponseSchema,
  oauthProviderSchema,
  oauthUnlinkResponseSchema,
  OAUTH_PROVIDERS,
  operationSchema,
  paginatedResultSchema,
  paginationOptionsSchema,
  passwordSchema,
  paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema,
  PAYMENT_METHOD_TYPES,
  planSchema,
  plansListResponseSchema,
  PLAN_INTERVALS,
  queueStatsSchema,
  realtimeContract,
  recordMapSchema,
  recordPointerSchema,
  recordSchema,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  requiredNameSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  revokeAllSessionsResponseSchema,
  revokeSessionResponseSchema,
  securityContract,
  securityEventDetailRequestSchema,
  securityEventDetailResponseSchema,
  securityEventSchema,
  securityEventsExportRequestSchema,
  securityEventsExportResponseSchema,
  securityEventsFilterSchema,
  securityEventsListRequestSchema,
  securityEventsListResponseSchema,
  securityMetricsRequestSchema,
  securityMetricsResponseSchema,
  securityMetricsSchema,
  SECURITY_EVENT_TYPES,
  SECURITY_SEVERITIES,
  sessionSchema,
  sessionsListResponseSchema,
  setNowOperationSchema,
  setOperationSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  setupIntentResponseSchema,
  subscriptionActionResponseSchema,
  subscriptionResponseSchema,
  subscriptionSchema,
  SUBSCRIPTION_STATUSES,
  syncStripeResponseSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpVerifyRequestSchema,
  totpVerifyResponseSchema,
  transactionSchema,
  universalPaginatedResultSchema,
  universalPaginationOptionsSchema,
  unlockAccountRequestSchema,
  unlockAccountResponseSchema,
  updatePlanRequestSchema,
  updateProfileRequestSchema,
  updateSubscriptionRequestSchema,
  userRoleSchema,
  userSchema,
  usersContract,
  userStatusSchema,
  USER_ROLES,
  USER_STATUSES,
  uuidSchema,
  writeResponseSchema,
} from '@abe-stack/contracts';
export type {
  AddPaymentMethodRequest,
  AdminLockUserRequest,
  AdminLockUserResponse,
  AdminPlan,
  AdminPlanResponse,
  AdminPlansListResponse,
  AdminUpdateUserRequest,
  AdminUpdateUserResponse,
  AdminUser,
  AdminUserListFilters,
  AdminUserListResponse,
  ApiContract,
  AuthResponse,
  AvatarDeleteResponse,
  AvatarUploadResponse,
  BillingService,
  CancelSubscriptionRequest,
  CardDetails,
  ChangePasswordRequest,
  ChangePasswordResponse,
  ChangeEmailRequest,
  ChangeEmailResponse,
  ConfirmEmailChangeRequest,
  ConfirmEmailChangeResponse,
  CheckoutParams,
  CheckoutRequest,
  CheckoutResponse,
  CheckoutResult,
  ConflictResponse,
  Contract,
  ContractRouter,
  CreatePlanRequest,
  CreateProductParams,
  CreateProductResult,
  CursorPaginatedResult,
  CursorPaginationOptions,
  EmailOptions,
  EmailResult,
  EmailService,
  EmailVerificationRequest,
  EmailVerificationResponse,
  EmptyBillingBody,
  EmptyBody,
  EndpointDef,
  ErrorResponse,
  ForgotPasswordRequest,
  ForgotPasswordResponse,
  GetRecordsRequest,
  GetRecordsResponse,
  HttpMethod,
  InferSchema,
  Invoice,
  InvoicesListResponse,
  InvoiceStatus,
  JobActionResponse,
  JobDetails,
  JobError,
  JobIdRequest,
  JobListQuery,
  JobListResponse,
  JobStatus,
  QueueStats,
  ListInsertOperation,
  ListPosition,
  ListRemoveOperation,
  Logger,
  LoginRequest,
  LogoutResponse,
  MagicLinkRequest,
  MagicLinkRequestResponse,
  MagicLinkVerifyRequest,
  MagicLinkVerifyResponse,
  NativeBridge,
  NormalizedEventType,
  NormalizedWebhookEvent,
  NotificationService,
  OAuthCallbackQuery,
  OAuthCallbackResponse,
  OAuthConnection,
  OAuthConnectionsResponse,
  OAuthEnabledProvidersResponse,
  OAuthInitiateResponse,
  OAuthLinkCallbackResponse,
  OAuthLinkResponse,
  OAuthProvider,
  OAuthUnlinkResponse,
  Operation,
  PaginatedResult,
  PaginationOptions,
  PaymentMethod,
  PaymentMethodResponse,
  PaymentMethodsListResponse,
  PaymentMethodType,
  Plan,
  PlanFeature,
  PlanInterval,
  PlansListResponse,
  ProviderInvoice,
  ProviderPaymentMethod,
  ProviderSubscription,
  QueryParams,
  RealtimeRecord,
  RealtimeTransaction,
  RecordMap,
  RecordPointer,
  RefreshResponse,
  RegisterRequest,
  RegisterResponse,
  RequestBody,
  ResendVerificationRequest,
  ResendVerificationResponse,
  ResetPasswordRequest,
  ResetPasswordResponse,
  RevokeAllSessionsResponse,
  RevokeSessionResponse,
  SafeParseResult,
  Schema,
  SecurityEvent,
  SecurityEventDetailRequest,
  SecurityEventDetailResponse,
  SecurityEventsExportRequest,
  SecurityEventsExportResponse,
  SecurityEventsFilter,
  SecurityEventsListRequest,
  SecurityEventsListResponse,
  SecurityEventType,
  SecurityMetrics,
  SecurityMetricsRequest,
  SecurityMetricsResponse,
  SecuritySeverity,
  ServerEnvironment,
  Session,
  SessionsListResponse,
  SetNowOperation,
  SetOperation,
  SetPasswordRequest,
  SetPasswordResponse,
  SetupIntentResponse,
  SetupIntentResult,
  StorageService,
  Subscription,
  SubscriptionActionResponse,
  SubscriptionResponse,
  SubscriptionStatus,
  SuccessResponse,
  SyncStripeResponse,
  TotpSetupResponse,
  TotpStatusResponse,
  TotpVerifyRequest,
  TotpVerifyResponse,
  Transaction,
  UniversalPaginatedResult,
  UniversalPaginationOptions,
  UnlockAccountRequest,
  UnlockAccountResponse,
  UpdatePlanRequest,
  UpdateProfileRequest,
  UpdateSubscriptionRequest,
  User,
  UserRole,
  UserStatus,
  WriteResponse,
} from '@abe-stack/contracts';

// Realtime Aliases (server expectations)
export type {
  ListInsertOperation as RealtimeListInsertOperation,
  ListRemoveOperation as RealtimeListRemoveOperation,
  Operation as RealtimeOperation,
  SetNowOperation as RealtimeSetNowOperation,
  SetOperation as RealtimeSetOperation,
} from '@abe-stack/contracts';

// ============================================================================
// Shared Utilities
// ============================================================================
export {
  addAuthHeader,
  createTokenStore,
  delay,
  isPortFree,
  isPortListening,
  normalizeStorageKey,
  pickAvailablePort,
  tokenStore,
  uniquePorts,
  waitForPort,
} from './shared';
export type { TokenStore } from './shared';

// Constants
export {
  DAYS_PER_WEEK,
  HOURS_PER_DAY,
  HTTP_STATUS,
  MINUTES_PER_HOUR,
  MS_PER_DAY,
  MS_PER_HOUR,
  MS_PER_MINUTE,
  MS_PER_SECOND,
  SECONDS_PER_DAY,
  SECONDS_PER_HOUR,
  SECONDS_PER_MINUTE,
} from './shared/constants';
export type { HttpStatusCode } from './shared/constants';

// Pagination
export {
  buildCursorPaginationQuery,
  calculateCursorPaginationMetadata,
  createCursorForItem,
  decodeCursor,
  encodeCursor,
  getSortableValue,
  isCursorValue,
  paginateArrayWithCursor,
  paginateLargeArrayWithCursor,
  PaginationError,
  PAGINATION_ERROR_TYPES,
} from './shared/pagination';
export type { CursorData, PaginationErrorType } from './shared/pagination';
