// main/shared/src/domain/auth/index.ts

export {
  defaultPasswordConfig,
  getStrengthColor,
  getStrengthLabel,
  validatePassword,
  validatePasswordBasic,
  type PasswordConfig,
  type PasswordValidationResult,
} from './auth.password';

export { estimatePasswordStrength, type StrengthResult } from './auth.password-strength';

export {
  calculateEntropy,
  calculateScore,
  estimateCrackTime,
  generateFeedback,
  getCharsetSize,
  type PasswordPenalties,
} from './auth.password-scoring';

export {
  COMMON_PASSWORDS,
  containsUserInput,
  hasKeyboardPattern,
  hasRepeatedChars,
  hasSequentialChars,
  isCommonPassword,
  KEYBOARD_PATTERNS,
} from './auth.password-patterns';

export { authContract } from './auth.contracts';

export { AUTH_ERROR_MESSAGES, AUTH_SUCCESS_MESSAGES } from './auth.messages';

// Only export auth-specific errors not already in core/errors.ts
export { AccountLockedError, EmailSendError } from './auth.errors';

export {
  HTTP_ERROR_MESSAGES,
  isKnownAuthError,
  mapErrorToHttpResponse,
  type ErrorMapperLogger,
  type ErrorMapperOptions,
  type ErrorStatusCode,
  type HttpErrorResponse,
} from './auth.http-mapper';

export {
  acceptTosRequestSchema,
  acceptTosResponseSchema,
  authResponseSchema,
  bffLoginResponseSchema,
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  revertEmailChangeRequestSchema,
  revertEmailChangeResponseSchema,
  emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema,
  loginRequestSchema,
  logoutResponseSchema,
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyRequestSchema,
  magicLinkVerifyResponseSchema,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  sudoRequestSchema,
  sudoResponseSchema,
  totpLoginChallengeResponseSchema,
  totpLoginVerifyRequestSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpVerifyRequestSchema,
  tosStatusResponseSchema,
  totpVerifyResponseSchema,
  setPhoneRequestSchema,
  setPhoneResponseSchema,
  verifyPhoneRequestSchema,
  verifyPhoneResponseSchema,
  removePhoneResponseSchema,
  smsChallengeRequestSchema,
  smsVerifyRequestSchema,
  deviceItemSchema,
  deviceListResponseSchema,
  trustDeviceResponseSchema,
  invalidateSessionsResponseSchema,
  passkeyListItemSchema,
  passkeyListResponseSchema,
  type AcceptTosRequest,
  type AcceptTosResponse,
  type AuthResponse,
  type BffLoginResponse,
  type ChangeEmailRequest,
  type ChangeEmailResponse,
  type ConfirmEmailChangeRequest,
  type ConfirmEmailChangeResponse,
  type RevertEmailChangeRequest,
  type RevertEmailChangeResponse,
  type EmailVerificationRequest,
  type EmailVerificationResponse,
  type ForgotPasswordRequest,
  type ForgotPasswordResponse,
  type LoginRequest,
  type LogoutResponse,
  type MagicLinkRequest,
  type MagicLinkRequestResponse,
  type MagicLinkVerifyRequest,
  type MagicLinkVerifyResponse,
  type LoginSuccessResponse,
  type RefreshResponse,
  type RegisterRequest,
  type RegisterResponse,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type SetPasswordRequest,
  type SetPasswordResponse,
  type SudoRequest,
  type SudoResponse,
  type SmsLoginChallengeResponse,
  type TotpLoginChallengeResponse,
  type TotpLoginVerifyRequest,
  type TotpSetupResponse,
  type TotpStatusResponse,
  type TotpVerifyRequest,
  type TosStatusResponse,
  type TotpVerifyResponse,
  type SetPhoneRequest,
  type SetPhoneResponse,
  type VerifyPhoneRequest,
  type VerifyPhoneResponse,
  type RemovePhoneResponse,
  type SmsChallengeRequest,
  type SmsChallengeResponse,
  type SmsVerifyRequest,
  type DeviceItem,
  type DeviceListResponse,
  type TrustDeviceResponse,
  type InvalidateSessionsResponse,
  renamePasskeyRequestSchema,
  webauthnOptionsResponseSchema,
  webauthnRegisterVerifyRequestSchema,
  webauthnRegisterVerifyResponseSchema,
  webauthnLoginOptionsRequestSchema,
  webauthnLoginVerifyRequestSchema,
  type PasskeyListItem,
  type RenamePasskeyRequest,
  type WebauthnOptionsResponse,
  type WebauthnRegisterVerifyRequest,
  type WebauthnRegisterVerifyResponse,
  type WebauthnLoginOptionsRequest,
  type WebauthnLoginVerifyRequest,
} from './auth.schemas';

export {
  oauthContract,
  OAUTH_PROVIDERS,
  oauthCallbackQuerySchema,
  oauthCallbackResponseSchema,
  oauthConnectionSchema,
  oauthConnectionsResponseSchema,
  oauthEnabledProvidersResponseSchema,
  oauthInitiateResponseSchema,
  oauthLinkCallbackResponseSchema,
  oauthLinkResponseSchema,
  oauthProviderSchema,
  oauthUnlinkResponseSchema,
  type OAuthCallbackQuery,
  type OAuthCallbackResponse,
  type OAuthConnection,
  type OAuthConnectionsResponse,
  type OAuthEnabledProvidersResponse,
  type OAuthInitiateResponse,
  type OAuthLinkCallbackResponse,
  type OAuthLinkResponse,
  type OAuthProvider,
  type OAuthUnlinkResponse,
} from './auth.oauth';
