// main/shared/src/engine/index.ts

export {
  auditEventSchema,
  auditLogFilterSchema,
  auditLogListResponseSchema,
  buildAuditEvent,
  createAuditEventSchema,
  getAuditActionTone,
  getAuditSeverityTone,
  sanitizeMetadata,
  type AuditBuilderParams,
  type AuditCategory,
  type AuditEvent,
  type AuditLogFilter,
  type AuditLogListResponse,
  type AuditSeverity,
  type CreateAuditEvent
} from './audit-log';

export {
  AccountLockedError, AUTH_ERROR_MESSAGES,
  AUTH_SUCCESS_MESSAGES, authContract,
  authResponseSchema,
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  deviceItemSchema,
  deviceListResponseSchema, EmailSendError, emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema, HTTP_ERROR_MESSAGES, invalidateSessionsResponseSchema,
  isKnownAuthError,
  loginRequestSchema,
  logoutResponseSchema,
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyRequestSchema,
  magicLinkVerifyResponseSchema,
  mapErrorToHttpResponse,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  removePhoneResponseSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  setPhoneRequestSchema,
  setPhoneResponseSchema,
  smsChallengeRequestSchema,
  smsVerifyRequestSchema,
  totpLoginChallengeResponseSchema,
  totpLoginVerifyRequestSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpVerifyRequestSchema,
  totpVerifyResponseSchema,
  trustDeviceResponseSchema,
  validatePassword,
  verifyPhoneRequestSchema,
  verifyPhoneResponseSchema,
  webauthnOptionsResponseSchema,
  webauthnRegisterVerifyResponseSchema,
  type AuthResponse,
  type ChangeEmailRequest,
  type ChangeEmailResponse,
  type ConfirmEmailChangeRequest,
  type ConfirmEmailChangeResponse,
  type DeviceItem,
  type DeviceListResponse,
  type EmailVerificationRequest,
  type EmailVerificationResponse,
  type ErrorMapperLogger,
  type ErrorMapperOptions,
  type ErrorStatusCode,
  type ForgotPasswordRequest,
  type ForgotPasswordResponse,
  type HttpErrorResponse,
  type InvalidateSessionsResponse,
  type LoginRequest,
  type LogoutResponse,
  type MagicLinkRequest,
  type MagicLinkRequestResponse,
  type MagicLinkVerifyRequest,
  type MagicLinkVerifyResponse,
  type RefreshResponse,
  type RegisterRequest,
  type RegisterResponse,
  type RemovePhoneResponse,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type SetPasswordRequest,
  type SetPasswordResponse,
  type SetPhoneRequest,
  type SetPhoneResponse,
  type SmsChallengeRequest,
  type SmsChallengeResponse,
  type SmsLoginChallengeResponse,
  type SmsVerifyRequest,
  type TotpLoginChallengeResponse,
  type TotpLoginVerifyRequest,
  type TotpSetupResponse,
  type TotpStatusResponse,
  type TotpVerifyRequest,
  type TotpVerifyResponse,
  type TrustDeviceResponse,
  type VerifyPhoneRequest,
  type VerifyPhoneResponse,
  type WebauthnOptionsResponse,
  type WebauthnRegisterVerifyResponse
} from '../core/auth';

export {
  addPaymentMethodRequestSchema,
  adminBillingStatsSchema,
  adminPlansListResponseSchema,
  assertEntitled,
  assertWithinLimit,
  billingContract, BillingProviderError,
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError, calculateProration,
  cancelSubscriptionRequestSchema, CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError, cardDetailsSchema,
  checkoutRequestSchema,
  checkoutResponseSchema, CheckoutSessionError, createPlanRequestSchema, CustomerNotFoundError, hasActiveSubscription, InvoiceNotFoundError, invoiceSchema,
  invoicesListResponseSchema,
  isBillingProviderError,
  isEntitled,
  isPlanError,
  isSubscriptionError, PaymentMethodNotFoundError, paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema, PaymentMethodValidationError, planFeatureSchema, PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  PlanNotFoundError, planSchema,
  plansListResponseSchema,
  resolveEntitlements,
  setupIntentResponseSchema,
  subscriptionActionResponseSchema, SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError, subscriptionResponseSchema,
  subscriptionSchema,
  updatePlanRequestSchema,
  updateSubscriptionRequestSchema, WebhookEventAlreadyProcessedError,
  WebhookSignatureError, type AddPaymentMethodRequest,
  type AdminBillingStats,
  type AdminPlansListResponse,
  type BillingProvider,
  type BillingService,
  type BillingStats,
  type CancelSubscriptionRequest,
  type CardDetails,
  type CheckoutParams,
  type CheckoutRequest,
  type CheckoutResponse,
  type CheckoutResult,
  type CreatePlanRequest,
  type CreateProductParams,
  type CreateProductResult,
  type EntitlementInput,
  type FeatureEntitlement,
  type FeatureKey,
  type Invoice,
  type InvoiceResponse, type InvoicesListResponse, type InvoiceStatus, type NormalizedEventType,
  type NormalizedWebhookEvent,
  type PaymentMethod,
  type PaymentMethodResponse, type PaymentMethodsListResponse, type PaymentMethodType, type Plan,
  type PlanFeature,
  type PlanId,
  type PlanInterval,
  type PlansListResponse,
  type ProviderInvoice,
  type ProviderPaymentMethod,
  type ProviderSubscription,
  type ResolvedEntitlements,
  type SetupIntentResponse,
  type SetupIntentResult,
  type Subscription,
  type SubscriptionActionResponse,
  type SubscriptionId,
  type SubscriptionResponse,
  type SubscriptionState,
  type SubscriptionStatus,
  type UpdatePlanRequest,
  type UpdateSubscriptionRequest
} from '../core/billing';

export {
  CONSENT_TYPES, consentLogSchema,
  createConsentLogSchema,
  createDataExportRequestSchema,
  createLegalDocumentSchema,
  createUserAgreementSchema, DATA_EXPORT_STATUSES,
  DATA_EXPORT_TYPES, dataExportRequestSchema, DOCUMENT_TYPES, getEffectiveConsent,
  isConsentGranted,
  legalDocumentSchema,
  needsReacceptance,
  updateConsentPreferencesRequestSchema,
  updateLegalDocumentSchema,
  userAgreementSchema,
  type ConsentLog,
  type ConsentType,
  type CreateConsentLog,
  type CreateDataExportRequest,
  type CreateLegalDocument,
  type CreateUserAgreement,
  type DataExportRequest,
  type DataExportStatus,
  type DataExportType,
  type DocumentType,
  type LegalDocument,
  type UpdateConsentPreferencesRequest,
  type UpdateLegalDocument,
  type UserAgreement
} from '../core/compliance';

export {
  createFeatureFlagRequestSchema,
  evaluateFlag,
  featureFlagSchema,
  setTenantFeatureOverrideRequestSchema,
  tenantFeatureOverrideSchema,
  updateFeatureFlagRequestSchema,
  type CreateFeatureFlagRequest,
  type FeatureFlag,
  type SetTenantFeatureOverrideRequest,
  type TenantFeatureOverride,
  type UpdateFeatureFlagRequest
} from './feature-flags';

export {
  calculateBackoff,
  canRetry,
  createJobSchema,
  getJobStatusLabel,
  getJobStatusTone,
  isTerminalStatus,
  JOB_PRIORITIES,
  JOB_PRIORITY_VALUES,
  JOB_STATUSES,
  jobSchema,
  shouldProcess,
  updateJobSchema,
  type CreateJob,
  type DomainJob,
  type JobPriority,
  type JobStatus,
  type UpdateJob
} from './jobs';

export {
  acceptInvitationSchema,
  addMemberSchema,
  canAcceptInvite,
  canAssignRole,
  canChangeRole,
  canLeave,
  canRemoveMember,
  canRevokeInvite,
  createInvitationSchema,
  getInvitationStatusTone,
  getNextOwnerCandidate,
  getRoleLevel,
  getTenantRoleTone,
  hasAtLeastRole,
  INVITATION_STATUSES,
  invitationSchema,
  isInviteExpired,
  isSoleOwner,
  membershipSchema,
  updateMembershipRoleSchema,
  type AcceptInvitation,
  type AddMember,
  type CreateInvitation,
  type Invitation,
  type InvitationStatus,
  type Membership,
  type UpdateMembershipRole
} from '../core/membership';

export {
  baseMarkAsReadRequestSchema,
  DEFAULT_NOTIFICATION_PREFERENCES,
  deleteNotificationResponseSchema,
  getNotificationLevelTone,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  markReadResponseSchema,
  NOTIFICATION_PAYLOAD_MAX_SIZE,
  NOTIFICATION_TYPES,
  notificationDeleteRequestSchema,
  notificationPreferencesSchema,
  NotificationRateLimitError,
  notificationSchema,
  notificationsContract,
  NotificationsDisabledError,
  NotificationSendError,
  notificationsListRequestSchema,
  notificationsListResponseSchema,
  PayloadTooLargeError,
  PreferencesNotFoundError,
  preferencesResponseSchema,
  ProviderError,
  ProviderNotConfiguredError,
  PushProviderNotConfiguredError,
  PushSubscriptionExistsError,
  PushSubscriptionNotFoundError,
  QuietHoursActiveError,
  sendNotificationRequestSchema,
  sendNotificationResponseSchema,
  shouldSendNotification,
  subscribeRequestSchema,
  subscribeResponseSchema,
  SubscriptionExistsError,
  SubscriptionExpiredError,
  SubscriptionNotFoundError,
  unsubscribeRequestSchema,
  unsubscribeResponseSchema,
  updatePreferencesRequestSchema,
  vapidKeyResponseSchema,
  VapidNotConfiguredError,
  type BaseMarkAsReadRequest,
  type BatchSendResult,
  type DeleteNotificationResponse,
  type MarkReadResponse,
  type Notification,
  type NotificationAction,
  type NotificationChannel,
  type NotificationDeleteRequest,
  type NotificationMessage,
  type NotificationPayload,
  type NotificationPreferences,
  type NotificationPreferencesConfig,
  type NotificationPriority,
  type NotificationsListRequest,
  type NotificationsListResponse,
  type NotificationType,
  type NotificationTypePreference,
  type PreferencesResponse,
  type PushSendResult,
  type PushSubscription,
  type PushSubscriptionKeys,
  type SendNotificationRequest,
  type SendNotificationResponse,
  type StoredPushSubscription,
  type SubscribeRequest,
  type SubscribeResponse,
  type UnsubscribeRequest,
  type UnsubscribeResponse,
  type UpdatePreferencesRequest,
  type VapidKeyResponse
} from '../core/notifications';

export {
  createUserSessionSchema,
  getSessionAge,
  isSessionActive,
  isSessionRevoked,
  updateUserSessionSchema,
  userSessionSchema,
  type CreateUserSession,
  type UpdateUserSession,
  type UserSession
} from '../core/sessions';

export {
  createTenantSchema,
  extractEmailDomain,
  isEmailDomainAllowed,
  tenantSchema,
  transferOwnershipSchema,
  updateTenantSchema,
  type CreateTenantInput,
  type Tenant,
  type TransferOwnershipInput,
  type UpdateTenantInput
} from '../core/tenant';

export {
  aggregateSnapshots,
  aggregateValues,
  isOverQuota,
  usageMetricSchema,
  usageSnapshotSchema,
  type UsageMetric,
  type UsageSnapshot
} from './usage-metering';

export {
  ACCOUNT_DELETION_GRACE_PERIOD_DAYS,
  APP_ROLES,
  appRoleSchema,
  avatarDeleteResponseSchema,
  avatarUploadRequestSchema,
  avatarUploadResponseSchema,
  calculateDeletionGracePeriodEnd,
  canDeactivate,
  canReactivate,
  canRequestDeletion,
  canUser,
  changePasswordRequestSchema,
  changePasswordResponseSchema,
  deactivateAccountRequestSchema,
  deleteAccountRequestSchema,
  getAccountStatus,
  getAllRoles,
  getRoleDisplayName,
  hasRole,
  isAccountActive,
  isAccountDeactivated,
  isAccountPendingDeletion,
  isAdmin,
  isModerator,
  isOwner,
  isRegularUser,
  isUser,
  isWithinDeletionGracePeriod,
  revokeAllSessionsResponseSchema,
  revokeSessionResponseSchema,
  sessionSchema,
  sessionsListResponseSchema,
  updateProfileRequestSchema,
  userIdSchema,
  userSchema,
  usersContract,
  type AccountLifecycleFields,
  type AccountLifecycleResponse,
  type AccountStatus,
  type AppRole,
  type AvatarDeleteResponse,
  type AvatarUploadRequest,
  type AvatarUploadResponse,
  type ChangePasswordRequest,
  type ChangePasswordResponse,
  type DeactivateAccountRequest,
  type DeleteAccountRequest,
  type RevokeAllSessionsResponse,
  type RevokeSessionResponse,
  type Session,
  type SessionsListResponse,
  type UpdateProfileRequest,
  type User,
  type UserId
} from '../core/users';

export {
  calculateRetryDelay,
  createWebhookDeliverySchema,
  createWebhookSchema,
  isDeliveryTerminal,
  matchesEventFilter,
  rotateSecretResponseSchema,
  shouldRetryDelivery,
  updateWebhookDeliverySchema,
  updateWebhookSchema,
  WEBHOOK_DELIVERY_STATUSES,
  webhookDeleteResponseSchema,
  webhookDeliveryItemSchema,
  webhookDeliverySchema,
  webhookItemSchema,
  webhookListResponseSchema,
  webhookMutationResponseSchema,
  webhookResponseSchema,
  webhookSchema,
  webhooksContract,
  webhookWithDeliveriesSchema,
  type CreateWebhook,
  type CreateWebhookDelivery,
  type RotateSecretResponse,
  type UpdateWebhook,
  type UpdateWebhookDelivery,
  type Webhook,
  type WebhookDeleteResponse,
  type WebhookDelivery,
  type WebhookDeliveryItem,
  type WebhookDeliveryStatus,
  type WebhookItem,
  type WebhookListResponse,
  type WebhookMutationResponse,
  type WebhookResponse,
  type WebhookWithDeliveries
} from './webhooks';

export {
  applyOperation,
  applyOperations,
  checkVersionConflicts,
  conflictResponseSchema,
  getOperationPointers,
  getRecordsRequestSchema,
  getRecordsResponseSchema,
  isFieldMutable,
  listInsertOperationSchema,
  listPositionSchema,
  listRemoveOperationSchema,
  operationSchema,
  PROTECTED_FIELDS,
  REALTIME_ERRORS,
  realtimeContract,
  recordMapSchema,
  recordPointerSchema,
  recordSchema,
  setNowOperationSchema,
  setOperationSchema,
  setPath,
  transactionSchema,
  writeResponseSchema,
  type ApplyOperationsResult,
  type ConflictResponse,
  type GetRecordsRequest,
  type GetRecordsResponse,
  type ListInsertOperation,
  type ListPosition,
  type ListRemoveOperation,
  type RealtimeOperation,
  type RealtimeRecord,
  type RealtimeTransaction,
  type RecordMap,
  type RecordPointer,
  type SetNowOperation,
  type SetOperation,
  type VersionConflict,
  type WriteResponse
} from './realtime';

// Media
export {
  ALL_MEDIA_EXTENSIONS,
  ALLOWED_MEDIA_MIME_TYPES,
  AUDIO_EXTENSIONS,
  detectFileType,
  detectFileTypeFromPath,
  EXT_TO_MIME,
  generateFileId,
  IMAGE_EXTENSIONS,
  isAllowedFileType,
  MAX_CHUNK_SIZE,
  MAX_FILENAME_LENGTH,
  MAX_UPLOAD_FILE_SIZE,
  MAX_UPLOAD_TIMEOUT_MS,
  MIME_TO_EXT,
  parseAudioMetadataFromBuffer,
  sanitizeFilename,
  validateUploadConfig,
  VIDEO_EXTENSIONS,
  type AudioMetadata,
  type AudioProcessingOptions,
  type ContentModerationResult,
  type FileTypeResult,
  type ImageProcessingOptions,
  type MediaMetadata,
  type MediaProcessingOptions,
  type ProcessingResult,
  type SecurityScanResult,
  type UploadConfig,
  type VideoProcessingOptions
} from './media';

export {
  activitySchema,
  ACTOR_TYPES,
  actorTypeSchema,
  createActivitySchema,
  getActorTypeTone,
  type Activity,
  type ActorType,
  type CreateActivity
} from '../core/activities';

export {
  apiKeyItemSchema,
  apiKeySchema,
  apiKeysContract,
  createApiKeyRequestSchema,
  createApiKeyResponseSchema,
  createApiKeySchema,
  deleteApiKeyResponseSchema,
  listApiKeysResponseSchema,
  revokeApiKeyResponseSchema,
  updateApiKeySchema,
  type ApiKey,
  type ApiKeyItem,
  type CreateApiKey,
  type CreateApiKeyRequest,
  type CreateApiKeyResponse,
  type DeleteApiKeyResponse,
  type ListApiKeysResponse,
  type RevokeApiKeyResponse,
  type UpdateApiKey
} from './api-keys';

export {
  createEmailLogEntrySchema,
  createEmailTemplateSchema,
  EMAIL_PROVIDERS,
  EMAIL_STATUSES,
  emailLogEntrySchema,
  emailProviderSchema,
  emailStatusSchema,
  emailTemplateSchema,
  updateEmailTemplateSchema,
  type CreateEmailLogEntry,
  type CreateEmailTemplate,
  type EmailLogEntry,
  type EmailProvider,
  type EmailStatus,
  type EmailTemplate,
  type UpdateEmailTemplate
} from './email';

export {
  createFileRecordSchema,
  FILE_PURPOSES,
  filePurposeSchema,
  fileRecordSchema,
  fileUploadRequestSchema,
  STORAGE_PROVIDERS,
  storageProviderSchema,
  updateFileRecordSchema,
  type CreateFileRecord,
  type FilePurpose,
  type FileRecord,
  type FileUploadRequest,
  type StorageProvider,
  type UpdateFileRecord
} from './files';

export {
  createTenantSettingSchema,
  tenantSettingSchema,
  updateTenantSettingSchema,
  type CreateTenantSetting,
  type TenantSetting,
  type UpdateTenantSetting
} from '../core/tenant-settings';

export {
  DEFAULT_CONTRAST_MODE,
  DEFAULT_DENSITY,
  densityMultipliers,
  getContrastCssVariables,
  getDensityCssVariables,
  getSpacingForDensity,
  highContrastDarkOverrides,
  highContrastLightOverrides,
  type ContrastMode,
  type Density
} from './theme';

