name: Setup Node and pnpm
description: Setup pnpm, setup Node with pnpm cache, and install dependencies.

inputs:
  node-version:
    description: Node.js version.
    required: false
    default: '20'
  pnpm-version:
    description: pnpm version.
    required: false
    default: '10.26.2'
  install:
    description: Whether to run pnpm install.
    required: false
    default: 'true'
  frozen-lockfile:
    description: Whether to pass --frozen-lockfile to pnpm install.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      env:
        FROZEN_LOCKFILE: ${{ inputs.frozen-lockfile }}
      run: |
        if [ "$FROZEN_LOCKFILE" = "true" ]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi
