// main/shared/src/index.ts

export type * from './core/api';

// ============================================================================
// CORE EXPORTS (Errors, constants, guards, result, policy, etc.)
// ============================================================================

export {
  type ApiResponse,
  type ApiResult,
  type Contract,
  type EndpointContract,
  type ErrorResponse,
  type InferResponseData,
  type StatusCode,
} from './core/api';

export {
  ACCESS_TOKEN_COOKIE_NAME,
  API_PREFIX,
  AUTH_EXPIRY,
  CSRF_COOKIE_NAME,
  CSRF_TOKEN_HEADER,
  DEFAULT_PAGINATION,
  ERROR_CODES,
  ERROR_MESSAGES,
  HTTP_BODY_LIMIT,
  HTTP_STATUS,
  LIMITS,
  LOGIN_FAILURE_REASON,
  QUOTAS,
  REFRESH_TOKEN_COOKIE_NAME,
  RETENTION_PERIODS,
  SMS_LIMITS,
  SUDO_TOKEN_HEADER,
  WEBSOCKET_PATH,
  WS_CLOSE_POLICY_VIOLATION,
  type ErrorCode,
  type HttpStatusCode,
  type LoginFailureReason,
} from './core/constants';

export {
  AppError,
  BadRequestError,
  BaseError,
  ConfigurationError,
  ConflictError,
  EmailAlreadyExistsError,
  EmailNotVerifiedError,
  ForbiddenError,
  InternalError,
  InternalServerError,
  InvalidCredentialsError,
  InvalidTokenError,
  NotFoundError,
  OAuthError,
  OAuthStateMismatchError,
  ResourceNotFoundError,
  TokenReuseError,
  TooManyRequestsError,
  TotpInvalidError,
  TotpRequiredError,
  UnauthorizedError,
  UnprocessableError,
  UserNotFoundError,
  ValidationError,
  WeakPasswordError,
  formatValidationErrors,
  getErrorStatusCode,
  getSafeErrorMessage,
  isAppError,
  toAppError,
  type AppErrorInfo,
  type ValidationErrorDetail,
  type ValidationErrorResponse,
  type ValidationIssue,
} from './core/errors';

export {
  isErrorResponse,
  isSuccessResponse,
  type ApiErrorResponse,
  type ApiSuccessResponse,
} from './core/response';

export {
  assert,
  assertDefined,
  assertNever,
  isAuthenticatedRequest,
  isNonEmptyString,
  isNumber,
  isObjectLike,
  isPlainObject,
  isSafeObjectKey,
  isString,
} from './core/guard';

export { err, isErr, isOk, ok, type Result } from './core/result';

export {
  can,
  hasPermission,
  type AuthContext,
  type PolicyAction,
  type PolicyResource,
} from './core/policy';

export { baseEnvSchema, getRawEnv, validateEnv, type BaseEnv } from './core/env';

export {
  type Attachment,
  type BaseStorageConfig,
  type CacheService,
  type ConfigService,
  type EmailOptions,
  type EmailService,
  type HealthCheckResult,
  type InfrastructureService,
  type Job,
  type JobHandler,
  type JobOptions,
  type JobQueueService,
  type LocalStorageConfig,
  type MetricsService,
  type NotificationService,
  type ReadableStreamLike,
  type S3StorageConfig,
  type SendResult,
  type StorageClient,
  type StorageConfig,
  type StorageProvider,
} from './core/ports';

export {
  type BreadcrumbData,
  type ErrorTracker,
  type HasErrorTracker,
} from './core/observability';

export {
  apiResultSchema,
  emailSchema,
  emptyBodySchema,
  errorCodeSchema,
  errorResponseSchema,
  isoDateTimeSchema,
  passwordSchema,
  successResponseSchema,
  type EmptyBody,
} from './core/schemas';

export type { ModuleDeps, ModuleRegistrationOptions } from './core/module-registration';

export {
  createListInsertOperation,
  createListRemoveOperation,
  createSetOperation,
  createTransaction,
  invertOperation,
  invertTransaction,
  isListInsertOperation,
  isListRemoveOperation,
  isSetOperation,
  mergeTransactions,
  type ListInsertOperation,
  type ListRemoveOperation,
  type Operation,
  type SetOperation,
  type Transaction,
} from './core/transactions';

// ============================================================================
// API ROUTER EXPORTS
// ============================================================================

export { apiRouter, type ApiDomain, type ApiRouter } from './api';

// ============================================================================
// DOMAIN EXPORTS
// ============================================================================

// Audit log
export {
  getAuditActionTone,
  getAuditSeverityTone,
  AUDIT_ACTION_REGEX,
  AUDIT_CATEGORIES,
  AUDIT_SEVERITIES,
  auditEventSchema,
  auditLogFilterSchema,
  auditLogListResponseSchema,
  buildAuditEvent,
  createAuditEventSchema,
  sanitizeMetadata,
  type AuditBuilderParams,
  type AuditCategory,
  type AuditEvent,
  type AuditLogFilter,
  type AuditLogListResponse,
  type AuditSeverity,
  type CreateAuditEvent,
} from './domain/audit-log';

// Auth
export {
  AUTH_ERROR_MESSAGES,
  AUTH_SUCCESS_MESSAGES,
  AccountLockedError,
  COMMON_PASSWORDS,
  EmailSendError,
  HTTP_ERROR_MESSAGES,
  KEYBOARD_PATTERNS,
  authContract,
  authResponseSchema,
  bffLoginResponseSchema,
  calculateEntropy,
  calculateScore,
  containsUserInput,
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  acceptTosRequestSchema,
  acceptTosResponseSchema,
  revertEmailChangeRequestSchema,
  revertEmailChangeResponseSchema,
  defaultPasswordConfig,
  emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  estimateCrackTime,
  estimatePasswordStrength,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema,
  generateFeedback,
  getCharsetSize,
  getStrengthColor,
  getStrengthLabel,
  hasKeyboardPattern,
  hasRepeatedChars,
  hasSequentialChars,
  isCommonPassword,
  isKnownAuthError,
  loginRequestSchema,
  logoutResponseSchema,
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyRequestSchema,
  magicLinkVerifyResponseSchema,
  mapErrorToHttpResponse,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  sudoRequestSchema,
  sudoResponseSchema,
  totpLoginChallengeResponseSchema,
  totpLoginVerifyRequestSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpVerifyRequestSchema,
  tosStatusResponseSchema,
  totpVerifyResponseSchema,
  deviceItemSchema,
  deviceListResponseSchema,
  trustDeviceResponseSchema,
  invalidateSessionsResponseSchema,
  webauthnOptionsResponseSchema,
  webauthnRegisterVerifyResponseSchema,
  setPhoneRequestSchema,
  setPhoneResponseSchema,
  verifyPhoneRequestSchema,
  verifyPhoneResponseSchema,
  removePhoneResponseSchema,
  smsChallengeRequestSchema,
  smsVerifyRequestSchema,
  webauthnRegisterVerifyRequestSchema,
  webauthnLoginOptionsRequestSchema,
  webauthnLoginVerifyRequestSchema,
  validatePassword,
  validatePasswordBasic,
  type AcceptTosRequest,
  type AcceptTosResponse,
  type AuthResponse,
  type BffLoginResponse,
  type ChangeEmailRequest,
  type ChangeEmailResponse,
  type ConfirmEmailChangeRequest,
  type ConfirmEmailChangeResponse,
  type RevertEmailChangeRequest,
  type RevertEmailChangeResponse,
  type EmailVerificationRequest,
  type EmailVerificationResponse,
  type ErrorMapperLogger,
  type ErrorMapperOptions,
  type ErrorStatusCode,
  type ForgotPasswordRequest,
  type ForgotPasswordResponse,
  type HttpErrorResponse,
  type LoginRequest,
  type LoginSuccessResponse,
  type LogoutResponse,
  type MagicLinkRequest,
  type MagicLinkRequestResponse,
  type MagicLinkVerifyRequest,
  type MagicLinkVerifyResponse,
  type PasswordConfig,
  type PasswordPenalties,
  type PasswordValidationResult,
  type RefreshResponse,
  type RegisterRequest,
  type RegisterResponse,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type SetPasswordRequest,
  type SetPasswordResponse,
  type StrengthResult,
  type SudoRequest,
  type SudoResponse,
  type SmsLoginChallengeResponse,
  type TotpLoginChallengeResponse,
  type TotpLoginVerifyRequest,
  type TotpSetupResponse,
  type TotpStatusResponse,
  type TotpVerifyRequest,
  type TosStatusResponse,
  type TotpVerifyResponse,
  type DeviceItem,
  type DeviceListResponse,
  type TrustDeviceResponse,
  type InvalidateSessionsResponse,
  type WebauthnOptionsResponse,
  type WebauthnRegisterVerifyResponse,
  type SetPhoneRequest,
  type SetPhoneResponse,
  type VerifyPhoneRequest,
  type VerifyPhoneResponse,
  type RemovePhoneResponse,
  type SmsChallengeRequest,
  type SmsChallengeResponse,
  type PasskeyListItem,
  type RenamePasskeyRequest,
  type WebauthnRegisterVerifyRequest,
  type WebauthnLoginOptionsRequest,
  type WebauthnLoginVerifyRequest,
  renamePasskeyRequestSchema,
  type SmsVerifyRequest,
} from './domain/auth';

// Billing
export {
  BILLING_EVENT_TYPES,
  BILLING_PROVIDERS,
  BillingProviderError,
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError,
  CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError,
  CheckoutSessionError,
  CustomerNotFoundError,
  FEATURE_KEYS,
  INVOICE_STATUSES,
  InvoiceNotFoundError,
  PAYMENT_METHOD_TYPES,
  PLAN_FEES,
  PLAN_INTERVALS,
  PaymentMethodNotFoundError,
  PaymentMethodValidationError,
  PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  PlanNotFoundError,
  SUBSCRIPTION_STATUSES,
  SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError,
  WebhookEventAlreadyProcessedError,
  WebhookSignatureError,
  addPaymentMethodRequestSchema,
  adminBillingStatsSchema,
  adminPlanResponseSchema,
  adminPlanSchema,
  adminPlansListResponseSchema,
  billingContract,
  calculateProration,
  cancelSubscriptionRequestSchema,
  formatPlanInterval,
  formatPrice,
  formatPriceWithInterval,
  getCardBrandLabel,
  getInvoiceStatusLabel,
  getInvoiceStatusVariant,
  getPaymentMethodIcon,
  getPaymentMethodLabel,
  getSubscriptionStatusLabel,
  getSubscriptionStatusVariant,
  cardDetailsSchema,
  checkoutRequestSchema,
  checkoutResponseSchema,
  createPlanRequestSchema,
  invoiceSchema,
  invoicesListResponseSchema,
  isBillingProviderError,
  isPlanError,
  isSubscriptionError,
  paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema,
  planFeatureSchema,
  planSchema,
  plansListResponseSchema,
  setupIntentResponseSchema,
  subscriptionActionResponseSchema,
  subscriptionResponseSchema,
  subscriptionSchema,
  syncStripeResponseSchema,
  updatePlanRequestSchema,
  updateSubscriptionRequestSchema,
  type AddPaymentMethodRequest,
  type AdminBillingStats,
  type AdminPlan,
  type AdminPlanResponse,
  type AdminPlansListResponse,
  type BillingProvider,
  type BillingEventType,
  type BillingStats,
  type CancelSubscriptionRequest,
  type CardDetails,
  type CheckoutRequest,
  type CheckoutResponse,
  type CreatePlanRequest,
  type FeatureKey,
  type Invoice,
  type InvoiceResponse,
  type InvoiceStatus,
  type InvoicesListResponse,
  type PaymentMethod,
  type PaymentMethodResponse,
  type PaymentMethodType,
  type PaymentMethodsListResponse,
  type Plan,
  type PlanFeature,
  type PlanInterval,
  type PlanId,
  type PlansListResponse,
  type SetupIntentResponse,
  type Subscription,
  type StatusVariant,
  type SubscriptionActionResponse,
  type SubscriptionId,
  type SubscriptionResponse,
  type SubscriptionStatus,
  type SyncStripeResponse,
  type UpdatePlanRequest,
  type UpdateSubscriptionRequest,
} from './domain/billing';

// Compliance
export {
  CONSENT_TYPES,
  DATA_EXPORT_STATUSES,
  DATA_EXPORT_TYPES,
  DOCUMENT_TYPES,
  consentLogSchema,
  createConsentLogSchema,
  createDataExportRequestSchema,
  createLegalDocumentSchema,
  createUserAgreementSchema,
  dataExportRequestSchema,
  getEffectiveConsent,
  isConsentGranted,
  legalDocumentSchema,
  needsReacceptance,
  updateConsentPreferencesRequestSchema,
  updateLegalDocumentSchema,
  userAgreementSchema,
  type ConsentLog,
  type ConsentType,
  type CreateConsentLog,
  type CreateDataExportRequest,
  type CreateLegalDocument,
  type CreateUserAgreement,
  type DataExportRequest,
  type DataExportStatus,
  type DataExportType,
  type DocumentType,
  type LegalDocument,
  type UpdateConsentPreferencesRequest,
  type UpdateLegalDocument,
  type UserAgreement,
} from './domain/compliance';

// Email
export {
  EMAIL_PROVIDERS,
  EMAIL_STATUSES,
  type EmailProvider,
  type EmailStatus,
} from './domain/email';

// Files
export {
  FILE_PURPOSES,
  STORAGE_PROVIDERS,
  fileUploadRequestSchema,
  type FilePurpose,
  type FileUploadRequest,
} from './domain/files';

// Feature flags
export {
  evaluateFlag,
  createFeatureFlagRequestSchema,
  featureFlagSchema,
  setTenantFeatureOverrideRequestSchema,
  tenantFeatureOverrideSchema,
  updateFeatureFlagRequestSchema,
  type CreateFeatureFlagRequest,
  type FeatureFlag,
  type SetTenantFeatureOverrideRequest,
  type TenantFeatureOverride,
  type UpdateFeatureFlagRequest,
} from './domain/feature-flags';

// Jobs
export {
  getJobStatusLabel,
  getJobStatusTone,
  JOB_PRIORITIES,
  JOB_PRIORITY_VALUES,
  JOB_STATUSES,
  calculateBackoff,
  canRetry,
  createJobSchema,
  isTerminalStatus,
  jobSchema,
  shouldProcess,
  updateJobSchema,
  type CreateJob,
  type DomainJob,
  type JobPriority,
  type JobStatus,
  type UpdateJob,
} from './domain/jobs';

// Membership
export {
  getInvitationStatusTone,
  getTenantRoleTone,
  INVITATION_STATUSES,
  ROLE_LEVELS,
  acceptInvitationSchema,
  addMemberSchema,
  canAcceptInvite,
  canAssignRole,
  canChangeRole,
  canLeave,
  canRemoveMember,
  canRevokeInvite,
  createInvitationSchema,
  getNextOwnerCandidate,
  getRoleLevel,
  hasAtLeastRole,
  invitationSchema,
  isInviteExpired,
  isSoleOwner,
  membershipSchema,
  updateMembershipRoleSchema,
  type AcceptInvitation,
  type AddMember,
  type CreateInvitation,
  type Invitation,
  type InvitationStatus,
  type Membership,
  type UpdateMembershipRole,
} from './domain/membership';

// Notifications
export {
  notificationsContract,
  getNotificationLevelTone,
  DEFAULT_NOTIFICATION_PREFERENCES,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  NOTIFICATION_LEVELS,
  NOTIFICATION_PAYLOAD_MAX_SIZE,
  NOTIFICATION_TYPES,
  NotificationRateLimitError,
  NotificationSendError,
  NotificationsDisabledError,
  PayloadTooLargeError,
  PreferencesNotFoundError,
  ProviderError,
  ProviderNotConfiguredError,
  PushProviderNotConfiguredError,
  PushSubscriptionExistsError,
  PushSubscriptionNotFoundError,
  QuietHoursActiveError,
  SubscriptionExistsError,
  SubscriptionExpiredError,
  SubscriptionNotFoundError,
  VapidNotConfiguredError,
  baseMarkAsReadRequestSchema,
  deleteNotificationResponseSchema,
  markReadResponseSchema,
  notificationDeleteRequestSchema,
  notificationPreferencesSchema,
  notificationSchema,
  notificationsListRequestSchema,
  notificationsListResponseSchema,
  sendNotificationRequestSchema,
  sendNotificationResponseSchema,
  preferencesResponseSchema,
  shouldSendNotification,
  subscribeRequestSchema,
  subscribeResponseSchema,
  unsubscribeRequestSchema,
  unsubscribeResponseSchema,
  updatePreferencesRequestSchema,
  vapidKeyResponseSchema,
  type BaseMarkAsReadRequest,
  type DeleteNotificationResponse,
  type MarkReadResponse,
  type NotificationDeleteRequest,
  type BatchSendResult,
  type Notification,
  type NotificationAction,
  type NotificationLevel,
  type NotificationChannel,
  type NotificationMessage,
  type NotificationPayload,
  type NotificationPreferences,
  type NotificationPreferencesConfig,
  type NotificationPriority,
  type NotificationType,
  type NotificationTypePreference,
  type NotificationsListRequest,
  type NotificationsListResponse,
  type PreferencesResponse,
  type PushSendResult,
  type PushSubscription,
  type PushSubscriptionKeys,
  type SendNotificationRequest,
  type SendNotificationResponse,
  type StoredPushSubscription,
  type SubscribeRequest,
  type SubscribeResponse,
  type UnsubscribeRequest,
  type UnsubscribeResponse,
  type UpdatePreferencesRequest,
  type VapidKeyResponse,
} from './domain/notifications';

// Sessions
export {
  createUserSessionSchema,
  getSessionAge,
  isSessionActive,
  isSessionRevoked,
  updateUserSessionSchema,
  userSessionSchema,
  type CreateUserSession,
  type UpdateUserSession,
  type UserSession,
} from './domain/sessions';

// Tenant
export {
  assertWorkspaceScope,
  createTenantSchema,
  createWorkspaceContext,
  extractEmailDomain,
  getWorkspaceContext,
  hasRequiredWorkspaceRole,
  isEmailDomainAllowed,
  isWorkspaceScoped,
  tenantSchema,
  transferOwnershipSchema,
  updateTenantSchema,
  WORKSPACE_ID_HEADER,
  WORKSPACE_ROLE_HEADER,
  type CreateTenantInput,
  type MaybeWorkspaceContext,
  type Tenant,
  type TransferOwnershipInput,
  type UpdateTenantInput,
  type WorkspaceContext,
} from './domain/tenant';

// Usage metering
export {
  aggregateSnapshots,
  aggregateValues,
  isOverQuota,
  usageMetricSchema,
  usageSnapshotSchema,
  type AggregationType,
  type UsageMetric,
  type UsageSnapshot,
} from './domain/usage-metering';

// Users
export {
  APP_ROLES,
  appRoleSchema,
  avatarDeleteResponseSchema,
  avatarUploadRequestSchema,
  avatarUploadResponseSchema,
  canUser,
  changePasswordRequestSchema,
  changePasswordResponseSchema,
  getAllRoles,
  getNextUsernameChangeDate,
  getRoleDisplayName,
  hasRole,
  isAdmin,
  isModerator,
  isOwner,
  isRegularUser,
  isUser,
  isUsernameChangeCooldownActive,
  profileCompletenessResponseSchema,
  RESERVED_USERNAMES,
  revokeAllSessionsResponseSchema,
  revokeSessionResponseSchema,
  sessionSchema,
  sessionsListResponseSchema,
  updateProfileRequestSchema,
  updateUsernameRequestSchema,
  USERNAME_CHANGE_COOLDOWN_DAYS,
  userIdSchema,
  userSchema,
  usersContract,
  ACCOUNT_DELETION_GRACE_PERIOD_DAYS,
  calculateDeletionGracePeriodEnd,
  canDeactivate,
  canReactivate,
  canRequestDeletion,
  deactivateAccountRequestSchema,
  deleteAccountRequestSchema,
  getAccountStatus,
  isAccountActive,
  isAccountDeactivated,
  isAccountPendingDeletion,
  isWithinDeletionGracePeriod,
  type AccountLifecycleFields,
  type AccountLifecycleResponse,
  type AccountStatus,
  type DeactivateAccountRequest,
  type DeleteAccountRequest,
  type AppRole,
  type AvatarDeleteResponse,
  type AvatarUploadRequest,
  type AvatarUploadResponse,
  type ChangePasswordRequest,
  type ChangePasswordResponse,
  type ProfileCompletenessResponse,
  type RevokeAllSessionsResponse,
  type RevokeSessionResponse,
  type Session,
  type SessionsListResponse,
  type UpdateProfileRequest,
  type UpdateUsernameRequest,
  type UpdateUsernameResponse,
  type User,
  type UserId,
} from './domain/users';

// Webhooks
export {
  apiKeysContract,
  apiKeyItemSchema,
  apiKeySchema,
  createApiKeyRequestSchema,
  createApiKeyResponseSchema,
  createApiKeySchema,
  deleteApiKeyResponseSchema,
  listApiKeysResponseSchema,
  revokeApiKeyResponseSchema,
  updateApiKeySchema,
  type ApiKey,
  type ApiKeyItem,
  type CreateApiKey,
  type CreateApiKeyRequest,
  type CreateApiKeyResponse,
  type DeleteApiKeyResponse,
  type ListApiKeysResponse,
  type RevokeApiKeyResponse,
  type UpdateApiKey,
} from './domain/api-keys';

// Webhooks
export {
  webhooksContract,
  MAX_DELIVERY_ATTEMPTS,
  RETRY_DELAYS_MINUTES,
  SUBSCRIBABLE_EVENT_TYPES,
  WEBHOOK_DELIVERY_STATUSES,
  WEBHOOK_EVENT_TYPES,
  calculateRetryDelay,
  createWebhookDeliverySchema,
  createWebhookSchema,
  isDeliveryTerminal,
  matchesEventFilter,
  shouldRetryDelivery,
  rotateSecretResponseSchema,
  updateWebhookDeliverySchema,
  updateWebhookSchema,
  webhookDeleteResponseSchema,
  webhookDeliveryItemSchema,
  webhookDeliverySchema,
  webhookItemSchema,
  webhookListResponseSchema,
  webhookMutationResponseSchema,
  webhookResponseSchema,
  webhookSchema,
  webhookWithDeliveriesSchema,
  type CreateWebhook,
  type CreateWebhookDelivery,
  type RotateSecretResponse,
  type UpdateWebhook,
  type UpdateWebhookDelivery,
  type Webhook,
  type WebhookDeleteResponse,
  type WebhookDeliveryItem,
  type WebhookDelivery,
  type WebhookDeliveryStatus,
  type WebhookEventType,
  type WebhookItem,
  type WebhookListResponse,
  type WebhookMutationResponse,
  type WebhookResponse,
  type WebhookWithDeliveries,
} from './domain/webhooks';

// ============================================================================
// ADDITIONAL DOMAIN EXPORTS (formerly in contracts/)
// ============================================================================

// Admin (additional exports)
export {
  formatSecurityEventType,
  getAppRoleLabel,
  getAppRoleTone,
  getSecuritySeverityTone,
  getUserStatusLabel,
  getUserStatusTone,
  USER_STATUSES,
  adminActionResponseSchema,
  adminHardBanRequestSchema,
  adminHardBanResponseSchema,
  adminLockUserRequestSchema,
  adminLockUserResponseSchema,
  adminSuspendTenantRequestSchema,
  adminUpdateUserRequestSchema,
  adminUpdateUserResponseSchema,
  adminUserListFiltersSchema,
  adminUserListResponseSchema,
  adminUserSchema,
  unlockAccountRequestSchema,
  unlockAccountResponseSchema,
  userStatusSchema,
  type AdminActionResponse,
  type AdminHardBanRequest,
  type AdminHardBanResponse,
  type AdminLockUserRequest,
  type AdminLockUserResponse,
  type AdminSuspendTenantRequest,
  type AdminUpdateUserRequest,
  type AdminUpdateUserResponse,
  type AdminUser,
  type AdminUserListFilters,
  type AdminUserListResponse,
  type UnlockAccountRequest,
  type UnlockAccountResponse,
  type UserStatus,
} from './domain/admin';

// Context (from core)
export {
  type AuthenticatedUser,
  type BaseContext,
  type RequestContext as ContractRequestContext,
  type RequestInfo as ContractRequestInfo,
  type HasBilling,
  type HasCache,
  type HasEmail,
  type HasNotifications,
  type HasPubSub,
  type HasStorage,
  type ReplyContext,
} from './core/context';

// Jobs (additional contract exports)
export {
  jobActionResponseSchema,
  jobDetailsSchema,
  jobListQuerySchema,
  jobListResponseSchema,
  queueStatsSchema,
  type JobActionResponse,
  type JobDetails,
  type JobError,
  type JobListQuery,
  type JobListResponse,
  type QueueStats,
} from './domain/jobs';

// Billing Service types (from domain)
export {
  type BillingService,
  type CheckoutParams,
  type CheckoutResult,
  type CreateProductParams,
  type CreateProductResult,
  type NormalizedEventType,
  type NormalizedWebhookEvent,
  type ProviderInvoice,
  type ProviderPaymentMethod,
  type ProviderSubscription,
  type SetupIntentResult,
} from './domain/billing';

// OAuth (from domain/auth)
export {
  OAUTH_PROVIDERS,
  oauthCallbackQuerySchema,
  oauthCallbackResponseSchema,
  oauthConnectionSchema,
  oauthConnectionsResponseSchema,
  oauthContract,
  oauthEnabledProvidersResponseSchema,
  oauthInitiateResponseSchema,
  oauthLinkCallbackResponseSchema,
  oauthLinkResponseSchema,
  oauthProviderSchema,
  oauthUnlinkResponseSchema,
  type OAuthCallbackQuery,
  type OAuthCallbackResponse,
  type OAuthConnection,
  type OAuthConnectionsResponse,
  type OAuthEnabledProvidersResponse,
  type OAuthInitiateResponse,
  type OAuthLinkCallbackResponse,
  type OAuthLinkResponse,
  type OAuthProvider,
  type OAuthUnlinkResponse,
} from './domain/auth';

// Native bridge (from core)
export { type NativeBridge } from './core/native';

// Users contract (legacy aliases)
export { USER_ROLES, userRoleSchema, type UserRole } from './domain/users';

// Realtime (from domain)
export {
  conflictResponseSchema,
  getRecordsRequestSchema,
  getRecordsResponseSchema,
  listInsertOperationSchema,
  listPositionSchema,
  listRemoveOperationSchema,
  operationSchema,
  realtimeContract,
  recordMapSchema,
  recordPointerSchema,
  recordSchema,
  setNowOperationSchema,
  setOperationSchema,
  transactionSchema,
  writeResponseSchema,
  type ConflictResponse,
  type GetRecordsRequest,
  type GetRecordsResponse,
  type ListInsertOperation as RealtimeListInsertOperation,
  type ListPosition,
  type ListRemoveOperation as RealtimeListRemoveOperation,
  type RealtimeOperation,
  type RealtimeRecord,
  type RealtimeTransaction,
  type RecordMap,
  type RecordPointer,
  type VersionedRecord,
  type SetNowOperation,
  type SetOperation as RealtimeSetOperation,
  type WriteResponse,
  PROTECTED_FIELDS,
  REALTIME_ERRORS,
  applyOperation,
  applyOperations,
  checkVersionConflicts,
  getOperationPointers,
  isFieldMutable,
  setPath,
  type ApplyOperationsResult,
  type VersionConflict,
} from './domain/realtime';

// Media (from domain/media)
export {
  ALL_MEDIA_EXTENSIONS,
  ALLOWED_MEDIA_MIME_TYPES,
  AUDIO_EXTENSIONS,
  EXT_TO_MIME,
  IMAGE_EXTENSIONS,
  MAX_CHUNK_SIZE,
  MAX_FILENAME_LENGTH,
  MAX_UPLOAD_FILE_SIZE,
  MAX_UPLOAD_TIMEOUT_MS,
  MIME_TO_EXT,
  VIDEO_EXTENSIONS,
  detectFileType,
  detectFileTypeFromPath,
  generateFileId,
  isAllowedFileType,
  parseAudioMetadataFromBuffer,
  sanitizeFilename,
  validateUploadConfig,
  type AudioMetadata,
  type AudioProcessingOptions,
  type ContentModerationResult,
  type FileTypeResult,
  type ImageProcessingOptions,
  type MediaMetadata,
  type MediaProcessingOptions,
  type ProcessingResult,
  type SecurityScanResult,
  type UploadConfig,
  type VideoProcessingOptions,
} from './domain/media';

// Activities (from domain/activities)
export {
  ACTOR_TYPES,
  activitySchema,
  actorTypeSchema,
  createActivitySchema,
  getActorTypeTone,
  type Activity,
  type ActorType,
  type CreateActivity,
} from './domain/activities';

// Security (from domain/admin)
export {
  SECURITY_EVENT_TYPES,
  SECURITY_SEVERITIES,
  securityContract,
  securityEventDetailRequestSchema,
  securityEventDetailResponseSchema,
  securityEventSchema,
  securityEventsExportRequestSchema,
  securityEventsExportResponseSchema,
  securityEventsFilterSchema,
  securityEventsListRequestSchema,
  securityEventsListResponseSchema,
  securityMetricsRequestSchema,
  securityMetricsResponseSchema,
  securityMetricsSchema,
  type SecurityEvent,
  type SecurityEventDetailRequest,
  type SecurityEventDetailResponse,
  type SecurityEventType,
  type SecurityEventsExportRequest,
  type SecurityEventsExportResponse,
  type SecurityEventsFilter,
  type SecurityEventsListRequest,
  type SecurityEventsListResponse,
  type SecurityMetrics,
  type SecurityMetricsRequest,
  type SecurityMetricsResponse,
  type SecuritySeverity,
} from './domain/admin';

// ============================================================================
// TYPE DEFINITIONS (Namespace)
// ============================================================================

export * as Types from './types';

// Commonly-used types from ./types that are needed by server modules
export type { Permission, TenantRole } from './types/roles';

// ============================================================================
// BROWSER-SAFE UTILITIES
// ============================================================================

// --- Async ---
export * as Async from './utils/async';

export {
  BatchedQueue,
  DeferredPromise,
  ReactiveMap,
  delay,
  type BatchProcessResult,
  type BatchedQueueOptions,
} from './utils/async';

// --- Cache ---
export * as Cache from './utils/cache';

export {
  CacheCapacityError,
  CacheConnectionError,
  CacheDeserializationError,
  CacheError,
  CacheInvalidKeyError,
  CacheMemoryLimitError,
  CacheNotInitializedError,
  CacheProviderNotFoundError,
  CacheSerializationError,
  CacheTimeoutError,
  LRUCache,
  isCacheConnectionError,
  isCacheError,
  isCacheTimeoutError,
  memoize,
  toCacheError,
  type BaseCacheConfig,
  type CacheConfig,
  type CacheDeleteOptions,
  type CacheEntry,
  type CacheEntryMetadata,
  type CacheGetOptions,
  type CacheProvider,
  type CacheSetOptions,
  type CacheStats,
  type LRUCacheOptions,
  type MemoizeFunction,
  type MemoizeOptions,
  type MemoryCacheConfig,
  type RedisCacheConfig,
} from './utils/cache';

// --- Search ---
export * as Search from './utils/search';

export {
  FILTER_OPERATORS,
  InvalidCursorError,
  InvalidFieldError,
  InvalidFilterError,
  InvalidOperatorError,
  InvalidPaginationError,
  InvalidQueryError,
  InvalidSortError,
  LOGICAL_OPERATORS,
  QueryTooComplexError,
  SEARCH_DEFAULTS,
  SEARCH_ERROR_TYPES,
  SearchError,
  SearchProviderError,
  SearchProviderUnavailableError,
  SearchQueryBuilder,
  SearchTimeoutError,
  UnsupportedOperatorError,
  // Serialization
  buildURLWithQuery,
  compoundFilterSchema,
  contains,
  createSearchQuery,
  cursorSearchResultSchema,
  deserializeFromHash,
  deserializeFromJSON,
  deserializeFromURLParams,
  eq,
  evaluateCompoundFilter,
  evaluateCondition,
  evaluateFilter,
  extractQueryFromURL,
  facetBucketSchema,
  facetConfigSchema,
  facetResultSchema,
  facetedSearchQuerySchema,
  facetedSearchResultSchema,
  filterArray,
  filterConditionSchema,
  filterOperatorSchema,
  filterPrimitiveSchema,
  filterSchema,
  filterValueSchema,
  fromSearchQuery,
  fullTextSearchConfigSchema,
  getFieldValue,
  gt,
  highlightedFieldSchema,
  inArray,
  isCompoundFilter,
  isFilterCondition,
  isInvalidFilterError,
  isInvalidQueryError,
  isSearchError,
  isSearchProviderError,
  isSearchTimeoutError,
  logicalOperatorSchema,
  lt,
  mergeSearchParamsIntoURL,
  neq,
  paginateArray,
  rangeValueSchema,
  searchQuerySchema,
  searchResultItemSchema,
  searchResultSchema,
  serializeToHash,
  serializeToJSON,
  serializeToURLParams,
  sortArray,
  sortConfigSchema,
  urlSearchParamsSchema,
  type CompoundFilter,
  type CursorSearchResult,
  type FacetBucket,
  type FacetConfig,
  type FacetResult,
  type FacetedSearchQuery,
  type FacetedSearchResult,
  type FilterCondition,
  type FilterOperator,
  type FilterPrimitive,
  type FilterValue,
  type FullTextSearchConfig,
  type HighlightedField,
  type LogicalOperator,
  type SearchCapabilities,
  type SearchErrorType,
  type SearchProvider,
  type SearchQuery,
  type SearchQueryInput,
  type SearchQueryOutput,
  type SearchResult,
  type SearchResultItem,
  type SerializationOptions,
  type SerializedFilter,
  type SerializedQuery,
  type SortConfig,
  type UrlSearchParamsInput,
} from './utils/search';

// --- Logger ---
// NOTE: The Logger type is available via the LoggerNs namespace below,
// or import directly from './logger'.
export * as LoggerNs from './logger';

export {
  CONSOLE_LOG_LEVELS,
  LOG_LEVELS,
  createConsoleLogger,
  createJobCorrelationId,
  createJobLogger,
  createLogger,
  createRequestContext,
  createRequestLogger,
  generateCorrelationId,
  getOrCreateCorrelationId,
  isValidCorrelationId,
  shouldLog,
  type BaseLogger,
  type ConsoleLogLevel,
  type ConsoleLoggerConfig,
  type LogData,
  type LogLevel,
  type Logger,
  type LoggerConfig,
  type RequestContext,
} from './logger';

// --- Monitor ---
export * as Monitor from './utils/monitor';

export {
  buildDetailedHealthResponse,
  checkCache,
  checkDatabase,
  checkEmail,
  checkPubSub,
  checkQueue,
  checkRateLimit,
  checkSchema,
  checkStorage,
  checkWebSocket,
  determineOverallStatus,
  type DetailedHealthResponse,
  type EmailHealthConfig,
  type HealthCheckCache,
  type HealthCheckDatabase,
  type HealthCheckPubSub,
  type HealthCheckQueue,
  type LiveResponse,
  type OverallStatus,
  type ReadyResponse,
  type RoutesResponse,
  type SchemaHealth,
  type SchemaValidationResult,
  type SchemaValidator,
  type ServiceHealth,
  type ServiceStatus,
  type StartupSummaryOptions,
  type StorageHealthConfig,
  type WebSocketStats,
} from './utils/monitor';

// --- PubSub ---
export * as PubSub from './utils/pubsub';

export {
  SubKeys,
  SubscriptionManager,
  parseRecordKey,
  publishAfterWrite,
  type ClientMessage,
  type ListKey,
  type ParsedRecordKey,
  type PostgresPubSub,
  type PostgresPubSubOptions,
  type PubSubMessage,
  type RecordKey,
  type ServerMessage,
  type SubscriptionKey,
  type SubscriptionManagerOptions,
  type WebSocket,
} from './utils/pubsub';

// --- Casing ---
export {
  camelToSnake,
  camelizeKeys,
  snakeToCamel,
  snakeifyKeys,
  toCamelCaseArray,
  toSnakeCase,
  type KeyMapping,
} from './utils/string/casing';
// NOTE: toCamelCase is exported from ./utils/string/string (string conversion).
// For record-key conversion, import { toCamelCase } from './utils/string/casing' directly.

// --- Keyboard ---
export {
  formatKeyBinding,
  isEditableElement,
  isMac,
  matchesAnyBinding,
  matchesKeyBinding,
  matchesModifiers,
  parseKeyBinding,
  type KeyModifiers,
  type ParsedKeyBinding,
} from './utils/keyboard';

// --- Constants ---
export {
  DAYS_PER_WEEK,
  HOURS_PER_DAY,
  MINUTES_PER_HOUR,
  MS_PER_DAY,
  MS_PER_HOUR,
  MS_PER_MINUTE,
  MS_PER_SECOND,
  SECONDS_PER_DAY,
  SECONDS_PER_HOUR,
  SECONDS_PER_MINUTE,
  SORT_ORDER,
  type SortOrder,
} from './utils/constants';

// --- Comparison ---
export { deepEqual } from './utils/comparison';

// --- Crypto ---
export {
  constantTimeCompare,
  generateSecureId,
  generateToken,
  generateUUID,
} from './utils/crypto/crypto';

// --- Date ---
export {
  formatDate,
  formatDateTime,
  formatTimeAgo,
  toISODateOnly,
  toISOStringOrNull,
} from './utils/date';

// --- HTTP ---
export {
  extractBearerToken,
  parseCookies,
  serializeCookie,
  type CookieOptions,
  type CookieSerializeOptions,
} from './utils/http/http';

export {
  type BaseRouteDefinition,
  type HandlerContext,
  type HttpMethod,
  type RequestInfo,
  type RouteHandler,
  type RouteMap,
  type RouteResult,
  type ValidationSchema,
} from './utils/http/http-types';

export {
  getValidatedClientIp,
  ipMatchesCidr,
  isFromTrustedProxy,
  isValidIp,
  isValidIpv4,
  isValidIpv6,
  parseCidr,
  parseXForwardedFor,
  validateCidrList,
  type ForwardedInfo,
  type ProxyValidationConfig,
} from './utils/http/proxy';
export { parseMultipartFile, type ParsedMultipartFile } from './utils/http/multipart';
export { EXTRA_EXT_TO_MIME, getMimeType } from './utils/http/mime';
export { extractIpAddress, extractUserAgent, getRequesterId } from './utils/http/request';
export { SAFE_METHODS, CSRF_EXEMPT_PATHS, extractCsrfToken } from './utils/http/csrf';

export { hasDangerousKeys, sanitizePrototype } from './utils/security/prototype';
export {
  detectNoSQLInjection,
  detectSQLInjection,
  isValidInputKeyName,
  sanitizeString,
  type SQLInjectionDetectionOptions,
} from './utils/security/input';
export {
  getInjectionErrors,
  sanitizeObject,
  type SanitizationResult,
  type ValidationOptions,
} from './utils/security/sanitization';

// --- Routes ---
export { createRouteMap, protectedRoute, publicRoute } from './utils/http/routes';

// --- Pagination ---
export {
  DEFAULT_PAGE_LIMIT,
  DEFAULT_SORT_BY,
  DEFAULT_SORT_ORDER,
  PAGINATION_ERROR_TYPES,
  PaginationError,
  buildCursorPaginationQuery,
  calculateCursorPaginationMetadata,
  calculateOffsetPaginationMetadata,
  createCursorForItem,
  createCursorPaginatedResult,
  createPaginatedResult,
  cursorPaginatedResultSchema,
  cursorPaginationOptionsSchema,
  decodeCursor,
  encodeCursor,
  getQueryParam,
  getSortableValue,
  isCursorValue,
  paginatedResultSchema,
  paginationOptionsSchema,
  parseLimitParam,
  parsePageParam,
  parseSortByParam,
  parseSortOrderParam,
  sortOrderSchema,
  type CursorData,
  type CursorPaginatedResult,
  type CursorPaginationOptions,
  type PaginatedResult,
  type PaginationErrorType,
  type PaginationOptions,
  type PaginationParamNames,
  type PaginationParseConfig,
} from './utils/pagination';

// --- Rate Limit ---
export { createRateLimiter, type RateLimitInfo } from './utils/rate-limit';

// --- Storage ---
export {
  ALLOWED_IMAGE_TYPES,
  MAX_IMAGE_SIZE,
  MAX_LOGO_SIZE,
  generateUniqueFilename,
  joinStoragePath,
  normalizeStoragePath,
  validateFileType,
} from './utils/storage';

// --- String ---
export {
  capitalize,
  canonicalizeEmail,
  countCharactersNoWhitespace,
  countWords,
  escapeHtml,
  formatBytes,
  normalizeEmail,
  normalizeWhitespace,
  padLeft,
  slugify,
  stripControlChars,
  titleCase,
  toCamelCase,
  toKebabCase,
  toPascalCase,
  trimTrailingSlashes,
  truncate,
} from './utils/string/string';

// --- User Agent ---
export { parseUserAgent, type ParsedUserAgent } from './utils/user-agent';

// --- Token ---
export { addAuthHeader, createTokenStore, tokenStore, type TokenStore } from './utils/crypto/token';

// --- Theme tokens ---
export {
  DEFAULT_CONTRAST_MODE,
  DEFAULT_DENSITY,
  densityMultipliers,
  getContrastCssVariables,
  getDensityCssVariables,
  getSpacingForDensity,
  highContrastDarkOverrides,
  highContrastLightOverrides,
  type ContrastMode,
  type Density,
} from './domain/theme';
