// main/shared/src/index.ts

// ============================================================================
// PRIMITIVES
// ============================================================================

// Type vocabulary
export type {
  ApiResponse,
  ApiResult,
  Contract,
  EndpointContract,
  ErrorCode,
  ErrorResponse,
  InferResponseData,
  StatusCode,
} from './primitives/api';

// Constants
export {
  ALL_MEDIA_EXTENSIONS,
  ALLOWED_IMAGE_MIME_TYPES,
  ALLOWED_MEDIA_MIME_TYPES,
  AUDIO_EXTENSIONS,
  AUDIT_ACTION_REGEX,
  AUDIT_PATTERNS,
  DATE_FORMATS,
  DATE_ONLY_REGEX,
  DAYS_PER_WEEK,
  EMAIL_REGEX,
  EXT_TO_MIME,
  EXTRA_EXT_TO_MIME,
  FILE_PURPOSES,
  HOURS_PER_DAY,
  IMAGE_EXTENSIONS,
  IP_V4_REGEX,
  IP_V6_REGEX,
  MAGIC_NUMBERS,
  MIME_TO_EXT,
  MINUTES_PER_HOUR,
  MS_PER_DAY,
  MS_PER_HOUR,
  MS_PER_MINUTE,
  MS_PER_SECOND,
  PHONE_REGEX,
  REGEX_PATTERNS,
  SECONDS_PER_DAY,
  SECONDS_PER_HOUR,
  SECONDS_PER_MINUTE,
  STORAGE_PROVIDERS,
  TIME,
  TIME_ZONE,
  URL_REGEX,
  USERNAME_REGEX_LOCAL,
  UUID_REGEX,
  VIDEO_EXTENSIONS,
} from './primitives/constants';

// Schema
export {
  activityIdSchema,
  apiKeyIdSchema,
  auditEventIdSchema,
  coerceDate,
  coerceNumber,
  consentLogIdSchema,
  createArraySchema,
  createBrandedStringSchema,
  createBrandedUuidSchema,
  createEnumSchema,
  createLiteralSchema,
  createSchema,
  createUnionSchema,
  emailLogIdSchema,
  emailTemplateKeySchema,
  fileIdSchema,
  inviteIdSchema,
  jobIdSchema,
  legalDocumentIdSchema,
  membershipIdSchema,
  notificationIdSchema,
  organizationIdSchema,
  parseBoolean,
  parseNullable,
  parseNullableOptional,
  parseNumber,
  parseObject,
  parseOptional,
  parsePlanId,
  parseRecord,
  parseString,
  parseTenantId,
  parseTypedRecord,
  parseUserId,
  planIdSchema,
  sessionIdSchema,
  subscriptionIdSchema,
  tenantIdSchema,
  userAgreementIdSchema,
  uuidSchema,
  webhookDeliveryIdSchema,
  webhookIdSchema,
  withDefault,
  type ActivityId,
  type ApiKeyId,
  type AuditEventId,
  type ConsentLogId,
  type EmailLogId,
  type EmailTemplateKey,
  type FileId,
  type InferSchema,
  type InviteId,
  type JobId,
  type LegalDocumentId,
  type MembershipId,
  type NotificationId,
  type OrganizationId,
  type ParseNumberOptions,
  type ParseStringOptions,
  type SafeParseResult,
  type Schema,
  type SessionId,
  type TenantId,
  type UserAgreementId,
  type WebhookDeliveryId,
  type WebhookId,
} from './primitives/schema';

// Helpers (consolidated: object, string, async, response, result, crypto)
export {
  assert,
  assertDefined,
  assertNever,
  camelizeKeys,
  camelToSnake,
  canonicalizeEmail,
  capitalize,
  constantTimeCompare,
  countCharactersNoWhitespace,
  countWords,
  deepEqual,
  DeferredPromise,
  delay,
  err,
  escapeHtml,
  formatBytes,
  generateSecureId,
  generateToken,
  generateUUID,
  getFieldValue,
  hasDangerousKeys,
  isErr,
  isErrorResponse,
  isNonEmptyString,
  isNumber,
  isObjectLike,
  isOk,
  isPlainObject,
  isSafeObjectKey,
  isString,
  isSuccessResponse,
  normalizeEmail,
  normalizeWhitespace,
  ok,
  padLeft,
  sanitizePrototype,
  slugify,
  snakeifyKeys,
  snakeToCamel,
  stripControlChars,
  titleCase,
  toCamelCase,
  toCamelCaseArray,
  toKebabCase,
  toPascalCase,
  toSnakeCase,
  trimTrailingSlashes,
  truncate,
  type ApiErrorResponse,
  type ApiSuccessResponse,
  type KeyMapping,
  type Result,
} from './primitives/helpers';

// ============================================================================
// SYSTEM INFRASTRUCTURE
// ============================================================================

// Errors (consolidated: HTTP + Auth + Error mapper)
export {
  AccountLockedError,
  AppError,
  BadRequestError,
  BaseError,
  ConfigurationError,
  ConflictError,
  EmailAlreadyExistsError,
  EmailNotVerifiedError,
  EmailSendError,
  ForbiddenError,
  formatValidationErrors,
  getErrorStatusCode,
  getSafeErrorMessage,
  InternalError,
  InternalServerError,
  InvalidCredentialsError,
  InvalidTokenError,
  isAppError,
  isKnownAuthError,
  mapErrorToHttpResponse,
  NotFoundError,
  OAuthError,
  OAuthStateMismatchError,
  ResourceNotFoundError,
  toAppError,
  TokenReuseError,
  TooManyRequestsError,
  TotpInvalidError,
  TotpRequiredError,
  UnauthorizedError,
  UnprocessableError,
  UserNotFoundError,
  ValidationError,
  WeakPasswordError,
  type AppErrorInfo,
  type ErrorMapperLogger,
  type ErrorMapperOptions,
  type ErrorStatusCode,
  type HttpErrorResponse,
  type ValidationErrorDetail,
  type ValidationErrorResponse,
  type ValidationIssue,
} from './system/errors';

// Constants (consolidated)
export {
  ACCESS_TOKEN_COOKIE_NAME,
  AGGREGATION_TYPES,
  ANSI,
  API_PREFIX,
  API_VERSIONS,
  AUDIT_CATEGORIES,
  AUDIT_SEVERITIES,
  AUTH_CONSTANTS,
  AUTH_ERROR_MESSAGES,
  AUTH_SUCCESS_MESSAGES,
  CACHE_TTL,
  CORS_CONFIG,
  CRYPTO,
  CSRF_EXEMPT_PATHS,
  DEFAULT_PAGINATION,
  DEVICE_TYPES,
  EMAIL_PROVIDERS,
  EMAIL_STATUSES,
  ERROR_CODES,
  ERROR_MESSAGES,
  FILTER_OPERATOR_VALUES,
  FILTER_OPERATORS,
  HEALTH_STATUS,
  HTTP_ERROR_MESSAGES,
  HTTP_STATUS,
  JOB_PRIORITIES,
  JOB_PRIORITY_VALUES,
  JOB_STATUS_CONFIG,
  JOB_STATUSES,
  LIMITS,
  LOG_LEVELS,
  LOGICAL_OPERATOR_VALUES,
  LOGICAL_OPERATORS,
  MAX_CHUNK_SIZE,
  MAX_DELIVERY_ATTEMPTS,
  MAX_FILENAME_LENGTH,
  MAX_UPLOAD_FILE_SIZE,
  MAX_UPLOAD_TIMEOUT_MS,
  PLATFORM_TYPES,
  QUOTAS,
  RATE_LIMIT_WINDOWS,
  RETRY_DELAYS_MINUTES,
  SAFE_METHODS,
  SEARCH_DEFAULTS,
  SEARCH_ERROR_TYPES,
  SENSITIVE_KEYS,
  SMS_LIMITS,
  SORT_ORDER,
  STANDARD_HEADERS,
  SUBSCRIBABLE_EVENT_TYPES,
  TERMINAL_DELIVERY_STATUSES,
  TERMINAL_STATUSES,
  WEBHOOK_DELIVERY_STATUSES,
  WEBHOOK_EVENT_TYPES,
  type HttpStatusCode,
} from './system/constants';

// Environment
export { baseEnvSchema, getRawEnv, validateEnv, type BaseEnv } from './system/env';

// Ports
export {
  type Attachment,
  type BaseStorageConfig,
  type BreadcrumbData,
  type CacheService,
  type ConfigService,
  type EmailOptions,
  type EmailService,
  type ErrorTracker,
  type HasErrorTracker,
  type HealthCheckResult,
  type InfrastructureService,
  type Job,
  type JobHandler,
  type JobOptions,
  type JobQueueService,
  type LocalStorageConfig,
  type MetricsService,
  type NotificationService,
  type ReadableStreamLike,
  type S3StorageConfig,
  type SendResult,
  type ServerLogger,
  type StorageClient,
  type StorageConfig,
  type StorageProvider,
} from './system/ports';

// HTTP (consolidated: response schemas, cookies, types, csrf, multipart, proxy, request, routes, user agent)
export {
  apiResultSchema,
  createRouteMap,
  emptyBodySchema,
  errorCodeSchema,
  errorResponseSchema,
  extractBearerToken,
  extractCsrfToken,
  extractIpAddress,
  extractUserAgent,
  getRequesterId,
  getValidatedClientIp,
  ipMatchesCidr,
  isFromTrustedProxy,
  isValidIp,
  isValidIpv4,
  isValidIpv6,
  parseCidr,
  parseCookies,
  parseMultipartFile,
  parseUserAgent,
  parseXForwardedFor,
  protectedRoute,
  publicRoute,
  serializeCookie,
  successResponseSchema,
  validateCidrList,
  type BaseRouteDefinition,
  type CookieOptions,
  type CookieSerializeOptions,
  type EmptyBody,
  type ForwardedInfo,
  type HandlerContext,
  type HttpMethod,
  type ParsedMultipartFile,
  type ParsedUserAgent,
  type ProxyValidationConfig,
  type RequestInfo,
  type RouteHandler,
  type RouteMap,
  type RouteResult,
  type ValidationSchema,
} from './system/http';

// Context
export {
  type AuthenticatedUser,
  type BaseContext,
  type HasBilling,
  type HasCache,
  type HasEmail,
  type HasNotifications,
  type HasPubSub,
  type HasQueue,
  type HasStorage,
  type RequestContext as ContractRequestContext,
  type RequestInfo as ContractRequestInfo,
  type ReplyContext,
} from './system/context';

// DI
export type { ModuleDeps, ModuleRegistrationOptions } from './system/di';

// Email types
export { type EmailProvider, type EmailStatus } from './system/email';

// Files (consolidated: schemas + storage utilities)
export {
  ALLOWED_IMAGE_TYPES,
  fileDeleteResponseSchema,
  fileRecordSchema,
  filesListResponseSchema,
  fileUploadResponseSchema,
  generateUniqueFilename,
  joinStoragePath,
  MAX_IMAGE_SIZE,
  MAX_LOGO_SIZE,
  normalizeStoragePath,
  validateFileType,
  type FileDeleteResponse,
  type FilePurpose,
  type FileRecord,
  type FilesListResponse,
  type FileUploadRequest,
  type FileUploadResponse,
} from './system/files';

// Feature flags
export {
  createFeatureFlagRequestSchema,
  evaluateFlag,
  featureFlagActionResponseSchema,
  featureFlagSchema,
  featureFlagsListResponseSchema,
  setTenantFeatureOverrideRequestSchema,
  tenantFeatureOverrideSchema,
  updateFeatureFlagRequestSchema,
  type CreateFeatureFlagRequest,
  type FeatureFlag,
  type FeatureFlagActionResponse,
  type FeatureFlagsListResponse,
  type SetTenantFeatureOverrideRequest,
  type TenantFeatureOverride,
  type UpdateFeatureFlagRequest,
} from './system/feature-flags';

// Jobs (consolidated)
export {
  calculateBackoff,
  canRetry,
  createJobSchema,
  getJobStatusLabel,
  getJobStatusTone,
  isTerminalStatus,
  jobActionResponseSchema,
  jobDetailsSchema,
  jobListQuerySchema,
  jobListResponseSchema,
  jobSchema,
  queueStatsSchema,
  shouldProcess,
  updateJobSchema,
  type CreateJob,
  type DomainJob,
  type JobActionResponse,
  type JobDetails,
  type JobError,
  type JobListQuery,
  type JobListResponse,
  type JobPriority,
  type JobStatus,
  type QueueStats,
  type UpdateJob,
} from './system/jobs';

// API keys
export {
  apiKeyItemSchema,
  apiKeySchema,
  createApiKeyRequestSchema,
  createApiKeyResponseSchema,
  createApiKeySchema,
  deleteApiKeyResponseSchema,
  listApiKeysResponseSchema,
  revokeApiKeyResponseSchema,
  updateApiKeySchema,
  type ApiKey,
  type ApiKeyItem,
  type CreateApiKey,
  type CreateApiKeyRequest,
  type CreateApiKeyResponse,
  type DeleteApiKeyResponse,
  type ListApiKeysResponse,
  type RevokeApiKeyResponse,
  type UpdateApiKey,
} from './system/api-keys';

// Webhooks
export {
  calculateRetryDelay,
  createWebhookDeliverySchema,
  createWebhookSchema,
  isDeliveryTerminal,
  matchesEventFilter,
  rotateSecretResponseSchema,
  shouldRetryDelivery,
  updateWebhookDeliverySchema,
  updateWebhookSchema,
  webhookDeleteResponseSchema,
  webhookDeliveryItemSchema,
  webhookDeliverySchema,
  webhookItemSchema,
  webhookListResponseSchema,
  webhookMutationResponseSchema,
  webhookResponseSchema,
  webhookSchema,
  webhookWithDeliveriesSchema,
  type CreateWebhook,
  type CreateWebhookDelivery,
  type RotateSecretResponse,
  type UpdateWebhook,
  type UpdateWebhookDelivery,
  type Webhook,
  type WebhookDeleteResponse,
  type WebhookDelivery,
  type WebhookDeliveryItem,
  type WebhookDeliveryStatus,
  type WebhookEventType,
  type WebhookItem,
  type WebhookListResponse,
  type WebhookMutationResponse,
  type WebhookResponse,
  type WebhookWithDeliveries,
} from './system/webhooks';

// Native bridge
export { type NativeBridge } from './system/native';

// ============================================================================
// SYSTEM UTILITIES
// ============================================================================

// Cache
export {
  CacheCapacityError,
  CacheConnectionError,
  CacheDeserializationError,
  CacheError,
  CacheInvalidKeyError,
  CacheMemoryLimitError,
  CacheNotInitializedError,
  CacheProviderNotFoundError,
  CacheSerializationError,
  CacheTimeoutError,
  isCacheConnectionError,
  isCacheError,
  isCacheTimeoutError,
  LRUCache,
  memoize,
  toCacheError,
  type BaseCacheConfig,
  type CacheConfig,
  type CacheDeleteOptions,
  type CacheEntry,
  type CacheEntryMetadata,
  type CacheGetOptions,
  type CacheProvider,
  type CacheSetOptions,
  type CacheStats,
  type LRUCacheOptions,
  type MemoizeFunction,
  type MemoizeOptions,
  type MemoryCacheConfig,
  type RedisCacheConfig,
} from './system/cache';

// Search
export {
  buildURLWithQuery,
  compoundFilterSchema,
  contains,
  createSearchQuery,
  cursorSearchResultSchema,
  deserializeFromHash,
  deserializeFromJSON,
  deserializeFromURLParams,
  eq,
  evaluateCompoundFilter,
  evaluateCondition,
  evaluateFilter,
  extractQueryFromURL,
  facetBucketSchema,
  facetConfigSchema,
  facetedSearchQuerySchema,
  facetedSearchResultSchema,
  facetResultSchema,
  filterArray,
  filterConditionSchema,
  filterOperatorSchema,
  filterPrimitiveSchema,
  filterSchema,
  filterValueSchema,
  fromSearchQuery,
  fullTextSearchConfigSchema,
  gt,
  highlightedFieldSchema,
  inArray,
  InvalidCursorError,
  InvalidFieldError,
  InvalidFilterError,
  InvalidOperatorError,
  InvalidPaginationError,
  InvalidQueryError,
  InvalidSortError,
  isCompoundFilter,
  isFilterCondition,
  isInvalidFilterError,
  isInvalidQueryError,
  isSearchError,
  isSearchProviderError,
  isSearchTimeoutError,
  logicalOperatorSchema,
  lt,
  mergeSearchParamsIntoURL,
  neq,
  paginateArray,
  QueryTooComplexError,
  rangeValueSchema,
  SearchError,
  SearchProviderError,
  SearchProviderUnavailableError,
  SearchQueryBuilder,
  searchQuerySchema,
  searchResultItemSchema,
  searchResultSchema,
  SearchTimeoutError,
  serializeToHash,
  serializeToJSON,
  serializeToURLParams,
  sortArray,
  sortConfigSchema,
  UnsupportedOperatorError,
  urlSearchParamsSchema,
  type CompoundFilter,
  type CursorSearchResult,
  type FacetBucket,
  type FacetConfig,
  type FacetedSearchQuery,
  type FacetedSearchResult,
  type FacetResult,
  type FilterCondition,
  type FilterOperator,
  type FilterPrimitive,
  type FilterValue,
  type FullTextSearchConfig,
  type HighlightedField,
  type LogicalOperator,
  type SearchCapabilities,
  type SearchErrorType,
  type SearchProvider,
  type SearchQuery,
  type SearchQueryInput,
  type SearchQueryOutput,
  type SearchResult,
  type SearchResultItem,
  type SerializationOptions,
  type SerializedFilter,
  type SerializedQuery,
  type SortConfig,
  type UrlSearchParamsInput,
} from './system/search';

// Logger
export {
  CONSOLE_LOG_LEVELS,
  createConsoleLogger,
  createJobCorrelationId,
  createJobLogger,
  createLogger,
  createRequestContext,
  createRequestLogger,
  generateCorrelationId,
  getOrCreateCorrelationId,
  isValidCorrelationId,
  shouldLog,
  type BaseLogger,
  type ConsoleLoggerConfig,
  type ConsoleLogLevel,
  type LogData,
  type Logger,
  type LoggerConfig,
  type LogLevel,
  type RequestContext,
} from './system/logger';

// Health
export {
  buildDetailedHealthResponse,
  checkCache,
  checkDatabase,
  checkEmail,
  checkPubSub,
  checkQueue,
  checkRateLimit,
  checkSchema,
  checkStorage,
  checkWebSocket,
  detailedHealthResponseSchema,
  determineOverallStatus,
  liveResponseSchema,
  readyResponseSchema,
  type DetailedHealthResponse,
  type EmailHealthConfig,
  type HealthCheckCache,
  type HealthCheckDatabase,
  type HealthCheckPubSub,
  type HealthCheckQueue,
  type LiveResponse,
  type OverallStatus,
  type ReadyResponse,
  type RoutesResponse,
  type SchemaHealth,
  type SchemaValidationResult,
  type SchemaValidator,
  type ServiceHealth,
  type ServiceStatus,
  type StartupSummaryOptions,
  type StorageHealthConfig,
  type WebSocketStats,
} from './system/health';

// PubSub
export {
  parseRecordKey,
  publishAfterWrite,
  SubKeys,
  SubscriptionManager,
  type ClientMessage,
  type ListKey,
  type ParsedRecordKey,
  type PostgresPubSub,
  type PostgresPubSubOptions,
  type PubSubMessage,
  type RecordKey,
  type ServerMessage,
  type SubscriptionKey,
  type SubscriptionManagerOptions,
  type WebSocket,
} from './system/pubsub';

// Realtime
export {
  applyOperation,
  applyOperations,
  checkVersionConflicts,
  conflictResponseSchema,
  getOperationPointers,
  getRecordsRequestSchema,
  getRecordsResponseSchema,
  isFieldMutable,
  listInsertOperationSchema,
  listPositionSchema,
  listRemoveOperationSchema,
  operationSchema,
  PROTECTED_FIELDS,
  REALTIME_ERRORS,
  recordMapSchema,
  recordPointerSchema,
  recordSchema,
  setNowOperationSchema,
  setOperationSchema,
  setPath,
  transactionSchema,
  writeResponseSchema,
  type ApplyOperationsResult,
  type ConflictResponse,
  type GetRecordsRequest,
  type GetRecordsResponse,
  type ListPosition,
  type ListInsertOperation as RealtimeListInsertOperation,
  type ListRemoveOperation as RealtimeListRemoveOperation,
  type RealtimeOperation,
  type RealtimeRecord,
  type RecordMap,
  type RecordPointer,
  type SetNowOperation,
  type SetOperation as RealtimeSetOperation,
  type RealtimeTransaction,
  type VersionConflict,
  type VersionedRecord,
  type WriteResponse,
} from './system/realtime';

// Media
export {
  detectFileType,
  detectFileTypeFromPath,
  generateFileId,
  getMimeType,
  isAllowedFileType,
  parseAudioMetadataFromBuffer,
  sanitizeFilename,
  validateUploadConfig,
  type AudioMetadata,
  type AudioProcessingOptions,
  type ContentModerationResult,
  type FileTypeResult,
  type ImageProcessingOptions,
  type MediaMetadata,
  type MediaProcessingOptions,
  type ProcessingResult,
  type SecurityScanResult,
  type UploadConfig,
  type VideoProcessingOptions,
} from './system/media';

// Pagination
export {
  buildCursorPaginationQuery,
  calculateCursorPaginationMetadata,
  calculateOffsetPaginationMetadata,
  createCursorForItem,
  createCursorPaginatedResult,
  createPaginatedResult,
  cursorPaginatedResultSchema,
  cursorPaginationOptionsSchema,
  decodeCursor,
  DEFAULT_PAGE_LIMIT,
  DEFAULT_SORT_BY,
  DEFAULT_SORT_ORDER,
  encodeCursor,
  getQueryParam,
  getSortableValue,
  isCursorValue,
  paginatedResultSchema,
  PAGINATION_ERROR_TYPES,
  PaginationError,
  paginationOptionsSchema,
  parseLimitParam,
  parsePageParam,
  parseSortByParam,
  parseSortOrderParam,
  sortOrderSchema,
  type CursorData,
  type CursorPaginatedResult,
  type CursorPaginationOptions,
  type PaginatedResult,
  type PaginationErrorType,
  type PaginationOptions,
  type PaginationParamNames,
  type PaginationParseConfig,
} from './system/pagination';

// Security (consolidated: input, sanitization, rate limit)
export {
  createRateLimiter,
  detectNoSQLInjection,
  detectSQLInjection,
  getInjectionErrors,
  isValidInputKeyName,
  sanitizeObject,
  sanitizeString,
  type RateLimitInfo,
  type SanitizationResult,
  type SQLInjectionDetectionOptions,
  type ValidationOptions,
} from './system/security';

// Crypto
export {
  addAuthHeader,
  createTokenStore,
  tokenStore,
  type TokenStore,
} from './system/crypto';

// Usage metering
export {
  aggregateSnapshots,
  aggregateValues,
  isOverQuota,
  usageMetricSchema,
  usageMetricSummarySchema,
  usageSnapshotSchema,
  usageSummaryResponseSchema,
  type AggregationType,
  type UsageMetric,
  type UsageMetricSummary,
  type UsageSnapshot,
  type UsageSummaryResponse,
} from './system/usage-metering';

// ============================================================================
// CORE DOMAIN
// ============================================================================

// Auth (consolidated: schemas, policy, roles, sessions, passwords)
export {
  acceptTosRequestSchema,
  acceptTosResponseSchema,
  authResponseSchema,
  bffLoginResponseSchema,
  calculateEntropy,
  calculateScore,
  can,
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  containsUserInput,
  createUserSessionSchema,
  defaultPasswordConfig,
  deviceItemSchema,
  deviceListResponseSchema,
  emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  estimateCrackTime,
  estimatePasswordStrength,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema,
  generateFeedback,
  getCharsetSize,
  getSessionAge,
  getStrengthColor,
  getStrengthLabel,
  hasKeyboardPattern,
  hasPermission,
  hasRepeatedChars,
  hasSequentialChars,
  invalidateSessionsResponseSchema,
  isCommonPassword,
  isSessionActive,
  isSessionRevoked,
  loginRequestSchema,
  logoutResponseSchema,
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyRequestSchema,
  magicLinkVerifyResponseSchema,
  oauthCallbackQuerySchema,
  oauthCallbackResponseSchema,
  oauthConnectionSchema,
  oauthConnectionsResponseSchema,
  oauthEnabledProvidersResponseSchema,
  oauthInitiateResponseSchema,
  oauthLinkCallbackResponseSchema,
  oauthLinkResponseSchema,
  oauthProviderSchema,
  oauthUnlinkResponseSchema,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  removePhoneResponseSchema,
  renamePasskeyRequestSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  revertEmailChangeRequestSchema,
  revertEmailChangeResponseSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  setPhoneRequestSchema,
  setPhoneResponseSchema,
  smsChallengeRequestSchema,
  smsVerifyRequestSchema,
  sudoRequestSchema,
  sudoResponseSchema,
  tosStatusResponseSchema,
  totpLoginChallengeResponseSchema,
  totpLoginVerifyRequestSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpVerifyRequestSchema,
  totpVerifyResponseSchema,
  trustDeviceResponseSchema,
  updateUserSessionSchema,
  userSessionSchema,
  validatePassword,
  validatePasswordBasic,
  verifyPhoneRequestSchema,
  verifyPhoneResponseSchema,
  webauthnLoginOptionsRequestSchema,
  webauthnLoginVerifyRequestSchema,
  webauthnOptionsResponseSchema,
  webauthnRegisterVerifyRequestSchema,
  webauthnRegisterVerifyResponseSchema,
  type AcceptTosRequest,
  type AcceptTosResponse,
  type AuthContext,
  type AuthResponse,
  type BffLoginResponse,
  type ChangeEmailRequest,
  type ChangeEmailResponse,
  type ConfirmEmailChangeRequest,
  type ConfirmEmailChangeResponse,
  type CreateUserSession,
  type DeviceItem,
  type DeviceListResponse,
  type EmailVerificationRequest,
  type EmailVerificationResponse,
  type ForgotPasswordRequest,
  type ForgotPasswordResponse,
  type InvalidateSessionsResponse,
  type LoginRequest,
  type LoginSuccessResponse,
  type LogoutResponse,
  type MagicLinkRequest,
  type MagicLinkRequestResponse,
  type MagicLinkVerifyRequest,
  type MagicLinkVerifyResponse,
  type OAuthCallbackQuery,
  type OAuthCallbackResponse,
  type OAuthConnection,
  type OAuthConnectionsResponse,
  type OAuthEnabledProvidersResponse,
  type OAuthInitiateResponse,
  type OAuthLinkCallbackResponse,
  type OAuthLinkResponse,
  type OAuthProvider,
  type OAuthUnlinkResponse,
  type PasskeyListItem,
  type PasswordConfig,
  type PasswordPenalties,
  type PasswordValidationResult,
  type Permission,
  type PolicyAction,
  type PolicyResource,
  type RefreshResponse,
  type RegisterRequest,
  type RegisterResponse,
  type RemovePhoneResponse,
  type RenamePasskeyRequest,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type RevertEmailChangeRequest,
  type RevertEmailChangeResponse,
  type SetPasswordRequest,
  type SetPasswordResponse,
  type SetPhoneRequest,
  type SetPhoneResponse,
  type SmsChallengeRequest,
  type SmsChallengeResponse,
  type SmsLoginChallengeResponse,
  type SmsVerifyRequest,
  type StrengthResult,
  type SudoRequest,
  type SudoResponse,
  type TenantRole,
  type TosStatusResponse,
  type TotpLoginChallengeResponse,
  type TotpLoginVerifyRequest,
  type TotpSetupResponse,
  type TotpStatusResponse,
  type TotpVerifyRequest,
  type TotpVerifyResponse,
  type TrustDeviceResponse,
  type UpdateUserSession,
  type UserSession,
  type VerifyPhoneRequest,
  type VerifyPhoneResponse,
  type WebauthnLoginOptionsRequest,
  type WebauthnLoginVerifyRequest,
  type WebauthnOptionsResponse,
  type WebauthnRegisterVerifyRequest,
  type WebauthnRegisterVerifyResponse,
} from './core/auth';

// Field schemas
export { emailSchema, isoDateTimeSchema, passwordSchema } from './core/schemas';

// Transactions
export {
  createListInsertOperation,
  createListRemoveOperation,
  createSetOperation,
  createTransaction,
  invertOperation,
  invertTransaction,
  isListInsertOperation,
  isListRemoveOperation,
  isSetOperation,
  mergeTransactions,
  type ListInsertOperation,
  type ListRemoveOperation,
  type Operation,
  type SetOperation,
  type Transaction,
} from './core/transactions';

// Core constants (consolidated)
export {
  AUTH_EXPIRY,
  COMMON_PASSWORDS,
  KEYBOARD_PATTERNS,
  LOGIN_FAILURE_REASON,
  OAUTH_PROVIDERS,
  RETENTION_PERIODS,
} from './core/constants';

// Audit log
export {
  auditEventSchema,
  auditLogFilterSchema,
  auditLogListResponseSchema,
  buildAuditEvent,
  createAuditEventSchema,
  getAuditActionTone,
  getAuditSeverityTone,
  sanitizeMetadata,
  type AuditBuilderParams,
  type AuditCategory,
  type AuditEvent,
  type AuditLogFilter,
  type AuditLogListResponse,
  type AuditSeverity,
  type CreateAuditEvent,
} from './core/audit-log';

// Billing (consolidated: schemas + service types)
export {
  addPaymentMethodRequestSchema,
  adminBillingStatsSchema,
  adminPlanResponseSchema,
  adminPlanSchema,
  adminPlansListResponseSchema,
  assertEntitled,
  assertWithinLimit,
  BILLING_EVENT_TYPES,
  BILLING_PROVIDERS,
  BillingProviderError,
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError,
  calculateProration,
  cancelSubscriptionRequestSchema,
  CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError,
  cardDetailsSchema,
  checkoutRequestSchema,
  checkoutResponseSchema,
  CheckoutSessionError,
  createPlanRequestSchema,
  CustomerNotFoundError,
  FEATURE_KEYS,
  formatPlanInterval,
  formatPrice,
  formatPriceWithInterval,
  getCardBrandLabel,
  getInvoiceStatusLabel,
  getInvoiceStatusVariant,
  getPaymentMethodIcon,
  getPaymentMethodLabel,
  getSubscriptionStatusLabel,
  getSubscriptionStatusVariant,
  hasActiveSubscription,
  INVOICE_STATUSES,
  InvoiceNotFoundError,
  invoiceResponseSchema,
  invoiceSchema,
  invoicesListResponseSchema,
  isBillingProviderError,
  isEntitled,
  isPlanError,
  isSubscriptionError,
  PAYMENT_METHOD_TYPES,
  PaymentMethodNotFoundError,
  paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema,
  PaymentMethodValidationError,
  PLAN_FEES,
  PLAN_INTERVALS,
  planFeatureSchema,
  PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  PlanNotFoundError,
  planSchema,
  plansListResponseSchema,
  portalSessionRequestSchema,
  portalSessionResultSchema,
  resolveEntitlements,
  setupIntentResponseSchema,
  SUBSCRIPTION_STATUSES,
  subscriptionActionResponseSchema,
  SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError,
  subscriptionResponseSchema,
  subscriptionSchema,
  syncStripeResponseSchema,
  updatePlanRequestSchema,
  updateSubscriptionRequestSchema,
  WebhookEventAlreadyProcessedError,
  WebhookSignatureError,
  type AddPaymentMethodRequest,
  type AdminBillingStats,
  type AdminPlan,
  type AdminPlanResponse,
  type AdminPlansListResponse,
  type BillingEventType,
  type BillingProvider,
  type BillingService,
  type BillingStats,
  type CancelSubscriptionRequest,
  type CardDetails,
  type CheckoutParams,
  type CheckoutRequest,
  type CheckoutResponse,
  type CheckoutResult,
  type CreatePlanRequest,
  type CreateProductParams,
  type CreateProductResult,
  type EntitlementInput,
  type FeatureEntitlement,
  type FeatureKey,
  type Invoice,
  type InvoiceResponse,
  type InvoicesListResponse,
  type InvoiceStatus,
  type NormalizedEventType,
  type NormalizedWebhookEvent,
  type PaymentMethod,
  type PaymentMethodResponse,
  type PaymentMethodsListResponse,
  type PaymentMethodType,
  type Plan,
  type PlanFeature,
  type PlanId,
  type PlanInterval,
  type PlansListResponse,
  type PortalSessionRequest,
  type PortalSessionResult,
  type ProviderInvoice,
  type ProviderPaymentMethod,
  type ProviderSubscription,
  type ResolvedEntitlements,
  type SetupIntentResponse,
  type SetupIntentResult,
  type StatusVariant,
  type Subscription,
  type SubscriptionActionResponse,
  type SubscriptionId,
  type SubscriptionResponse,
  type SubscriptionState,
  type SubscriptionStatus,
  type SyncStripeResponse,
  type UpdatePlanRequest,
  type UpdateSubscriptionRequest,
} from './core/billing';

// Compliance
export {
  complianceActionResponseSchema,
  consentLogSchema,
  consentPreferencesResponseSchema,
  createConsentLogSchema,
  createDataExportRequestSchema,
  createLegalDocumentSchema,
  createUserAgreementSchema,
  dataExportRequestedResponseSchema,
  dataExportRequestSchema,
  getEffectiveConsent,
  isConsentGranted,
  legalDocumentSchema,
  needsReacceptance,
  updateConsentPreferencesRequestSchema,
  updateLegalDocumentSchema,
  userAgreementSchema,
  type ComplianceActionResponse,
  type ConsentLog,
  type ConsentPreferencesResponse,
  type ConsentType,
  type CreateConsentLog,
  type CreateDataExportRequest,
  type CreateLegalDocument,
  type CreateUserAgreement,
  type DataExportRequest,
  type DataExportRequestedResponse,
  type DataExportStatus,
  type DataExportType,
  type DocumentType,
  type LegalDocument,
  type UpdateConsentPreferencesRequest,
  type UpdateLegalDocument,
  type UserAgreement,
} from './core/compliance';

// Tenant (consolidated: includes membership)
export {
  acceptInvitationSchema,
  addMemberSchema,
  assertWorkspaceScope,
  canAcceptInvite,
  canAssignRole,
  canChangeRole,
  canLeave,
  canRemoveMember,
  canRevokeInvite,
  createInvitationSchema,
  createTenantSchema,
  createWorkspaceContext,
  extractEmailDomain,
  getInvitationStatusTone,
  getNextOwnerCandidate,
  getRoleLevel,
  getTenantRoleTone,
  getWorkspaceContext,
  hasAtLeastRole,
  hasRequiredWorkspaceRole,
  invitationSchema,
  invitationsListResponseSchema,
  isEmailDomainAllowed,
  isInviteExpired,
  isSoleOwner,
  isWorkspaceScoped,
  membershipActionResponseSchema,
  membershipSchema,
  membersListResponseSchema,
  ROLE_LEVELS,
  tenantActionResponseSchema,
  tenantListResponseSchema,
  tenantSchema,
  transferOwnershipSchema,
  updateMembershipRoleSchema,
  updateTenantSchema,
  WORKSPACE_ID_HEADER,
  WORKSPACE_ROLE_HEADER,
  type AcceptInvitation,
  type AddMember,
  type CreateInvitation,
  type CreateTenantInput,
  type Invitation,
  type InvitationsListResponse,
  type InvitationStatus,
  type MaybeWorkspaceContext,
  type Membership,
  type MembershipActionResponse,
  type MembersListResponse,
  type Tenant,
  type TenantActionResponse,
  type TenantListResponse,
  type TransferOwnershipInput,
  type UpdateMembershipRole,
  type UpdateTenantInput,
  type WorkspaceContext,
} from './core/tenant';

// Notifications
export {
  baseMarkAsReadRequestSchema,
  DEFAULT_NOTIFICATION_PREFERENCES,
  deleteNotificationResponseSchema,
  getNotificationLevelTone,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  markReadResponseSchema,
  NOTIFICATION_LEVELS,
  NOTIFICATION_PAYLOAD_MAX_SIZE,
  NOTIFICATION_TYPES,
  notificationDeleteRequestSchema,
  notificationPreferencesSchema,
  NotificationRateLimitError,
  notificationSchema,
  NotificationsDisabledError,
  NotificationSendError,
  notificationsListRequestSchema,
  notificationsListResponseSchema,
  PayloadTooLargeError,
  PreferencesNotFoundError,
  preferencesResponseSchema,
  ProviderError,
  ProviderNotConfiguredError,
  PushProviderNotConfiguredError,
  PushSubscriptionExistsError,
  PushSubscriptionNotFoundError,
  QuietHoursActiveError,
  sendNotificationRequestSchema,
  sendNotificationResponseSchema,
  shouldSendNotification,
  subscribeRequestSchema,
  subscribeResponseSchema,
  SubscriptionExistsError,
  SubscriptionExpiredError,
  SubscriptionNotFoundError,
  unsubscribeRequestSchema,
  unsubscribeResponseSchema,
  updatePreferencesRequestSchema,
  vapidKeyResponseSchema,
  VapidNotConfiguredError,
  type BaseMarkAsReadRequest,
  type BatchSendResult,
  type DeleteNotificationResponse,
  type MarkReadResponse,
  type Notification,
  type NotificationAction,
  type NotificationChannel,
  type NotificationDeleteRequest,
  type NotificationLevel,
  type NotificationMessage,
  type NotificationPayload,
  type NotificationPreferences,
  type NotificationPreferencesConfig,
  type NotificationPriority,
  type NotificationsListRequest,
  type NotificationsListResponse,
  type NotificationType,
  type NotificationTypePreference,
  type PreferencesResponse,
  type PushSendResult,
  type PushSubscription,
  type PushSubscriptionKeys,
  type SendNotificationRequest,
  type SendNotificationResponse,
  type StoredPushSubscription,
  type SubscribeRequest,
  type SubscribeResponse,
  type UnsubscribeRequest,
  type UnsubscribeResponse,
  type UpdatePreferencesRequest,
  type VapidKeyResponse,
} from './core/notifications';

// Users (consolidated)
export {
  ACCOUNT_DELETION_GRACE_PERIOD_DAYS,
  APP_ROLES,
  appRoleSchema,
  avatarDeleteResponseSchema,
  avatarUploadRequestSchema,
  avatarUploadResponseSchema,
  calculateDeletionGracePeriodEnd,
  canDeactivate,
  canReactivate,
  canRequestDeletion,
  canUser,
  changePasswordRequestSchema,
  changePasswordResponseSchema,
  deactivateAccountRequestSchema,
  deleteAccountRequestSchema,
  getAccountStatus,
  getAllRoles,
  getNextUsernameChangeDate,
  getRoleDisplayName,
  hasRole,
  isAccountActive,
  isAccountDeactivated,
  isAccountPendingDeletion,
  isAdmin,
  isModerator,
  isOwner,
  isRegularUser,
  isUser,
  isUsernameChangeCooldownActive,
  isWithinDeletionGracePeriod,
  profileCompletenessResponseSchema,
  RESERVED_USERNAMES,
  revokeAllSessionsResponseSchema,
  revokeSessionResponseSchema,
  sessionSchema,
  sessionsListResponseSchema,
  updateProfileRequestSchema,
  updateUsernameRequestSchema,
  USER_ROLES,
  userIdSchema,
  USERNAME_CHANGE_COOLDOWN_DAYS,
  userRoleSchema,
  userSchema,
  type AccountLifecycleFields,
  type AccountLifecycleResponse,
  type AccountStatus,
  type AppRole,
  type AvatarDeleteResponse,
  type AvatarUploadRequest,
  type AvatarUploadResponse,
  type ChangePasswordRequest,
  type ChangePasswordResponse,
  type DeactivateAccountRequest,
  type DeleteAccountRequest,
  type ProfileCompletenessResponse,
  type RevokeAllSessionsResponse,
  type RevokeSessionResponse,
  type Session,
  type SessionsListResponse,
  type UpdateProfileRequest,
  type UpdateUsernameRequest,
  type UpdateUsernameResponse,
  type User,
  type UserId,
  type UserRole,
} from './core/users';

// Activities
export {
  activitiesListFiltersSchema,
  activitySchema,
  createActivitySchema,
  getActorTypeTone,
  type ActivitiesListFilters,
  type Activity,
  type ActorType,
  type CreateActivity,
} from './core/activities';

// Admin (consolidated: includes security schemas)
export {
  adminActionResponseSchema,
  adminHardBanRequestSchema,
  adminHardBanResponseSchema,
  adminLockUserRequestSchema,
  adminLockUserResponseSchema,
  adminSuspendTenantRequestSchema,
  adminTenantSchema,
  adminTenantsListResponseSchema,
  adminUpdateUserRequestSchema,
  adminUpdateUserResponseSchema,
  adminUserListFiltersSchema,
  adminUserListResponseSchema,
  adminUserSchema,
  endImpersonationResponseSchema,
  formatSecurityEventType,
  getAppRoleLabel,
  getAppRoleTone,
  getSecuritySeverityTone,
  getUserStatusLabel,
  getUserStatusTone,
  impersonationResponseSchema,
  routeManifestResponseSchema,
  SECURITY_EVENT_TYPES,
  SECURITY_SEVERITIES,
  securityEventDetailRequestSchema,
  securityEventDetailResponseSchema,
  securityEventSchema,
  securityEventsExportRequestSchema,
  securityEventsExportResponseSchema,
  securityEventsFilterSchema,
  securityEventsListRequestSchema,
  securityEventsListResponseSchema,
  securityMetricsRequestSchema,
  securityMetricsResponseSchema,
  securityMetricsSchema,
  systemStatsResponseSchema,
  unlockAccountRequestSchema,
  unlockAccountResponseSchema,
  USER_STATUSES,
  userStatusSchema,
  type AdminActionResponse,
  type AdminHardBanRequest,
  type AdminHardBanResponse,
  type AdminLockUserRequest,
  type AdminLockUserResponse,
  type AdminSuspendTenantRequest,
  type AdminTenant,
  type AdminTenantsListResponse,
  type AdminUpdateUserRequest,
  type AdminUpdateUserResponse,
  type AdminUser,
  type AdminUserListFilters,
  type AdminUserListResponse,
  type EndImpersonationResponse,
  type ImpersonationResponse,
  type RouteManifestResponse,
  type SecurityEvent,
  type SecurityEventDetailRequest,
  type SecurityEventDetailResponse,
  type SecurityEventsExportRequest,
  type SecurityEventsExportResponse,
  type SecurityEventsFilter,
  type SecurityEventsListRequest,
  type SecurityEventsListResponse,
  type SecurityEventType,
  type SecurityMetrics,
  type SecurityMetricsRequest,
  type SecurityMetricsResponse,
  type SecuritySeverity,
  type SystemStatsResponse,
  type UnlockAccountRequest,
  type UnlockAccountResponse,
  type UserStatus,
} from './core/admin';

// ============================================================================
// API ROUTER & CONTRACTS
// ============================================================================

export { apiRouter, type ApiRouter } from './api';

export {
  activitiesContract,
  adminContract,
  apiKeysContract,
  auditLogContract,
  authContract,
  billingContract,
  complianceContract,
  featureFlagsContract,
  filesContract,
  healthContract,
  jobsContract,
  notificationsContract,
  realtimeContract,
  tenantContract,
  usersContract,
  webhooksContract,
} from './contracts';
