// src/shared/src/domain/realtime/index.ts

export {
  realtimeContract,
  conflictResponseSchema,
  getRecordsRequestSchema,
  getRecordsResponseSchema,
  listInsertOperationSchema,
  listPositionSchema,
  listRemoveOperationSchema,
  operationSchema,
  recordMapSchema,
  recordPointerSchema,
  recordSchema,
  setNowOperationSchema,
  setOperationSchema,
  transactionSchema,
  writeResponseSchema,
  type ConflictResponse,
  type GetRecordsRequest,
  type GetRecordsResponse,
  type ListInsertOperation,
  type ListPosition,
  type ListRemoveOperation,
  type RealtimeOperation,
  type RealtimeRecord,
  type RealtimeTransaction,
  type RecordMap,
  type RecordPointer,
  type VersionedRecord,
  type SetNowOperation,
  type SetOperation,
  type WriteResponse,
} from './realtime.schemas';

export {
  PROTECTED_FIELDS,
  REALTIME_ERRORS,
  applyOperation,
  applyOperations,
  checkVersionConflicts,
  getOperationPointers,
  isFieldMutable,
  setPath,
  type ApplyOperationsResult,
  type VersionConflict,
} from './realtime.operations';
