// src/apps/web/src/api/index.ts
// AUTO-GENERATED by scripts/generate-api-index.mjs
// Run: pnpm -C src/apps/web run api:index
export { ApiProvider, useApi } from './ApiProvider';
export * as authRoute from './auth/route';
