// main/shared/src/core/index.ts
/**
 * Core Module Barrel
 *
 * Business logic: auth, billing, users, tenant (incl. membership), notifications,
 * compliance, activities, admin, audit-log, field schemas, transactions.
 * Infrastructure (errors, envelopes, env) lives in engine/.
 */

// ============================================================================
// Auth
// ============================================================================
// Note: appRoleSchema and AppRole are exported from ./users to avoid collision.

export {
  // auth.core
  authResponseSchema,
  bffLoginResponseSchema,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema,
  isAuthenticatedRequest,
  loginRequestSchema,
  loginSuccessResponseSchema,
  logoutResponseSchema,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  sudoRequestSchema,
  sudoResponseSchema,
  type AuthResponse,
  type BffLoginResponse,
  type ForgotPasswordRequest,
  type ForgotPasswordResponse,
  type LoginRequest,
  type LoginSuccessResponse,
  type LogoutResponse,
  type RefreshResponse,
  type RegisterRequest,
  type RegisterResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type SetPasswordRequest,
  type SetPasswordResponse,
  type SudoRequest,
  type SudoResponse,
  // auth.devices
  deviceItemSchema,
  deviceListResponseSchema,
  trustDeviceResponseSchema,
  type DeviceItem,
  type DeviceListResponse,
  type TrustDeviceResponse,
  // auth.email
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  revertEmailChangeRequestSchema,
  revertEmailChangeResponseSchema,
  type ChangeEmailRequest,
  type ChangeEmailResponse,
  type ConfirmEmailChangeRequest,
  type ConfirmEmailChangeResponse,
  type EmailVerificationRequest,
  type EmailVerificationResponse,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type RevertEmailChangeRequest,
  type RevertEmailChangeResponse,
  // auth.helpers
  getRefreshCookieOptions,
  isStrategyEnabled,
  // auth.magic-link
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyRequestSchema,
  magicLinkVerifyResponseSchema,
  type MagicLinkRequest,
  type MagicLinkRequestResponse,
  type MagicLinkVerifyRequest,
  type MagicLinkVerifyResponse,
  // auth.mfa
  invalidateSessionsResponseSchema,
  removePhoneResponseSchema,
  setPhoneRequestSchema,
  setPhoneResponseSchema,
  smsChallengeRequestSchema,
  smsVerifyRequestSchema,
  totpLoginChallengeResponseSchema,
  totpLoginVerifyRequestSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpVerifyRequestSchema,
  totpVerifyResponseSchema,
  verifyPhoneRequestSchema,
  verifyPhoneResponseSchema,
  type InvalidateSessionsResponse,
  type RemovePhoneResponse,
  type SetPhoneRequest,
  type SetPhoneResponse,
  type SmsChallengeRequest,
  type SmsChallengeResponse,
  type SmsLoginChallengeResponse,
  type SmsVerifyRequest,
  type TotpLoginChallengeResponse,
  type TotpLoginVerifyRequest,
  type TotpSetupResponse,
  type TotpStatusResponse,
  type TotpVerifyRequest,
  type TotpVerifyResponse,
  type VerifyPhoneRequest,
  type VerifyPhoneResponse,
  // auth.oauth
  oauthCallbackQuerySchema,
  oauthCallbackResponseSchema,
  oauthConnectionSchema,
  oauthConnectionsResponseSchema,
  oauthEnabledProvidersResponseSchema,
  oauthInitiateResponseSchema,
  oauthLinkCallbackResponseSchema,
  oauthLinkResponseSchema,
  oauthProviderSchema,
  oauthUnlinkResponseSchema,
  type OAuthCallbackQuery,
  type OAuthCallbackResponse,
  type OAuthConnection,
  type OAuthConnectionsResponse,
  type OAuthEnabledProvidersResponse,
  type OAuthInitiateResponse,
  type OAuthLinkCallbackResponse,
  type OAuthLinkResponse,
  type OAuthProvider,
  type OAuthUnlinkResponse,
  // auth.passkey
  passkeyListResponseSchema,
  renamePasskeyRequestSchema,
  type PasskeyListItem,
  type RenamePasskeyRequest,
  // auth.tos
  acceptTosRequestSchema,
  acceptTosResponseSchema,
  tosStatusResponseSchema,
  type AcceptTosRequest,
  type AcceptTosResponse,
  type TosStatusResponse,
  // auth.webauth
  webauthnLoginOptionsRequestSchema,
  webauthnLoginVerifyRequestSchema,
  webauthnOptionsResponseSchema,
  webauthnRegisterVerifyRequestSchema,
  webauthnRegisterVerifyResponseSchema,
  type WebauthnLoginOptionsRequest,
  type WebauthnLoginVerifyRequest,
  type WebauthnOptionsResponse,
  type WebauthnRegisterVerifyRequest,
  type WebauthnRegisterVerifyResponse,
  // passwords
  defaultPasswordConfig,
  getStrengthColor,
  getStrengthLabel,
  validatePassword,
  validatePasswordBasic,
  estimatePasswordStrength,
  calculateEntropy,
  calculateScore,
  estimateCrackTime,
  generateFeedback,
  getCharsetSize,
  containsUserInput,
  hasKeyboardPattern,
  hasRepeatedChars,
  hasSequentialChars,
  isCommonPassword,
  type PasswordConfig,
  type PasswordValidationResult,
  type StrengthResult,
  type PasswordPenalties,
  // auth errors (re-exported from engine/errors)
  AccountLockedError,
  EmailAlreadyExistsError,
  EmailNotVerifiedError,
  EmailSendError,
  InvalidCredentialsError,
  InvalidTokenError,
  OAuthError,
  OAuthStateMismatchError,
  TokenReuseError,
  TotpInvalidError,
  TotpRequiredError,
  UserNotFoundError,
  WeakPasswordError,
  // sessions
  getSessionAge,
  isSessionActive,
  isSessionRevoked,
  createUserSessionSchema,
  updateUserSessionSchema,
  userSessionSchema,
  type CreateUserSession,
  type UpdateUserSession,
  type UserSession,
  // roles (appRoleSchema, AppRole come from users)
  permissionSchema,
  tenantRoleSchema,
  type Permission,
  type TenantRole,
  // policy
  can,
  hasPermission,
  type AuthContext,
  type PolicyAction,
  type PolicyResource,
} from './auth';

// ============================================================================
// Users
// ============================================================================

export {
  ACCOUNT_DELETION_GRACE_PERIOD_DAYS,
  accountLifecycleResponseSchema,
  APP_ROLES,
  appRoleSchema,
  avatarDeleteResponseSchema,
  avatarUploadRequestSchema,
  avatarUploadResponseSchema,
  calculateDeletionGracePeriodEnd,
  canDeactivate,
  canReactivate,
  canRequestDeletion,
  canUser,
  changePasswordRequestSchema,
  changePasswordResponseSchema,
  deactivateAccountRequestSchema,
  deleteAccountRequestSchema,
  getAllRoles,
  getAccountStatus,
  getNextUsernameChangeDate,
  getRoleDisplayName,
  hasRole,
  isAccountActive,
  isAccountDeactivated,
  isAccountPendingDeletion,
  isAdmin,
  isModerator,
  isOwner,
  isRegularUser,
  isUser,
  isUsernameChangeCooldownActive,
  isWithinDeletionGracePeriod,
  profileCompletenessResponseSchema,
  RESERVED_USERNAMES,
  revokeAllSessionsResponseSchema,
  revokeSessionResponseSchema,
  sessionCountResponseSchema,
  sessionSchema,
  sessionsListResponseSchema,
  updateProfileRequestSchema,
  updateUsernameRequestSchema,
  updateUsernameResponseSchema,
  USER_ROLES,
  userIdSchema,
  USERNAME_CHANGE_COOLDOWN_DAYS,
  userRoleSchema,
  userSchema,
  usersListResponseSchema,
  type AccountLifecycleFields,
  type AccountLifecycleResponse,
  type AccountStatus,
  type AppRole,
  type AvatarDeleteResponse,
  type AvatarUploadRequest,
  type AvatarUploadResponse,
  type ChangePasswordRequest,
  type ChangePasswordResponse,
  type DeactivateAccountRequest,
  type DeleteAccountRequest,
  type ProfileCompletenessResponse,
  type RevokeAllSessionsResponse,
  type RevokeSessionResponse,
  type Session,
  type SessionCountResponse,
  type SessionsListResponse,
  type UpdateProfileRequest,
  type UpdateUsernameRequest,
  type UpdateUsernameResponse,
  type User,
  type UserId,
  type UserRole,
  type UsersListResponse,
} from './users';

// ============================================================================
// Billing
// ============================================================================

export {
  addPaymentMethodRequestSchema,
  adminBillingStatsSchema,
  adminPlanResponseSchema,
  adminPlanSchema,
  adminPlansListResponseSchema,
  assertEntitled,
  assertWithinLimit,
  BILLING_EVENT_TYPES,
  BILLING_PROVIDERS,
  BillingProviderError,
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError,
  calculateProration,
  cancelSubscriptionRequestSchema,
  CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError,
  cardDetailsSchema,
  checkoutRequestSchema,
  checkoutResponseSchema,
  CheckoutSessionError,
  createPlanRequestSchema,
  CustomerNotFoundError,
  FEATURE_KEYS,
  formatPlanInterval,
  formatPrice,
  formatPriceWithInterval,
  getCardBrandLabel,
  getInvoiceStatusLabel,
  getInvoiceStatusVariant,
  getPaymentMethodIcon,
  getPaymentMethodLabel,
  getSubscriptionStatusLabel,
  getSubscriptionStatusVariant,
  hasActiveSubscription,
  InvoiceNotFoundError,
  invoiceResponseSchema,
  invoiceSchema,
  invoicesListResponseSchema,
  INVOICE_STATUSES,
  isBillingProviderError,
  isEntitled,
  isPlanError,
  isSubscriptionError,
  PaymentMethodNotFoundError,
  paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema,
  PAYMENT_METHOD_TYPES,
  PaymentMethodValidationError,
  PLAN_FEES,
  PLAN_INTERVALS,
  planFeatureSchema,
  PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  PlanNotFoundError,
  planSchema,
  plansListResponseSchema,
  portalSessionRequestSchema,
  portalSessionResultSchema,
  resolveEntitlements,
  setupIntentResponseSchema,
  subscriptionActionResponseSchema,
  SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError,
  SUBSCRIPTION_STATUSES,
  subscriptionResponseSchema,
  subscriptionSchema,
  syncStripeResponseSchema,
  updatePlanRequestSchema,
  updateSubscriptionRequestSchema,
  WebhookEventAlreadyProcessedError,
  WebhookSignatureError,
  type AddPaymentMethodRequest,
  type AdminBillingStats,
  type AdminPlan,
  type AdminPlanResponse,
  type AdminPlansListResponse,
  type BillingEventType,
  type BillingProvider,
  type BillingService,
  type BillingStats,
  type CancelSubscriptionRequest,
  type CardDetails,
  type CheckoutParams,
  type CheckoutRequest,
  type CheckoutResponse,
  type CheckoutResult,
  type CreatePlanRequest,
  type CreateProductParams,
  type CreateProductResult,
  type EntitlementInput,
  type FeatureEntitlement,
  type FeatureKey,
  type Invoice,
  type InvoiceResponse,
  type InvoiceStatus,
  type InvoicesListResponse,
  type NormalizedEventType,
  type NormalizedWebhookEvent,
  type PaymentMethod,
  type PaymentMethodResponse,
  type PaymentMethodsListResponse,
  type PaymentMethodType,
  type Plan,
  type PlanFeature,
  type PlanId,
  type PlanInterval,
  type PlansListResponse,
  type PortalSessionParams,
  type PortalSessionRequest,
  type PortalSessionResult,
  type ProviderInvoice,
  type ProviderPaymentMethod,
  type ProviderSubscription,
  type ResolvedEntitlements,
  type SetupIntentResponse,
  type SetupIntentResult,
  type StatusVariant,
  type Subscription,
  type SubscriptionActionResponse,
  type SubscriptionId,
  type SubscriptionResponse,
  type SubscriptionState,
  type SubscriptionStatus,
  type SyncStripeResponse,
  type UpdatePlanRequest,
  type UpdateSubscriptionRequest,
} from './billing';

// ============================================================================
// Tenant
// ============================================================================
// Note: isAdmin, isOwner are exported from ./users to avoid collision.

export {
  assertWorkspaceScope,
  createTenantSchema,
  createTenantSettingSchema,
  createWorkspaceContext,
  extractEmailDomain,
  getWorkspaceContext,
  hasRequiredWorkspaceRole,
  isEmailDomainAllowed,
  isWorkspaceScoped,
  tenantSchema,
  tenantSettingSchema,
  transferOwnershipSchema,
  updateTenantSchema,
  updateTenantSettingSchema,
  WORKSPACE_ID_HEADER,
  WORKSPACE_ROLE_HEADER,
  type CreateTenantInput,
  type CreateTenantSetting,
  type MaybeWorkspaceContext,
  type Tenant,
  type TenantSetting,
  type TransferOwnershipInput,
  type UpdateTenantInput,
  type UpdateTenantSetting,
  type WorkspaceContext,
} from './tenant';

// ============================================================================
// Membership (colocated in tenant/)
// ============================================================================

export {
  acceptInvitationSchema,
  addMemberSchema,
  canAcceptInvite,
  canAssignRole,
  canChangeRole,
  canLeave,
  canRemoveMember,
  canRevokeInvite,
  createInvitationSchema,
  getInvitationStatusTone,
  getNextOwnerCandidate,
  getRoleLevel,
  getTenantRoleTone,
  hasAtLeastRole,
  INVITATION_STATUSES,
  invitationSchema,
  isInviteExpired,
  isSoleOwner,
  membershipSchema,
  ROLE_LEVELS,
  updateMembershipRoleSchema,
  type AcceptInvitation,
  type AddMember,
  type CreateInvitation,
  type Invitation,
  type InvitationStatus,
  type Membership,
  type UpdateMembershipRole,
} from './tenant';

// ============================================================================
// Notifications
// ============================================================================

export {
  baseMarkAsReadRequestSchema,
  DEFAULT_NOTIFICATION_PREFERENCES,
  deleteNotificationResponseSchema,
  getNotificationLevelTone,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  markReadResponseSchema,
  NOTIFICATION_LEVELS,
  NOTIFICATION_PAYLOAD_MAX_SIZE,
  NOTIFICATION_TYPES,
  notificationDeleteRequestSchema,
  notificationPreferencesSchema,
  NotificationRateLimitError,
  notificationSchema,
  NotificationsDisabledError,
  NotificationSendError,
  notificationsListRequestSchema,
  notificationsListResponseSchema,
  PayloadTooLargeError,
  PreferencesNotFoundError,
  preferencesResponseSchema,
  ProviderError,
  ProviderNotConfiguredError,
  PushProviderNotConfiguredError,
  PushSubscriptionExistsError,
  PushSubscriptionNotFoundError,
  QuietHoursActiveError,
  sendNotificationRequestSchema,
  sendNotificationResponseSchema,
  shouldSendNotification,
  subscribeRequestSchema,
  subscribeResponseSchema,
  SubscriptionExistsError,
  SubscriptionExpiredError,
  SubscriptionNotFoundError,
  unsubscribeRequestSchema,
  unsubscribeResponseSchema,
  updatePreferencesRequestSchema,
  vapidKeyResponseSchema,
  VapidNotConfiguredError,
  type BaseMarkAsReadRequest,
  type BatchSendResult,
  type DeleteNotificationResponse,
  type MarkReadResponse,
  type Notification,
  type NotificationAction,
  type NotificationChannel,
  type NotificationDeleteRequest,
  type NotificationLevel,
  type NotificationMessage,
  type NotificationPayload,
  type NotificationPreferences,
  type NotificationPreferencesConfig,
  type NotificationPriority,
  type NotificationsListRequest,
  type NotificationsListResponse,
  type NotificationType,
  type NotificationTypePreference,
  type PreferencesResponse,
  type PushSendResult,
  type PushSubscription,
  type PushSubscriptionKeys,
  type SendNotificationRequest,
  type SendNotificationResponse,
  type StoredPushSubscription,
  type SubscribeRequest,
  type SubscribeResponse,
  type UnsubscribeRequest,
  type UnsubscribeResponse,
  type UpdatePreferencesRequest,
  type VapidKeyResponse,
} from './notifications';

// ============================================================================
// Compliance
// ============================================================================

export {
  calculateHardDeleteDate,
  CONSENT_TYPES,
  consentLogSchema,
  createConsentLogSchema,
  createDataExportRequestSchema,
  createLegalDocumentSchema,
  createUserAgreementSchema,
  DATA_EXPORT_STATUSES,
  DATA_EXPORT_TYPES,
  dataExportRequestSchema,
  DEFAULT_DELETION_CONFIG,
  DEFAULT_GRACE_PERIOD_DAYS,
  DELETION_STATES,
  deletionRequestSchema,
  DOCUMENT_TYPES,
  getEffectiveConsent,
  isConsentGranted,
  isSoftDeleted,
  isWithinGracePeriod,
  legalDocumentSchema,
  needsReacceptance,
  updateConsentPreferencesRequestSchema,
  updateLegalDocumentSchema,
  userAgreementSchema,
  type ConsentLog,
  type ConsentType,
  type CreateConsentLog,
  type CreateDataExportRequest,
  type CreateLegalDocument,
  type CreateUserAgreement,
  type DataExportRequest,
  type DataExportStatus,
  type DataExportType,
  type DeletionConfig,
  type DeletionJob,
  type DeletionRequest,
  type DeletionServiceContract,
  type DeletionState,
  type DocumentType,
  type LegalDocument,
  type SoftDeletable,
  type UpdateConsentPreferencesRequest,
  type UpdateLegalDocument,
  type UserAgreement,
} from './compliance';

// ============================================================================
// Activities
// ============================================================================

export {
  ACTOR_TYPES,
  activitySchema,
  actorTypeSchema,
  createActivitySchema,
  getActorTypeTone,
  type Activity,
  type ActorType,
  type CreateActivity,
} from './activities';

// ============================================================================
// Admin
// ============================================================================

export {
  adminActionResponseSchema,
  adminHardBanRequestSchema,
  adminHardBanResponseSchema,
  adminLockUserRequestSchema,
  adminLockUserResponseSchema,
  adminSuspendTenantRequestSchema,
  adminTenantSchema,
  adminTenantsListResponseSchema,
  adminUpdateUserRequestSchema,
  adminUpdateUserResponseSchema,
  adminUserListFiltersSchema,
  adminUserListResponseSchema,
  adminUserSchema,
  endImpersonationResponseSchema,
  formatSecurityEventType,
  getAppRoleLabel,
  getAppRoleTone,
  getSecuritySeverityTone,
  getUserStatusLabel,
  getUserStatusTone,
  impersonationResponseSchema,
  routeManifestResponseSchema,
  SECURITY_EVENT_TYPES,
  SECURITY_SEVERITIES,
  securityEventDetailRequestSchema,
  securityEventDetailResponseSchema,
  securityEventSchema,
  securityEventsExportRequestSchema,
  securityEventsExportResponseSchema,
  securityEventsFilterSchema,
  securityEventsListRequestSchema,
  securityEventsListResponseSchema,
  securityMetricsRequestSchema,
  securityMetricsResponseSchema,
  securityMetricsSchema,
  systemStatsResponseSchema,
  unlockAccountRequestSchema,
  unlockAccountResponseSchema,
  USER_STATUSES,
  userStatusSchema,
  type AdminActionResponse,
  type AdminHardBanRequest,
  type AdminHardBanResponse,
  type AdminLockUserRequest,
  type AdminLockUserResponse,
  type AdminSuspendTenantRequest,
  type AdminTenant,
  type AdminTenantsListResponse,
  type AdminUpdateUserRequest,
  type AdminUpdateUserResponse,
  type AdminUser,
  type AdminUserListFilters,
  type AdminUserListResponse,
  type EndImpersonationResponse,
  type ImpersonationResponse,
  type RouteManifestResponse,
  type SecurityEvent,
  type SecurityEventDetailRequest,
  type SecurityEventDetailResponse,
  type SecurityEventType,
  type SecurityEventsExportRequest,
  type SecurityEventsExportResponse,
  type SecurityEventsFilter,
  type SecurityEventsListRequest,
  type SecurityEventsListResponse,
  type SecurityMetrics,
  type SecurityMetricsRequest,
  type SecurityMetricsResponse,
  type SecuritySeverity,
  type SystemStatsResponse,
  type UnlockAccountRequest,
  type UnlockAccountResponse,
  type UserStatus,
} from './admin';

// ============================================================================
// Audit Log
// ============================================================================

export {
  AUDIT_ACTION_REGEX,
  AUDIT_CATEGORIES,
  AUDIT_SEVERITIES,
  auditEventSchema,
  auditLogFilterSchema,
  auditLogListResponseSchema,
  buildAuditEvent,
  createAuditEventSchema,
  getAuditActionTone,
  getAuditSeverityTone,
  sanitizeMetadata,
  type AuditBuilderParams,
  type AuditCategory,
  type AuditEvent,
  type AuditLogFilter,
  type AuditLogListResponse,
  type AuditSeverity,
  type CreateAuditEvent,
} from './audit-log';

// ============================================================================
// Field Validation Schemas
// ============================================================================

export {
  bioSchema,
  dateOfBirthSchema,
  emailSchema,
  firstNameSchema,
  genderSchema,
  identifierSchema,
  isoDateTimeSchema,
  lastNameSchema,
  nameSchema,
  optionalShortTextSchema,
  passwordSchema,
  phoneSchema,
  requiredNameSchema,
  usernameSchema,
  uuidSchema,
  websiteSchema,
} from './schemas';

// ============================================================================
// Transactions (undo/redo)
// ============================================================================

export {
  createListInsertOperation,
  createListRemoveOperation,
  createSetOperation,
  createTransaction,
  invertOperation,
  invertTransaction,
  isListInsertOperation,
  isListRemoveOperation,
  isSetOperation,
  mergeTransactions,
  type ListInsertOperation,
  type ListRemoveOperation,
  type Operation,
  type SetOperation,
  type Transaction,
} from './transactions';

// ============================================================================
// Constants (unique to core/constants, not in domain modules above)
// ============================================================================

export { COMMON_PASSWORDS, KEYBOARD_PATTERNS, OAUTH_PROVIDERS } from './constants';
