// main/shared/src/core/index.ts

// Engine layer: base classes, HTTP errors, utilities
import {
  AppError,
  BadRequestError,
  BaseError,
  ConfigurationError,
  ConflictError,
  ForbiddenError,
  formatValidationErrors,
  getErrorStatusCode,
  getSafeErrorMessage,
  InternalError,
  InternalServerError,
  isAppError,
  NotFoundError,
  ResourceNotFoundError,
  toAppError,
  TooManyRequestsError,
  UnauthorizedError,
  UnprocessableError,
  ValidationError,
  type AppErrorInfo,
  type ValidationErrorDetail,
  type ValidationErrorResponse,
  type ValidationIssue,
} from '../engine/errors';

export {
  AppError,
  BadRequestError,
  BaseError,
  ConfigurationError,
  ConflictError,
  ForbiddenError,
  formatValidationErrors,
  getErrorStatusCode,
  getSafeErrorMessage,
  InternalError,
  InternalServerError,
  isAppError,
  NotFoundError,
  ResourceNotFoundError,
  toAppError,
  TooManyRequestsError,
  UnauthorizedError,
  UnprocessableError,
  ValidationError,
  type AppErrorInfo,
  type ValidationErrorDetail,
  type ValidationErrorResponse,
  type ValidationIssue,
};

// Auth layer: domain-specific errors
export {
  EmailAlreadyExistsError,
  EmailNotVerifiedError,
  InvalidCredentialsError,
  InvalidTokenError,
  OAuthError,
  OAuthStateMismatchError,
  TokenReuseError,
  TotpInvalidError,
  TotpRequiredError,
  UserNotFoundError,
  WeakPasswordError,
} from './auth';

export {
  can,
  hasPermission,
  type AuthContext,
  type PolicyAction,
  type PolicyResource,
} from './policy';

export { baseEnvSchema, getRawEnv, validateEnv, type BaseEnv } from './env';

export {
  apiResultSchema,
  bioSchema,
  createErrorCodeSchema,
  dateOfBirthSchema,
  emailSchema,
  emptyBodySchema,
  envelopeErrorResponseSchema,
  errorCodeSchema,
  errorResponseSchema,
  firstNameSchema,
  genderSchema,
  identifierSchema,
  isoDateTimeSchema,
  lastNameSchema,
  nameSchema,
  optionalShortTextSchema,
  passwordSchema,
  phoneSchema,
  requiredNameSchema,
  successResponseSchema,
  usernameSchema,
  uuidSchema,
  websiteSchema,
  type ApiResultEnvelope,
  type EmptyBody,
  type ErrorResponseEnvelope,
  type SuccessResponseEnvelope,
} from './schemas';

export {
  createListInsertOperation,
  createListRemoveOperation,
  createSetOperation,
  createTransaction,
  invertOperation,
  invertTransaction,
  isListInsertOperation,
  isListRemoveOperation,
  isSetOperation,
  mergeTransactions,
  type ListInsertOperation,
  type ListRemoveOperation,
  type Operation,
  type SetOperation,
  type Transaction,
} from './transactions';
