// main/apps/web/src/features/workspace/index.ts

// Components
export {
  AuditEventDetailModal,
  Can,
  CreateWorkspaceDialog,
  DomainAllowlistEditor,
  InvitationsList,
  InviteMemberDialog,
  MemberDetailPanel,
  MembersList,
  RequireWorkspaceRole,
  meetsRoleRequirement,
  TenantSwitcher,
  WebhookDetailView,
  WebhookManagement,
  WorkspaceAuditLog,
  WorkspaceBilling,
  WorkspaceDangerZone,
  WorkspaceFeatureOverrides,
  WorkspaceList,
  WorkspaceLogoUpload,
  WorkspaceSettingsForm,
  WorkspaceWelcomeBanner,
} from './components';
export type {
  AuditEventDetailModalProps,
  CanProps,
  CreateWorkspaceDialogProps,
  DomainAllowlistEditorProps,
  InvitationsListProps,
  InviteMemberDialogProps,
  MemberDetail,
  MemberDetailPanelProps,
  MembersListProps,
  RequireWorkspaceRoleProps,
  TenantSwitcherProps,
  WebhookDetailViewProps,
  WebhookManagementProps,
  WorkspaceAuditLogProps,
  WorkspaceBillingProps,
  WorkspaceDangerZoneProps,
  WorkspaceFeatureOverridesProps,
  WorkspaceListProps,
  WorkspaceLogoUploadProps,
  WorkspaceSettingsFormProps,
  WorkspaceWelcomeBannerProps,
} from './components';

// Hooks
export {
  useAuditLog,
  useAcceptInvitation,
  useCreateInvitation,
  useInvitations,
  useResendInvitation,
  useRevokeInvitation,
  useMembers,
  useRemoveMember,
  useUpdateMemberRole,
  usePermissions,
  useWorkspace,
  useWorkspaceBilling,
  useWorkspaceContext,
  useSetFeatureOverride,
  useWorkspaceFeatureOverrides,
  useCreateWorkspace,
  useDeleteWorkspace,
  useUpdateWorkspace,
  useWorkspaces,
} from './hooks';
export type {
  AuditEvent,
  AuditEventsResponse,
  UseAuditLogResult,
  UseAcceptInvitationResult,
  UseCreateInvitationResult,
  UseInvitationsResult,
  UseResendInvitationResult,
  UseRevokeInvitationResult,
  UseMembersResult,
  UseRemoveMemberResult,
  UseUpdateMemberRoleResult,
  PermissionsResult,
  UsePermissionsOptions,
  UseWorkspaceResult,
  Plan,
  Subscription,
  SubscriptionResponse,
  UseWorkspaceBillingOptions,
  UseWorkspaceBillingResult,
  UseWorkspaceContextResult,
  FlagWithOverride,
  SetOverrideRequest,
  TenantOverride,
  TenantOverridesResponse,
  UseSetFeatureOverrideOptions,
  UseSetFeatureOverrideResult,
  UseWorkspaceFeatureOverridesOptions,
  UseWorkspaceFeatureOverridesResult,
  UseCreateWorkspaceOptions,
  UseCreateWorkspaceResult,
  UseDeleteWorkspaceOptions,
  UseDeleteWorkspaceResult,
  UseUpdateWorkspaceOptions,
  UseUpdateWorkspaceResult,
  UseWorkspacesResult,
} from './hooks';

// Pages
export { AcceptInvitationPage, WorkspaceDetailPage, WorkspaceListPage } from './pages';

// API
export { createWorkspaceApi } from './api';
export type { WorkspaceApi, WorkspaceApiConfig } from './api';
