// main/apps/web/src/features/admin/index.ts
/**
 * Admin Feature
 *
 * Admin-only features for security auditing and system management.
 */

// Layouts
export { AdminLayout } from './layouts';

// Components
export {
  ActiveConnectionsWidget,
  CreateWebhookDialog,
  ExportDialog,
  FeatureFlagOverrideTable,
  HealthStatusCard,
  JobActionsMenu,
  JobDetailsPanel,
  JobQueueStatsWidget,
  JobsTable,
  JobStatusBadge,
  PlanOverrideSelector,
  QueueStatsCard,
  RecentErrorLogWidget,
  RoleBadge,
  SecurityEventCard,
  SecurityEventsFilters,
  SecurityEventsTable,
  SecurityMetricsCard,
  getUserStatus,
  StatusBadge,
  UserActionsMenu,
  UserDetailCard,
  UserFilters,
  UserTable,
  WebhookDeliveryRow,
  WebhookStatusBadge,
} from './components';
export type {
  ActiveConnectionsWidgetProps,
  CreateWebhookDialogProps,
  DeliveryRowData,
  ExportDialogProps,
  FeatureFlagOverrideTableProps,
  HealthStatusCardProps,
  JobActionsMenuProps,
  JobDetailsPanelProps,
  JobQueueStatsWidgetProps,
  JobsTableProps,
  JobStatusBadgeProps,
  PlanOverrideSelectorProps,
  QueueStatsCardProps,
  RecentErrorLogWidgetProps,
  RoleBadgeProps,
  SecurityEventCardProps,
  SecurityEventsFiltersProps,
  SecurityEventsTableProps,
  SecurityMetricsCardProps,
  StatusBadgeProps,
  UserActionsMenuProps,
  UserDetailCardProps,
  UserFiltersProps,
  UserTableProps,
  WebhookDeliveryRowProps,
  WebhookStatus,
  WebhookStatusBadgeProps,
} from './components';

// Hooks
export {
  useAdminUser,
  useAdminUsers,
  useAdminErrorLog,
  useAdminHealth,
  useAdminMetrics,
  useAuditEvents,
  useExportEvents,
  useFeatureFlag,
  useCreateFeatureFlag,
  useDeleteFeatureFlag,
  useFeatureFlags,
  useUpdateFeatureFlag,
  useDeleteFeatureFlagOverride,
  useFeatureFlagOverrides,
  useSetFeatureFlagOverride,
  useJobActions,
  useJobDetails,
  useJobsList,
  useQueueStats,
  useRouteManifest,
  useSecurityEvent,
  useSecurityEvents,
  useSecurityMetrics,
  useTenantPlanAssignment,
  useUserActions,
  useAdminCreateWebhook,
  useAdminDeleteWebhook,
  useAdminReplayDelivery,
  useAdminRotateWebhookSecret,
  useAdminUpdateWebhook,
  useAdminWebhook,
  useAdminWebhookDeliveries,
  useAdminWebhooks,
  useWebhookMonitor,
  useWebhookMonitorDeliveries,
} from './hooks';
export type {
  UseAdminUserResult,
  UseAdminUserState,
  UseAdminUsersActions,
  UseAdminUsersResult,
  UseAdminUsersState,
  UseAdminErrorLogOptions,
  UseAdminErrorLogResult,
  UseAdminHealthOptions,
  UseAdminHealthResult,
  UseAdminMetricsOptions,
  UseAdminMetricsResult,
  UseAuditEventsOptions,
  UseAuditEventsResult,
  UseExportEventsResult,
  UseFeatureFlagOptions,
  UseFeatureFlagResult,
  UseCreateFeatureFlagOptions,
  UseCreateFeatureFlagResult,
  UseDeleteFeatureFlagOptions,
  UseDeleteFeatureFlagResult,
  UseDeleteFeatureFlagOverrideOptions,
  UseDeleteFeatureFlagOverrideResult,
  UseFeatureFlagsOptions,
  UseFeatureFlagsResult,
  UseFeatureFlagOverridesOptions,
  UseFeatureFlagOverridesResult,
  UseSetFeatureFlagOverrideOptions,
  UseSetFeatureFlagOverrideResult,
  UseUpdateFeatureFlagOptions,
  UseUpdateFeatureFlagResult,
  UseJobActionsResult,
  UseJobDetailsOptions,
  UseJobDetailsResult,
  JobsFilter,
  JobsPagination,
  UseJobsListOptions,
  UseJobsListResult,
  UseQueueStatsOptions,
  UseQueueStatsResult,
  UseRouteManifestOptions,
  UseRouteManifestResult,
  UseSecurityEventOptions,
  UseSecurityEventResult,
  UseSecurityEventsOptions,
  UseSecurityEventsResult,
  MetricsPeriod,
  UseSecurityMetricsOptions,
  UseSecurityMetricsResult,
  UseTenantPlanAssignmentOptions,
  UseTenantPlanAssignmentResult,
  UseUserActionsResult,
  UseUserActionsState,
  UseWebhookMonitorOptions,
  UseWebhookMonitorResult,
  UseWebhookMonitorDeliveriesOptions,
  UseWebhookMonitorDeliveriesResult,
} from './hooks';

// Pages
export {
  AuditEventsPage,
  FeatureFlagsPage,
  JobMonitorPage,
  PlanManagementPage,
  RouteManifestPage,
  SecurityEventDetailPage,
  SecurityEventsPage,
  SystemHealthPage,
  TenantDetailPage,
  TenantListPage,
  UserDetailPage,
  UserListPage,
  WebhookDetailPage,
  WebhookListPage,
  WebhookMonitorPage,
} from './pages';

// Services
export { createAdminApiClient } from './services';
export type { AdminApiClient, AdminApiConfig } from './services';
