// packages/shared/src/domain/index.ts

export {
  buildAuditEvent,
  sanitizeMetadata,
  AUDIT_ACTION_REGEX,
  AUDIT_CATEGORIES,
  AUDIT_SEVERITIES,
  auditEventSchema,
  auditLogFilterSchema,
  auditLogListResponseSchema,
  createAuditEventSchema,
  type AuditBuilderParams,
  type AuditCategory,
  type AuditEvent,
  type AuditLogFilter,
  type AuditLogListResponse,
  type AuditSeverity,
  type CreateAuditEvent,
} from './audit-log';

export {
  validatePassword,
  authContract,
  AUTH_ERROR_MESSAGES,
  AUTH_SUCCESS_MESSAGES,
  AccountLockedError,
  EmailSendError,
  HTTP_ERROR_MESSAGES,
  isKnownAuthError,
  mapErrorToHttpResponse,
  authResponseSchema,
  changeEmailRequestSchema,
  changeEmailResponseSchema,
  confirmEmailChangeRequestSchema,
  confirmEmailChangeResponseSchema,
  emailVerificationRequestSchema,
  emailVerificationResponseSchema,
  forgotPasswordRequestSchema,
  forgotPasswordResponseSchema,
  loginRequestSchema,
  logoutResponseSchema,
  magicLinkRequestResponseSchema,
  magicLinkRequestSchema,
  magicLinkVerifyRequestSchema,
  magicLinkVerifyResponseSchema,
  refreshResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  resendVerificationRequestSchema,
  resendVerificationResponseSchema,
  resetPasswordRequestSchema,
  resetPasswordResponseSchema,
  setPasswordRequestSchema,
  setPasswordResponseSchema,
  totpSetupResponseSchema,
  totpStatusResponseSchema,
  totpVerifyRequestSchema,
  totpVerifyResponseSchema,
  type ErrorMapperLogger,
  type ErrorMapperOptions,
  type ErrorStatusCode,
  type HttpErrorResponse,
  type AuthResponse,
  type ChangeEmailRequest,
  type ChangeEmailResponse,
  type ConfirmEmailChangeRequest,
  type ConfirmEmailChangeResponse,
  type EmailVerificationRequest,
  type EmailVerificationResponse,
  type ForgotPasswordRequest,
  type ForgotPasswordResponse,
  type LoginRequest,
  type LogoutResponse,
  type MagicLinkRequest,
  type MagicLinkRequestResponse,
  type MagicLinkVerifyRequest,
  type MagicLinkVerifyResponse,
  type RefreshResponse,
  type RegisterRequest,
  type RegisterResponse,
  type ResendVerificationRequest,
  type ResendVerificationResponse,
  type ResetPasswordRequest,
  type ResetPasswordResponse,
  type SetPasswordRequest,
  type SetPasswordResponse,
  type TotpSetupResponse,
  type TotpStatusResponse,
  type TotpVerifyRequest,
  type TotpVerifyResponse,
} from './auth';

export {
  PLAN_FEES,
  calculateProration,
  billingContract,
  BILLING_PROVIDERS,
  FEATURE_KEYS,
  INVOICE_STATUSES,
  PAYMENT_METHOD_TYPES,
  PLAN_INTERVALS,
  SUBSCRIPTION_STATUSES,
  addPaymentMethodRequestSchema,
  cancelSubscriptionRequestSchema,
  cardDetailsSchema,
  checkoutRequestSchema,
  checkoutResponseSchema,
  invoiceSchema,
  invoicesListResponseSchema,
  paymentMethodResponseSchema,
  paymentMethodSchema,
  paymentMethodsListResponseSchema,
  planFeatureSchema,
  planSchema,
  plansListResponseSchema,
  setupIntentResponseSchema,
  subscriptionActionResponseSchema,
  subscriptionResponseSchema,
  subscriptionSchema,
  updateSubscriptionRequestSchema,
  adminBillingStatsSchema,
  adminPlansListResponseSchema,
  createPlanRequestSchema,
  updatePlanRequestSchema,
  BillingProviderError,
  BillingProviderNotConfiguredError,
  BillingSubscriptionExistsError,
  BillingSubscriptionNotFoundError,
  CannotDeactivatePlanWithActiveSubscriptionsError,
  CannotDowngradeInTrialError,
  CannotRemoveDefaultPaymentMethodError,
  CheckoutSessionError,
  CustomerNotFoundError,
  InvoiceNotFoundError,
  isBillingProviderError,
  isPlanError,
  isSubscriptionError,
  PaymentMethodNotFoundError,
  PaymentMethodValidationError,
  PlanHasActiveSubscriptionsError,
  PlanNotActiveError,
  PlanNotFoundError,
  SubscriptionAlreadyCanceledError,
  SubscriptionNotActiveError,
  SubscriptionNotCancelingError,
  WebhookEventAlreadyProcessedError,
  WebhookSignatureError,
  type BillingStats,
  type BillingProvider,
  type AddPaymentMethodRequest,
  type CancelSubscriptionRequest,
  type CardDetails,
  type CheckoutRequest,
  type CheckoutResponse,
  type FeatureKey,
  type Invoice,
  type InvoiceStatus,
  type InvoicesListResponse,
  type PaymentMethod,
  type PaymentMethodResponse,
  type PaymentMethodType,
  type PaymentMethodsListResponse,
  type Plan,
  type PlanFeature,
  type PlanInterval,
  type PlansListResponse,
  type SetupIntentResponse,
  type Subscription,
  type SubscriptionActionResponse,
  type SubscriptionResponse,
  type SubscriptionStatus,
  type UpdateSubscriptionRequest,
  type AdminBillingStats,
  type AdminPlansListResponse,
  type CreatePlanRequest,
  type UpdatePlanRequest,
} from './billing';

export {
  getEffectiveConsent,
  isConsentGranted,
  needsReacceptance,
  CONSENT_TYPES,
  consentLogSchema,
  createConsentLogSchema,
  createLegalDocumentSchema,
  createUserAgreementSchema,
  DOCUMENT_TYPES,
  legalDocumentSchema,
  updateLegalDocumentSchema,
  userAgreementSchema,
  type ConsentLog,
  type ConsentType,
  type CreateConsentLog,
  type CreateLegalDocument,
  type CreateUserAgreement,
  type DocumentType,
  type LegalDocument,
  type UpdateLegalDocument,
  type UserAgreement,
} from './compliance';

export {
  evaluateFlag,
  featureFlagSchema,
  tenantFeatureOverrideSchema,
  type FeatureFlag,
  type TenantFeatureOverride,
} from './feature-flags';

export {
  calculateBackoff,
  canRetry,
  isTerminalStatus,
  shouldProcess,
  createJobSchema,
  JOB_PRIORITIES,
  JOB_PRIORITY_VALUES,
  JOB_STATUSES,
  jobSchema,
  updateJobSchema,
  type CreateJob,
  type DomainJob,
  type JobPriority,
  type JobStatus,
  type UpdateJob,
} from './jobs';

export {
  canAcceptInvite,
  canRevokeInvite,
  hasAtLeastRole,
  isInviteExpired,
  INVITATION_STATUSES,
  acceptInvitationSchema,
  createInvitationSchema,
  invitationSchema,
  membershipSchema,
  updateMembershipRoleSchema,
  type AcceptInvitation,
  type CreateInvitation,
  type Invitation,
  type InvitationStatus,
  type Membership,
  type UpdateMembershipRole,
} from './membership';

export {
  shouldSendNotification,
  baseMarkAsReadRequestSchema,
  NOTIFICATION_TYPES,
  notificationPreferencesSchema,
  notificationSchema,
  notificationsListRequestSchema,
  notificationsListResponseSchema,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  NotificationRateLimitError,
  NotificationSendError,
  NotificationsDisabledError,
  PayloadTooLargeError,
  PreferencesNotFoundError,
  ProviderError,
  PushProviderNotConfiguredError,
  PushSubscriptionExistsError,
  PushSubscriptionNotFoundError,
  QuietHoursActiveError,
  SubscriptionExpiredError,
  VapidNotConfiguredError,
  DEFAULT_NOTIFICATION_PREFERENCES,
  type BaseMarkAsReadRequest,
  type Notification,
  type NotificationPreferences,
  type NotificationPreferencesConfig,
  type NotificationsListRequest,
  type NotificationsListResponse,
  type BatchSendResult,
  type NotificationAction,
  type NotificationChannel,
  type NotificationMessage,
  type NotificationPayload,
  type NotificationPriority,
  type NotificationType,
  type NotificationTypePreference,
  type PreferencesResponse,
  type PushSubscription,
  type PushSubscriptionKeys,
  type SendNotificationRequest,
  type SendNotificationResponse,
  type PushSendResult,
  type StoredPushSubscription,
  type SubscribeRequest,
  type SubscribeResponse,
  type UnsubscribeRequest,
  type UnsubscribeResponse,
  type UpdatePreferencesRequest,
  type VapidKeyResponse,
} from './notifications';

export {
  getSessionAge,
  isSessionActive,
  isSessionRevoked,
  createUserSessionSchema,
  updateUserSessionSchema,
  userSessionSchema,
  type CreateUserSession,
  type UpdateUserSession,
  type UserSession,
} from './sessions';

export {
  createTenantSchema,
  tenantSchema,
  updateTenantSchema,
  type CreateTenantInput,
  type Tenant,
  type UpdateTenantInput,
} from './tenant';

export {
  aggregateSnapshots,
  aggregateValues,
  isOverQuota,
  usageMetricSchema,
  usageSnapshotSchema,
  type UsageMetric,
  type UsageSnapshot,
} from './usage-metering';

export {
  getAllRoles,
  getRoleDisplayName,
  isAdmin,
  isModerator,
  isUser,
  canUser,
  hasRole,
  isOwner,
  isRegularUser,
  usersContract,
  APP_ROLES,
  appRoleSchema,
  avatarDeleteResponseSchema,
  avatarUploadResponseSchema,
  changePasswordRequestSchema,
  changePasswordResponseSchema,
  revokeAllSessionsResponseSchema,
  revokeSessionResponseSchema,
  sessionSchema,
  sessionsListResponseSchema,
  updateProfileRequestSchema,
  userIdSchema,
  userSchema,
  type AppRole,
  type AvatarDeleteResponse,
  type AvatarUploadResponse,
  type ChangePasswordRequest,
  type ChangePasswordResponse,
  type RevokeAllSessionsResponse,
  type RevokeSessionResponse,
  type Session,
  type SessionsListResponse,
  type UpdateProfileRequest,
  type User,
  type UserId,
} from './users';

export {
  calculateRetryDelay,
  isDeliveryTerminal,
  matchesEventFilter,
  shouldRetryDelivery,
  createWebhookDeliverySchema,
  createWebhookSchema,
  updateWebhookDeliverySchema,
  updateWebhookSchema,
  WEBHOOK_DELIVERY_STATUSES,
  webhookDeliverySchema,
  webhookSchema,
  type CreateWebhook,
  type CreateWebhookDelivery,
  type UpdateWebhook,
  type UpdateWebhookDelivery,
  type Webhook,
  type WebhookDelivery,
  type WebhookDeliveryStatus,
} from './webhooks';
