// main/apps/web/src/features/settings/index.ts
/**
 * Settings Feature
 *
 * User profile and settings management.
 */

// Pages
export { SettingsPage } from './pages';

// Components
export {
  ApiKeyScopeSelector,
  ApiKeysManagement,
  AvatarUpload,
  ConsentPreferences,
  CookieConsentBanner,
  DangerZone,
  DataControlsSection,
  DataExportSection,
  DevicesList,
  EmailChangeForm,
  ForgotPasswordShortcut,
  NotificationPreferencesForm,
  OAuthConnectionsList,
  PasskeyManagement,
  PasswordChangeForm,
  PhoneManagement,
  PreferencesSection,
  ProfileCompleteness,
  ProfileForm,
  SessionCard,
  SessionsList,
  SudoModal,
  TotpManagement,
  TotpQrCode,
  UsernameForm,
} from './components';
export type {
  ApiKeyScopeSelectorProps,
  ApiKeysManagementProps,
  AvatarUploadProps,
  CookieConsentBannerProps,
  DangerZoneProps,
  DataControlsSectionProps,
  DataExportSectionProps,
  EmailChangeFormProps,
  ForgotPasswordShortcutProps,
  NotificationPreferencesFormProps,
  OAuthConnectionsListProps,
  PasskeyManagementProps,
  PasswordChangeFormProps,
  PreferencesSectionProps,
  ProfileCompletenessProps,
  ProfileFormProps,
  SessionCardProps,
  SessionsListProps,
  SudoModalProps,
  TotpManagementProps,
  UsernameFormProps,
} from './components';

// Hooks
export {
  useDeactivateAccount,
  useDeleteAccount,
  useReactivateAccount,
  useApiKeys,
  useCreateApiKey,
  useDeleteApiKey,
  useRevokeApiKey,
  useAvatarDelete,
  useAvatarUpload,
  useConsent,
  useUpdateConsent,
  useDataExport,
  usePasswordChange,
  useProfileUpdate,
  useProfileCompleteness,
  useRevokeAllSessions,
  useRevokeSession,
  useSessions,
  useSudo,
  useTotpManagement,
  useUndoHandler,
  useUsernameUpdate,
} from './hooks';
export type {
  UseDeactivateAccountOptions,
  UseDeactivateAccountResult,
  UseDeleteAccountOptions,
  UseDeleteAccountResult,
  UseReactivateAccountOptions,
  UseReactivateAccountResult,
  UseApiKeysResult,
  UseCreateApiKeyOptions,
  UseCreateApiKeyResult,
  UseDeleteApiKeyOptions,
  UseDeleteApiKeyResult,
  UseRevokeApiKeyOptions,
  UseRevokeApiKeyResult,
  UseAvatarDeleteOptions,
  UseAvatarDeleteResult,
  UseAvatarUploadOptions,
  UseAvatarUploadResult,
  UpdateConsentInput,
  UpdateConsentResponse,
  ConsentPreferences as UseConsentPreferences,
  UseConsentResult,
  UseUpdateConsentResult,
  DataExportInfo,
  ExportStatus,
  UseDataExportResult,
  UsePasswordChangeOptions,
  UsePasswordChangeResult,
  UseProfileUpdateOptions,
  UseProfileUpdateResult,
  UseProfileCompletenessResult,
  UseRevokeAllSessionsOptions,
  UseRevokeAllSessionsResult,
  UseRevokeSessionOptions,
  UseRevokeSessionResult,
  UseSessionsResult,
  UseSudoOptions,
  UseSudoResult,
  TotpState,
  UseTotpManagementResult,
  UseUsernameUpdateOptions,
  UseUsernameUpdateResult,
} from './hooks';

// API
export { createSettingsApi } from './api';
export type {
  ApiError,
  AvatarDeleteResponse,
  AvatarUploadResponse,
  ChangePasswordRequest,
  ChangePasswordResponse,
  RevokeAllSessionsResponse,
  RevokeSessionResponse,
  Session,
  SessionsListResponse,
  SettingsApi,
  SettingsApiConfig,
  UpdateProfileRequest,
  User,
} from './api';
